Repository apache/incubator-kie-tools, pull requests merged in 2020-04, with the labels that each got.

#101 Changing SVG name to *-svg.svg
  packages/online-editor/src/editor/EditorPage.tsx
  packages/vscode-extension/src/KogitoEditor.ts
Labels: do not merge

#103 KOGITO-1667: Linux release should maintain permissions
  .github/workflows/ci.yml
  packages/desktop/package.json
  packages/hub/package.json
  yarn.lock
Labels: order: 2

#134 Bump editors to 7.36.1.Final
  packages/kie-bc-editors-unpacked/pom.xml
Labels: order: 1

#128 Release 0.3.1
  lerna.json
  packages/chrome-extension-pack-kogito-kie-editors/package.json
  packages/chrome-extension-pack-kogito-kie-editors/static/manifest.json
  packages/chrome-extension/package.json
  packages/core-api/package.json
  packages/desktop/package.json
  packages/hub/package.json
  packages/kie-bc-editors-unpacked/package.json
  packages/kie-bc-editors/package.json
  packages/microeditor-envelope-protocol/package.json
  packages/microeditor-envelope/package.json
  packages/online-editor/package.json
  packages/vscode-extension-pack-kogito-kie-editors/README.md
  packages/vscode-extension-pack-kogito-kie-editors/package.json
  packages/vscode-extension/package.json
Labels: order: 2
