Repository apache/incubator-kie-tools, pull requests merged in 2020-09, with the labels that each got.

#236 FAI-235: PMML: Enhance marshaller for DMN's use case
  packages/pmml-editor-marshaller/src/__tests__/marshaller/AnomalyDetectionModel.test.ts
  packages/pmml-editor-marshaller/src/__tests__/marshaller/AssociationModel.test.ts
  packages/pmml-editor-marshaller/src/__tests__/marshaller/BaselineModel.test.ts
  packages/pmml-editor-marshaller/src/__tests__/marshaller/BayesianNetworkModel.test.ts
  packages/pmml-editor-marshaller/src/__tests__/marshaller/ClusteringModel.test.ts
  packages/pmml-editor-marshaller/src/__tests__/marshaller/GaussianProcessModel.test.ts
  packages/pmml-editor-marshaller/src/__tests__/marshaller/GeneralRegressionModel.test.ts
  packages/pmml-editor-marshaller/src/__tests__/marshaller/MiningModel.test.ts
  packages/pmml-editor-marshaller/src/__tests__/marshaller/NaiveBayesModel.test.ts
  packages/pmml-editor-marshaller/src/__tests__/marshaller/NearestNeighborModel.test.ts
  packages/pmml-editor-marshaller/src/__tests__/marshaller/NeuralNetwork.test.ts
  packages/pmml-editor-marshaller/src/__tests__/marshaller/RuleSetModel.test.ts
  packages/pmml-editor-marshaller/src/__tests__/marshaller/SequenceModel.test.ts
  packages/pmml-editor-marshaller/src/__tests__/marshaller/SupportVectorMachineModel.test.ts
  packages/pmml-editor-marshaller/src/__tests__/marshaller/TestData_AnomalyDetectionModel.ts
  packages/pmml-editor-marshaller/src/__tests__/marshaller/TestData_AssociationModel.ts
  packages/pmml-editor-marshaller/src/__tests__/marshaller/TestData_BaselineModel.ts
  packages/pmml-editor-marshaller/src/__tests__/marshaller/TestData_BayesianNetworkModel.ts
  packages/pmml-editor-marshaller/src/__tests__/marshaller/TestData_ClusteringModel.ts
  packages/pmml-editor-marshaller/src/__tests__/marshaller/TestData_GaussianProcessModel.ts
  packages/pmml-editor-marshaller/src/__tests__/marshaller/TestData_GeneralRegressionModel.ts
  packages/pmml-editor-marshaller/src/__tests__/marshaller/TestData_MiningModel.ts
  packages/pmml-editor-marshaller/src/__tests__/marshaller/TestData_NaiveBayesModel.ts
  packages/pmml-editor-marshaller/src/__tests__/marshaller/TestData_NearestNeighborModel.ts
  packages/pmml-editor-marshaller/src/__tests__/marshaller/TestData_NeuralNetwork.ts
  packages/pmml-editor-marshaller/src/__tests__/marshaller/TestData_RuleSetModel.ts
  packages/pmml-editor-marshaller/src/__tests__/marshaller/TestData_SequenceModel.ts
  packages/pmml-editor-marshaller/src/__tests__/marshaller/TestData_SupportVectorMachineModel.ts
  packages/pmml-editor-marshaller/src/__tests__/marshaller/TestData_TextModel.ts
  packages/pmml-editor-marshaller/src/__tests__/marshaller/TestData_TimeSeriesModel.ts
  packages/pmml-editor-marshaller/src/__tests__/marshaller/TestData_TreeModel.ts
  packages/pmml-editor-marshaller/src/__tests__/marshaller/TextModel.test.ts
  packages/pmml-editor-marshaller/src/__tests__/marshaller/TimeSeriesModel.test.ts
  packages/pmml-editor-marshaller/src/__tests__/marshaller/TreeModel.test.ts
  packages/pmml-editor-marshaller/src/marshaller/Marshaller.ts
  packages/pmml-editor-marshaller/src/marshaller/jsonata/JSON2UI.ts
  packages/pmml-editor-marshaller/src/marshaller/jsonata/json2ui/AnomalyDetectionModel.ts
  packages/pmml-editor-marshaller/src/marshaller/jsonata/json2ui/AssociationModel.ts
  packages/pmml-editor-marshaller/src/marshaller/jsonata/json2ui/BaselineModel.ts
  packages/pmml-editor-marshaller/src/marshaller/jsonata/json2ui/BayesianNetworkModel.ts
  packages/pmml-editor-marshaller/src/marshaller/jsonata/json2ui/ClusteringModel.ts
  packages/pmml-editor-marshaller/src/marshaller/jsonata/json2ui/GaussianProcessModel.ts
  packages/pmml-editor-marshaller/src/marshaller/jsonata/json2ui/GeneralRegressionModel.ts
  packages/pmml-editor-marshaller/src/marshaller/jsonata/json2ui/MiningModel.ts
  packages/pmml-editor-marshaller/src/marshaller/jsonata/json2ui/NaiveBayesModel.ts
  packages/pmml-editor-marshaller/src/marshaller/jsonata/json2ui/NearestNeighborModel.ts
  packages/pmml-editor-marshaller/src/marshaller/jsonata/json2ui/NeuralNetwork.ts
  packages/pmml-editor-marshaller/src/marshaller/jsonata/json2ui/RuleSetModel.ts
  packages/pmml-editor-marshaller/src/marshaller/jsonata/json2ui/SequenceModel.ts
  packages/pmml-editor-marshaller/src/marshaller/jsonata/json2ui/SupportVectorMachineModel.ts
  packages/pmml-editor-marshaller/src/marshaller/jsonata/json2ui/TextModel.ts
  packages/pmml-editor-marshaller/src/marshaller/jsonata/json2ui/TimeSeriesModel.ts
  packages/pmml-editor-marshaller/src/marshaller/jsonata/json2ui/TreeModel.ts
  packages/pmml-editor-marshaller/src/marshaller/jsonata/json2ui/index.ts
Labels: order: 1, waiting-for-qe

#263 Added timeout to the CI jobs
  .github/workflows/ci.yml
  .github/workflows/pull_request_full_downstream_ci.yml
Labels: order: any

#264 Make @kogito-tooling/kie-bc-editors-unpacked actually pack the Editors
  packages/kie-bc-editors-unpacked/package.json
Labels: order: any, waiting-review

#260 KOGITO-2926: Provide `readOnly` property on EditorContext
  packages/editor/src/api/KogitoEditorEnvelopeApi.ts
  packages/editor/src/embedded/embedded/EmbeddedEditor.tsx
  packages/editor/src/envelope/KogitoEditorEnvelopeApiImpl.ts
  packages/editor/src/envelope/__tests__/CompositeEditorFactory.test.ts
  packages/kie-bc-editors/src/GwtEditorWrapperFactory.ts
  packages/kie-bc-editors/src/__tests__/GwtEditorWrapperFactory.test.ts
  packages/kie-bc-editors/src/api/EditorContextApi.ts
  packages/pmml-editor/src/__tests__/PMMLEditorFactory.test.ts
  packages/vscode-extension/src/KogitoEditor.ts
Labels: order: any, waiting-for-qe, waiting-review

#267 FAI-251: Score Cards: Setup showcase for PMML editor
  packages/envelope-bus/webpack.config.js
  packages/pmml-editor/package.json
  packages/pmml-editor/src/__tests__/PMMLEditorInterface.test.ts
  packages/pmml-editor/src/editor/PMMLEditor.tsx
  packages/pmml-editor/src/editor/PMMLEditorFactory.ts
  packages/pmml-editor/src/editor/index.ts
  packages/pmml-editor/src/showcase/index.tsx
  packages/pmml-editor/src/showcase/static/favicon.ico
  packages/pmml-editor/src/showcase/static/index.html
  packages/pmml-editor/src/showcase/static/resources/style.css
  packages/pmml-editor/tsconfig.json
  packages/pmml-editor/webpack.config.js
Labels: waiting-review

#261 KOGITO-3240: Fix convenience classes for use in `kogito-tooling-examples`
  packages/chrome-extension/src/app/components/common/KogitoMenu.tsx
  packages/chrome-extension/src/app/components/pr/IsolatedPrEditor.tsx
  packages/editor/src/embedded/embedded/EmbeddedEditor.tsx
  packages/editor/src/envelope/EditorEnvelopeView.tsx
  packages/editor/src/envelope/KogitoEditorEnvelope.tsx
  packages/editor/src/envelope/KogitoEditorEnvelopeApiImpl.ts
  packages/editor/src/envelope/LoadingScreen/LoadingScreen.tsx
  packages/editor/src/envelope/LoadingScreen/styles.scss
  packages/editor/src/envelope/__tests__/EditorEnvelopeView.test.tsx
  packages/editor/src/envelope/__tests__/LoadingScreen/LoadingScreen.test.tsx
  packages/editor/src/envelope/__tests__/LoadingScreen/__snapshots__/LoadingScreen.test.tsx.snap
  packages/editor/src/envelope/__tests__/__snapshots__/EditorEnvelopeView.test.tsx.snap
  packages/editor/src/envelope/index.ts
  packages/envelope/src/embedded/EmbeddedEnvelopeFactory.tsx
  packages/envelope/src/embedded/index.ts
Labels: waiting-review
