Repository apache/incubator-kie-tools, pull requests merged in 2020-06, with the labels that each got.

#185 KOGITO-2490: Shortcuts should not be triggered when typing on text inputs
  packages/microeditor-envelope/src/EditorEnvelopeController.tsx
  packages/microeditor-envelope/src/EditorEnvelopeView.tsx
  packages/microeditor-envelope/src/KeyBindingsHelpOverlay/KeyBindingsHelpOverlay.tsx
  packages/microeditor-envelope/src/__tests__/EditorEnvelopeController.test.tsx
  packages/microeditor-envelope/src/__tests__/EditorEnvelopeView.test.tsx
  packages/microeditor-envelope/src/__tests__/KeyBindingsHelpOverlay.test.tsx
  packages/microeditor-envelope/src/__tests__/__snapshots__/EditorEnvelopeController.test.tsx.snap
  packages/microeditor-envelope/src/__tests__/__snapshots__/EditorEnvelopeView.test.tsx.snap
  packages/microeditor-envelope/src/__tests__/keyboardShortcuts/DefaultKeyboardShortcutsService.test.ts
  packages/microeditor-envelope/src/__tests__/keyboardShortcuts/DefaultKeyboardShortcutsService.test.tsx
  packages/microeditor-envelope/src/api/keyboardShortcuts/DefaultKeyboardShortcutsService.ts
  packages/microeditor-envelope/src/api/keyboardShortcuts/KeyboardShorcutsApi.ts
  packages/microeditor-envelope/src/index.ts
Labels: order: 1, waiting-for-qe

#194 KOGITO-2534 Online editor is not loaded after Open in Online Editor button is clicked
  packages/chrome-extension-pack-kogito-kie-editors/src/background.ts
  packages/online-editor/src/index.tsx
Labels: order: any, waiting-for-qe

#195 KOGITO-2533 Icon with link to Online editor is not present in the GitHub file list
  packages/chrome-extension/src/app/Dependencies.ts
  packages/chrome-extension/src/app/components/tree/FileTreeWithExternalLink.tsx
  packages/chrome-extension/src/app/components/tree/OpenExternalEditorButton.tsx
Labels: order: any

#193 KOGITO-2542: Update Hub to install VS Code extension from Marketplace
  packages/hub/src/common/Constants.ts
  packages/hub/src/electron/Menu.ts
  packages/hub/src/electron/index.ts
  packages/hub/src/webview/App.tsx
  packages/hub/webpack.config.js
Labels: order: any, waiting-for-qe
