Repository apache/incubator-kie-tools, pull requests merged in 2020-07, with the labels that each got.

#189 FAI-178: FAI-179: PMML Scorecard marshaller
  .gitignore
  packages/pmml-editor/.gitignore
  packages/pmml-editor/package.json
  packages/pmml-editor/src/__tests__/marshaller/DataDictionary.test.ts
  packages/pmml-editor/src/__tests__/marshaller/Header.test.ts
  packages/pmml-editor/src/__tests__/marshaller/Interval.test.ts
  packages/pmml-editor/src/__tests__/marshaller/Scorecard.test.ts
  packages/pmml-editor/src/__tests__/marshaller/TestData_LinearRegressions.ts
  packages/pmml-editor/src/__tests__/marshaller/TestData_ScoreCards.ts
  packages/pmml-editor/src/__tests__/marshaller/Value.test.ts
  packages/pmml-editor/src/marshaller/Marshaller.ts
  packages/pmml-editor/src/marshaller/index.ts
  packages/pmml-editor/src/marshaller/jsonata/JSON2UI.ts
  packages/pmml-editor/src/marshaller/jsonata/UI2JSON.ts
  packages/pmml-editor/src/marshaller/jsonata/index.ts
  packages/pmml-editor/src/marshaller/jsonata/json2ui/DataDictionary.ts
  packages/pmml-editor/src/marshaller/jsonata/json2ui/Header.ts
  packages/pmml-editor/src/marshaller/jsonata/json2ui/MiningSchema.ts
  packages/pmml-editor/src/marshaller/jsonata/json2ui/Scorecard.ts
  packages/pmml-editor/src/marshaller/jsonata/json2ui/index.ts
  packages/pmml-editor/src/marshaller/jsonata/ui2json/DataDictionary.ts
  packages/pmml-editor/src/marshaller/jsonata/ui2json/Header.ts
  packages/pmml-editor/src/marshaller/jsonata/ui2json/MiningSchema.ts
  packages/pmml-editor/src/marshaller/jsonata/ui2json/Scorecard.ts
  packages/pmml-editor/src/marshaller/jsonata/ui2json/index.ts
  packages/pmml-editor/src/marshaller/model/README.md
  packages/pmml-editor/src/marshaller/model/pmml4_4.ts
  packages/pmml-editor/webpack.config.js
  yarn.lock
Labels: order: 1

#200 KOGITO-2601: Move State Control API to `kie-bc-editors`
  packages/chrome-extension-pack-kogito-kie-editors/src/envelope/index.ts
  packages/core-api/src/appformer/Editor.ts
  packages/embedded-editor/src/envelope/envelope.ts
  packages/kie-bc-editors/package.json
  packages/kie-bc-editors/src/GwtEditorWrapper.tsx
  packages/kie-bc-editors/src/GwtEditorWrapperFactory.ts
  packages/kie-bc-editors/src/__tests__/DummyEditor.tsx
  packages/kie-bc-editors/src/__tests__/GwtAppFormerApi.test.ts
  packages/kie-bc-editors/src/__tests__/GwtEditorWrapper.test.ts
  packages/kie-bc-editors/src/__tests__/GwtEditorWrapperFactory.test.ts
  packages/kie-bc-editors/src/__tests__/gwtStateControl/GwtCommandRegistry.test.ts
  packages/kie-bc-editors/src/__tests__/gwtStateControl/GwtStateControl.test.ts
  packages/kie-bc-editors/src/gwtStateControl/GwtStateControl.ts
  packages/kie-bc-editors/src/gwtStateControl/GwtStateControlCommand.ts
  packages/kie-bc-editors/src/gwtStateControl/KogitoCommandRegistry.ts
  packages/kie-bc-editors/src/gwtStateControl/index.ts
  packages/kie-bc-editors/src/index.ts
  packages/microeditor-envelope/src/EditorEnvelopeController.tsx
  packages/microeditor-envelope/src/EditorEnvelopeView.tsx
  packages/microeditor-envelope/src/EditorFactory.ts
  packages/microeditor-envelope/src/__tests__/DummyEditor.tsx
  packages/microeditor-envelope/src/__tests__/EditorEnvelopeController.test.tsx
  packages/microeditor-envelope/src/__tests__/EditorEnvelopeView.test.tsx
  packages/microeditor-envelope/src/__tests__/__snapshots__/EditorEnvelopeController.test.tsx.snap
  packages/microeditor-envelope/src/index.ts
  packages/vscode-extension-pack-kogito-kie-editors/src/webview/index.ts
  packages/vscode-extension/src/KogitoEditableDocument.ts
Labels: order: 2, waiting-for-qe

#199 KOGITO-2547: Include Webview into DefaultVsCodeRouter
  packages/vscode-extension-pack-kogito-kie-editors/src/extension/extension.ts
  packages/vscode-extension/src/DefaultVsCodeRouter.ts
  packages/vscode-extension/src/KogitoEditor.ts
  packages/vscode-extension/src/KogitoEditorFactory.ts
  packages/vscode-extension/src/KogitoEditorStore.ts
  packages/vscode-extension/src/index.ts
Labels: order: 1, waiting-for-qe

#216 Improve Webpack output
  package.json
  packages/chrome-extension-pack-kogito-kie-editors/webpack.config.js
  packages/chrome-extension/package.json
  packages/chrome-extension/webpack.config.js
  packages/core-api/webpack.config.js
  packages/desktop/package.json
  packages/desktop/webpack.config.js
  packages/embedded-editor/package.json
  packages/embedded-editor/webpack.config.js
  packages/guided-tour/package.json
  packages/guided-tour/webpack.config.js
  packages/hub/package.json
  packages/hub/webpack.config.js
  packages/keyboard-shortcuts/package.json
  packages/keyboard-shortcuts/webpack.config.js
  packages/kie-bc-editors/package.json
  packages/kie-bc-editors/webpack.config.js
  packages/microeditor-envelope-protocol/package.json
  packages/microeditor-envelope-protocol/webpack.config.js
  packages/microeditor-envelope/package.json
  packages/microeditor-envelope/webpack.config.js
  packages/online-editor/package.json
  packages/online-editor/webpack.config.js
  packages/pmml-editor/package.json
  packages/pmml-editor/webpack.config.js
  packages/vscode-extension-pack-kogito-kie-editors/webpack.config.js
  packages/vscode-extension/package.json
  packages/vscode-extension/webpack.config.js
  tsconfig.json
  webpack.common.config.js
  yarn.lock
Labels: order: any, waiting-review

#223 KOGITO-2834: Trigger kogito-tooling FDB manually
  .github/workflows/pull_request_full_downstream_ci.yml
Labels: order: any, waiting-review

#220 KOGITO-2833: Remove Enzyme as snapshot serializer
  package.json
  packages/chrome-extension/jest.config.js
  packages/chrome-extension/jest/jest-env-setup.js
  packages/microeditor-envelope/jest.config.js
  packages/microeditor-envelope/jest/jest-env-setup.js
  packages/microeditor-envelope/src/LoadingScreen/LoadingScreen.tsx
  packages/microeditor-envelope/src/__tests__/DummyEditor.tsx
  packages/microeditor-envelope/src/__tests__/EditorEnvelopeController.test.tsx
  packages/microeditor-envelope/src/__tests__/EditorEnvelopeView.test.tsx
  packages/microeditor-envelope/src/__tests__/LoadingScreen.test.tsx
  packages/microeditor-envelope/src/__tests__/__snapshots__/EditorEnvelopeController.test.tsx.snap
  packages/microeditor-envelope/src/__tests__/__snapshots__/EditorEnvelopeView.test.tsx.snap
  packages/microeditor-envelope/src/__tests__/__snapshots__/LoadingScreen.test.tsx.snap
  yarn.lock
Labels: order: any

#222 KOGITO-925: Online Editor deploy for every CI build
  .github/workflows/prerelease.yml
  .github/workflows/pull_request_full_downstream_ci.yml
Labels: do not merge

#231 KOGITO-2900: Daily cleanup of old online editor builds
  .github/workflows/daily_cleanup.yml
Labels: order: any

#203 KOGITO-1883: Improving pattern management for ResourceContentAPI to support Windows enviroments.
  packages/vscode-extension/src/KogitoEditorFactory.ts
  packages/vscode-extension/src/VsCodeResourceContentService.ts
Labels: order: any, waiting-for-qe

#230 KOGITO-2891: Upgrade electron version to 7.2.4 due to security vulnerability
  packages/desktop/package.json
  packages/hub/package.json
  yarn.lock
Labels: order: any, waiting-for-qe

#213 KOGITO-2659: Update PatternFly to the latest version
  packages/chrome-extension-pack-kogito-kie-editors/webpack.config.js
  packages/desktop/src/__tests__/webview/__snapshots__/App.test.tsx.snap
  packages/desktop/src/__tests__/webview/editor/__snapshots__/EditorToolbar.test.tsx.snap
  packages/desktop/src/__tests__/webview/home/__snapshots__/FilesPage.test.tsx.snap
  packages/desktop/src/webview/App.tsx
  packages/desktop/src/webview/editor/EditorPage.tsx
  packages/desktop/src/webview/editor/EditorToolbar.tsx
  packages/desktop/src/webview/home/FilesPage.tsx
  packages/desktop/src/webview/home/HomePage.tsx
  packages/desktop/src/webview/home/LearnMorePage.tsx
  packages/desktop/static/resources/style.css
  packages/desktop/webpack.config.js
  packages/embedded-editor/webpack.config.js
  packages/guided-tour/src/__tests__/components/__snapshots__/Dialog.test.tsx.snap
  packages/guided-tour/src/__tests__/components/__snapshots__/GuidedTour.test.tsx.snap
  packages/guided-tour/src/__tests__/components/__snapshots__/NavigationControls.test.tsx.snap
  packages/guided-tour/webpack.config.js
  packages/hub/src/webview/App.tsx
  packages/hub/static/resources/style.css
  packages/hub/webpack.config.js
  packages/keyboard-shortcuts/src/__tests__/common/KeyBindingHelpOverlay/__snapshots__/KeyBindingsHelpOverlay.test.tsx.snap
  packages/keyboard-shortcuts/webpack.config.js
  packages/microeditor-envelope/src/EditorEnvelopeView.tsx
  packages/microeditor-envelope/src/LoadingScreen/LoadingScreen.tsx
  packages/microeditor-envelope/src/LoadingScreen/spinner.scss
  packages/microeditor-envelope/src/LoadingScreen/styles.scss
  packages/microeditor-envelope/src/__tests__/__snapshots__/EditorEnvelopeController.test.tsx.snap
  packages/microeditor-envelope/src/__tests__/__snapshots__/EditorEnvelopeView.test.tsx.snap
  packages/microeditor-envelope/src/__tests__/__snapshots__/LoadingScreen.test.tsx.snap
  packages/microeditor-envelope/webpack.config.js
  packages/online-editor/src/App.tsx
  packages/online-editor/src/__tests__/editor/__snapshots__/EditorToolbar.test.tsx.snap
  packages/online-editor/src/common/GithubTokenModal.tsx
  packages/online-editor/src/editor/EditorPage.tsx
  packages/online-editor/src/editor/EditorToolbar.tsx
  packages/online-editor/src/home/DownloadHubModal.tsx
  packages/online-editor/src/home/HomePage.tsx
  packages/online-editor/src/index.tsx
  packages/online-editor/static/resources/style.css
  packages/online-editor/webpack.config.js
  packages/patternfly-base/package.json
  packages/patternfly-base/patternflyWebpackOptions.js
  packages/pmml-editor/webpack.config.js
  packages/vscode-extension-pack-kogito-kie-editors/webpack.config.js
  yarn.lock
Labels: order: 2, waiting-for-qe

#233 KOGITO-2841: Daily Online editor deploy
  .github/workflows/publish_daily_dev_version.yml
  .github/workflows/pull_request_full_downstream_ci.yml
Labels: order: any
