Repository apache/incubator-kie-tools, pull requests merged in 2020-12, with the labels that each got.

#308 KOGITO-3450: Export the Online Editor content using the Standalone Editor
  packages/online-editor/src/App.tsx
  packages/online-editor/src/__tests__/common/GithubService.test.ts
  packages/online-editor/src/__tests__/editor/EditorPage.test.tsx
  packages/online-editor/src/__tests__/editor/EditorToolbar.test.tsx
  packages/online-editor/src/__tests__/editor/__snapshots__/EditorToolbar.test.tsx.snap
  packages/online-editor/src/__tests__/home/HomePage.test.tsx
  packages/online-editor/src/common/GithubService.ts
  packages/online-editor/src/common/i18n/OnlineI18n.ts
  packages/online-editor/src/common/i18n/locales/en.ts
  packages/online-editor/src/editor/EditorPage.tsx
  packages/online-editor/src/editor/EditorToolbar.tsx
  packages/online-editor/src/editor/EmbedModal.tsx
  packages/online-editor/src/index.tsx
  packages/online-editor/static/resources/style.css
Labels: order: 1, waiting-for-qe

#344 Remove Maven from the build
  .github/workflows/ci.yml
  .github/workflows/daily_cleanup.yml
  .github/workflows/it-tests.yml
  .github/workflows/prerelease.yml
  .github/workflows/publish_artifacts.yml
  .github/workflows/publish_chrome_ext.yml
  .github/workflows/publish_daily_dev_version.yml
  .github/workflows/pull_request_full_downstream_ci.yml
  .gitignore
  package.json
  packages/backend-quarkus-runner-unpacked/.gitignore
  packages/backend-quarkus-runner-unpacked/package.json
  packages/backend-quarkus-runner-unpacked/pom.xml
  packages/channel-common-api/package.json
  packages/chrome-extension-pack-kogito-kie-editors/package.json
  packages/chrome-extension-pack-kogito-kie-editors/webpack.config.js
  packages/desktop/package.json
  packages/desktop/webpack.config.js
  packages/envelope-bus/package.json
  packages/envelope/package.json
  packages/external-assets-base/index.d.ts
  packages/external-assets-base/index.js
  packages/external-assets-base/package.json
  packages/i18n-common-dictionary/package.json
  packages/i18n/package.json
  packages/keyboard-shortcuts/package.json
  packages/kie-bc-editors-unpacked/package.json
  packages/kie-bc-editors-unpacked/pom.xml
  packages/kie-bc-editors/package.json
  packages/kie-editors-standalone/package.json
  packages/kie-editors-standalone/src/bpmn/BpmnEditorResources.ts
  packages/kie-editors-standalone/src/dmn/DmnEditorResources.ts
  packages/kie-editors-standalone/webpack.build-resources.config.js
  packages/online-editor/package.json
  packages/online-editor/webpack.config.js
  packages/vscode-extension-backend/package.json
  packages/vscode-extension-backend/webpack.config.js
  packages/vscode-extension-pack-kogito-kie-editors/package.json
  packages/vscode-extension-pack-kogito-kie-editors/webpack.config.js
  packages/vscode-extension/package.json
  yarn.lock
Labels: waiting-review

#191 KOGITO-2303: Use vscode-extension-tester to test the VS Code Extension
  package.json
  packages/vscode-extension-pack-kogito-kie-editors/.gitignore
  packages/vscode-extension-pack-kogito-kie-editors/.mocharc.json
  packages/vscode-extension-pack-kogito-kie-editors/.vscodeignore
  packages/vscode-extension-pack-kogito-kie-editors/package.json
  packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/extension-editors.test.ts
  packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/helpers/BpmnEditorTestHelper.ts
  packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/helpers/CommonAsserts.ts
  packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/helpers/CommonLocators.ts
  packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/helpers/DmnEditorTestHelper.ts
  packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/helpers/ScesimEditorTestHelper.ts
  packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/helpers/VSCodeTestHelper.ts
  packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/resources/demo.bpmn
  packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/resources/demo.dmn
  packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/resources/demo.scesim
  packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/resources/example.bpmn
  packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/resources/example.txt
  packages/vscode-extension-pack-kogito-kie-editors/src/ui-test/settings.json
  packages/vscode-extension-pack-kogito-kie-editors/tests-it/main.ts
  packages/vscode-extension-pack-kogito-kie-editors/tests-it/suite/extension.test.ts
  packages/vscode-extension-pack-kogito-kie-editors/tests-it/suite/index.ts
  packages/vscode-extension-pack-kogito-kie-editors/tests-it/test-workspace/demo.dmn
  packages/vscode-extension-pack-kogito-kie-editors/tests-it/tsconfig.json
  packages/vscode-extension-pack-kogito-kie-editors/tsconfig.json
  yarn.lock
Labels: order: any

#346 FAI-339: Score Cards: Outputs: UI does not update when undoing/redoing
  packages/pmml-editor/src/editor/components/EditorScorecard/molecules/CharacteristicsTableEditRow.tsx
  packages/pmml-editor/src/editor/components/EditorScorecard/molecules/CharacteristicsTableRow.scss
  packages/pmml-editor/src/editor/components/EditorScorecard/molecules/CharacteristicsTableRow.tsx
  packages/pmml-editor/src/editor/components/EditorScorecard/organisms/CharacteristicsTable.tsx
  packages/pmml-editor/src/editor/components/Outputs/organisms/OutputFieldsTable.tsx
Labels: order: any

#355 FAI-336: Fix undoing new fields (DD, Outputs, Characteristics) not exiting editing mode
  packages/pmml-editor/src/editor/components/EditorScorecard/organisms/CharacteristicsTable.tsx
  packages/pmml-editor/src/editor/components/Outputs/organisms/OutputFieldsTable.tsx
Labels: order: any, waiting-for-qe, waiting-review
