Repository apache/incubator-kie-tools, pull requests merged in 2021-01, with the labels that each got.

#358 FAI-335: Plugging data dictionary to state management (PMML editor PoC)
  packages/pmml-editor/package.json
  packages/pmml-editor/src/__tests__/editor/components/LandingPage/templates/__snapshots__/LandingPage.test.tsx.snap
  packages/pmml-editor/src/__tests__/editor/reducers/DataDictionaryFieldReducer.test.ts
  packages/pmml-editor/src/__tests__/editor/reducers/DataDictionaryReducer.test.ts
  packages/pmml-editor/src/editor/PMMLEditor.tsx
  packages/pmml-editor/src/editor/components/DataDictionary/ConstraintsEdit/ConstraintsEdit.tsx
  packages/pmml-editor/src/editor/components/DataDictionary/ConstraintsLabel/ConstraintsLabel.tsx
  packages/pmml-editor/src/editor/components/DataDictionary/ConstraintsRangeEdit/ConstraintsRangeEdit.tsx
  packages/pmml-editor/src/editor/components/DataDictionary/DataDictionaryContainer/DataDictionaryContainer.tsx
  packages/pmml-editor/src/editor/components/DataDictionary/DataDictionaryHandler/DataDictionaryHandler.tsx
  packages/pmml-editor/src/editor/components/DataDictionary/DataTypeItem/DataTypeItem.tsx
  packages/pmml-editor/src/editor/components/DataDictionary/DataTypesSort/DataTypesSort.tsx
  packages/pmml-editor/src/editor/components/DataDictionary/dataDictionaryUtils.ts
  packages/pmml-editor/src/editor/components/EditorScorecard/Operation.ts
  packages/pmml-editor/src/editor/reducers/Actions.ts
  packages/pmml-editor/src/editor/reducers/DataDictionaryFieldReducer.ts
  packages/pmml-editor/src/editor/reducers/DataDictionaryReducer.ts
  packages/pmml-editor/src/editor/reducers/DataFieldReducer.ts
  packages/pmml-editor/src/editor/reducers/index.ts
  packages/pmml-editor/src/showcase/HistoryButtons.tsx
Labels: order: any, waiting-for-qe

#366 FAI-344: Score Cards: Characteristic row is not rendered following pressing ESC to cancel
  packages/pmml-editor/src/editor/components/EditorScorecard/organisms/CharacteristicsTable.tsx
Labels: order: any, waiting-for-qe, waiting-review

#362 FAI-226: Score Cards: Refactor the Linear Regression Viewer to use new UI model (UI changes)
  packages/patternfly-base/package.json
  packages/pmml-editor/src/editor/PMMLModelHelper.ts
  packages/pmml-editor/src/editor/components/EditorCore/atoms/ModelTitle.tsx
  packages/pmml-editor/src/editor/components/EditorCore/molecules/EditorHeader.tsx
  packages/pmml-editor/src/editor/components/EditorCore/organisms/SingleEditorRouter.tsx
  packages/pmml-editor/src/editor/components/LinearRegressionViewer/molecules/LinearRegressionView.tsx
  packages/pmml-editor/src/editor/components/LinearRegressionViewer/molecules/LinearRegressionViewAdaptor.tsx
  packages/pmml-editor/src/editor/components/LinearRegressionViewer/molecules/index.ts
  packages/pmml-editor/src/editor/components/LinearRegressionViewer/templates/LinearRegressionViewerPage.scss
  packages/pmml-editor/src/editor/components/LinearRegressionViewer/templates/LinearRegressionViewerPage.tsx
  packages/pmml-editor/src/editor/components/LinearRegressionViewer/templates/index.ts
  yarn.lock
Labels: order: any

#371 FAI-350: Score Cards: Characteristic and Output rows do not scroll into view
  packages/pmml-editor/src/editor/components/EditorScorecard/organisms/CharacteristicsTable.tsx
  packages/pmml-editor/src/editor/components/Outputs/organisms/OutputFieldsTable.tsx
Labels: order: any, waiting-for-qe

#370 FAI-317: Data dictionary constraints and other properties handling
  packages/pmml-editor/src/__tests__/editor/reducers/DataDictionaryReducer.test.ts
  packages/pmml-editor/src/editor/components/DataDictionary/ConstraintsEdit/ConstraintsEdit.tsx
  packages/pmml-editor/src/editor/components/DataDictionary/ConstraintsEnumEdit/ConstraintsEnumEdit.scss
  packages/pmml-editor/src/editor/components/DataDictionary/ConstraintsEnumEdit/ConstraintsEnumEdit.tsx
  packages/pmml-editor/src/editor/components/DataDictionary/ConstraintsLabel/ConstraintsLabel.tsx
  packages/pmml-editor/src/editor/components/DataDictionary/ConstraintsRangeEdit/ConstraintsRangeEdit.scss
  packages/pmml-editor/src/editor/components/DataDictionary/ConstraintsRangeEdit/ConstraintsRangeEdit.tsx
  packages/pmml-editor/src/editor/components/DataDictionary/DataDictionaryContainer/DataDictionaryContainer.tsx
  packages/pmml-editor/src/editor/components/DataDictionary/DataDictionaryHandler/DataDictionaryHandler.tsx
  packages/pmml-editor/src/editor/components/DataDictionary/DataDictionaryPropertiesEdit/DataDictionaryPropertiesEdit.scss
  packages/pmml-editor/src/editor/components/DataDictionary/DataDictionaryPropertiesEdit/DataDictionaryPropertiesEdit.tsx
  packages/pmml-editor/src/editor/components/DataDictionary/DataTypeItem/DataTypeItem.scss
  packages/pmml-editor/src/editor/components/DataDictionary/DataTypeItem/DataTypeItem.tsx
  packages/pmml-editor/src/editor/components/DataDictionary/DataTypesSort/DataTypesSort.tsx
  packages/pmml-editor/src/editor/components/DataDictionary/PropertiesLabels/PropertiesLabels.scss
  packages/pmml-editor/src/editor/components/DataDictionary/PropertiesLabels/PropertiesLabels.tsx
  packages/pmml-editor/src/editor/components/DataDictionary/dataDictionaryUtils.ts
  packages/pmml-editor/src/editor/reducers/DataDictionaryReducer.ts
Labels: waiting-review

#376 KOGITO-4153: Fix extension clash in uitests and cleanup .vscode files
  packages/vscode-extension-pack-kogito-kie-editors/.vscode/launch.json
  packages/vscode-extension-pack-kogito-kie-editors/package.json
Labels: waiting-review

#377 KOGITO-3949: Fix duplicated Monaco artifact in Standalone Editors
  packages/kie-bc-editors/src/GwtEditorMapping.ts
  packages/kie-editors-standalone/src/bpmn/index.ts
Labels: waiting-for-qe

#367 FAI-345: Score Cards: Remove Reason Code field when Reason Codes are not used
  packages/pmml-editor/src/editor/components/EditorScorecard/atoms/AttributeLabels.tsx
  packages/pmml-editor/src/editor/components/EditorScorecard/atoms/CharacteristicLabels.tsx
  packages/pmml-editor/src/editor/components/EditorScorecard/molecules/AttributeEditor.tsx
  packages/pmml-editor/src/editor/components/EditorScorecard/molecules/AttributesTableRow.tsx
  packages/pmml-editor/src/editor/components/EditorScorecard/molecules/CharacteristicsTableEditRow.tsx
  packages/pmml-editor/src/editor/components/EditorScorecard/molecules/CharacteristicsTableRow.tsx
  packages/pmml-editor/src/editor/components/EditorScorecard/organisms/AttributesTable.tsx
  packages/pmml-editor/src/editor/components/EditorScorecard/organisms/CharacteristicsContainer.tsx
  packages/pmml-editor/src/editor/components/EditorScorecard/organisms/CharacteristicsTable.tsx
  packages/pmml-editor/src/editor/components/EditorScorecard/organisms/CorePropertiesTable.tsx
  packages/pmml-editor/src/editor/components/EditorScorecard/templates/ScorecardEditorPage.tsx
Labels: order: any

#387 KOGITO-4227: kogito-tooling: Upgrade immer to 8.0.1
  packages/pmml-editor/package.json
  yarn.lock
Labels: order: any, waiting-review

#375 KOGITO-4137: Update Patternfly to version 4.70.2
  packages/desktop/src/__tests__/webview/__snapshots__/App.test.tsx.snap
  packages/desktop/src/__tests__/webview/editor/__snapshots__/EditorToolbar.test.tsx.snap
  packages/desktop/src/__tests__/webview/home/__snapshots__/FilesPage.test.tsx.snap
  packages/editor/src/envelope/__tests__/KeyBindingHelpOverlay/__snapshots__/KeyBindingsHelpOverlay.test.tsx.snap
  packages/editor/src/envelope/__tests__/__snapshots__/EditorEnvelopeView.test.tsx.snap
  packages/guided-tour/src/__tests__/components/__snapshots__/Dialog.test.tsx.snap
  packages/guided-tour/src/__tests__/components/__snapshots__/GuidedTour.test.tsx.snap
  packages/guided-tour/src/__tests__/components/__snapshots__/NavigationControls.test.tsx.snap
  packages/hub/src/common/i18n/locales/en.ts
  packages/online-editor/src/__tests__/editor/EditorToolbar.test.tsx
  packages/online-editor/src/__tests__/editor/__snapshots__/EditorToolbar.test.tsx.snap
  packages/patternfly-base/package.json
  packages/pmml-editor/src/__tests__/editor/components/LandingPage/molecules/__snapshots__/LandingPageToolbar.test.tsx.snap
  packages/pmml-editor/src/__tests__/editor/components/LandingPage/molecules/__snapshots__/ModelCard.test.tsx.snap
  packages/pmml-editor/src/__tests__/editor/components/LandingPage/organisms/__snapshots__/EmptyStateNoContent.test.tsx.snap
  packages/pmml-editor/src/__tests__/editor/components/LandingPage/organisms/__snapshots__/EmptyStateNoModels.test.tsx.snap
  packages/pmml-editor/src/__tests__/editor/components/LandingPage/templates/__snapshots__/LandingPage.test.tsx.snap
  yarn.lock
Labels: do not merge

#388 FAI-375: Score Cards: Validation: Characteristic Baseline Score should be hidden when Model Baseline score is provided
  packages/pmml-editor/src/editor/components/EditorScorecard/molecules/CharacteristicsTableEditRow.tsx
Labels: order: any, waiting-review

#380 FAI-357: [Scorecard Editor] Model Setup and Characteristics panels restyle
  packages/pmml-editor/src/editor/components/EditorScorecard/atoms/CharacteristicLabel.tsx
  packages/pmml-editor/src/editor/components/EditorScorecard/atoms/CharacteristicLabels.tsx
  packages/pmml-editor/src/editor/components/EditorScorecard/molecules/AttributeToolbar.tsx
  packages/pmml-editor/src/editor/components/EditorScorecard/molecules/AttributesTableRow.tsx
  packages/pmml-editor/src/editor/components/EditorScorecard/molecules/CharacteristicsTableRow.tsx
  packages/pmml-editor/src/editor/components/EditorScorecard/molecules/CharacteristicsToolbar.scss
  packages/pmml-editor/src/editor/components/EditorScorecard/molecules/CharacteristicsToolbar.tsx
  packages/pmml-editor/src/editor/components/EditorScorecard/organisms/CharacteristicsContainer.scss
  packages/pmml-editor/src/editor/components/EditorScorecard/organisms/CharacteristicsContainer.tsx
  packages/pmml-editor/src/editor/components/EditorScorecard/organisms/CorePropertiesTable.scss
  packages/pmml-editor/src/editor/components/EditorScorecard/organisms/CorePropertiesTable.tsx
  packages/pmml-editor/src/editor/components/EditorScorecard/templates/ScorecardEditorPage.scss
  packages/pmml-editor/src/editor/components/EditorScorecard/templates/ScorecardEditorPage.tsx
Labels: order: any, waiting-review
