Repository apache/incubator-kie-tools, pull requests merged in 2021-07, with the labels that each got.

#540 FAI-519: Score Cards: Renaming a DataField does not update Attributes' predicates
  packages/pmml-editor/src/__tests__/editor/paths/PathBuilders.test.ts
  packages/pmml-editor/src/__tests__/editor/reducers/ScorecardReducer.test.ts
  packages/pmml-editor/src/__tests__/editor/validation/Attributes.test.ts
  packages/pmml-editor/src/editor/components/DataDictionary/DataTypeItem/DataTypeItem.tsx
  packages/pmml-editor/src/editor/components/EditorScorecard/molecules/CharacteristicsTableRow.tsx
  packages/pmml-editor/src/editor/components/EditorScorecard/organisms/CorePropertiesTable.tsx
  packages/pmml-editor/src/editor/paths/PathBuilders.ts
  packages/pmml-editor/src/editor/reducers/ScorecardReducer.ts
  packages/pmml-editor/src/editor/validation/Attributes.ts
  packages/pmml-editor/src/editor/validation/MiningSchema.ts
Labels: order: any

#541 KOGITO-5264: Create CLI tool to generate forms from tasks json schemas in Kogito Projects
  package.json
  packages/form-generation-tool/jest.config.js
  packages/form-generation-tool/package.json
  packages/form-generation-tool/src/__tests__/generation/formGenerationCommand.test.ts
  packages/form-generation-tool/src/__tests__/generation/fs/checks.test.ts
  packages/form-generation-tool/src/__tests__/generation/fs/loadProjectSchemas.test.ts
  packages/form-generation-tool/src/__tests__/generation/fs/resources/empty/pom.xml
  packages/form-generation-tool/src/__tests__/generation/fs/resources/full/pom.xml
  packages/form-generation-tool/src/__tests__/generation/fs/resources/full/schemas/empty.json
  packages/form-generation-tool/src/__tests__/generation/fs/resources/full/schemas/travels_ApplyForVisa.json
  packages/form-generation-tool/src/__tests__/generation/fs/resources/full/schemas/travels_ConfirmTravel.json
  packages/form-generation-tool/src/__tests__/generation/fs/storeFormAsset.test.ts
  packages/form-generation-tool/src/__tests__/generation/tools/formGenerationToolsRegistry.test.ts
  packages/form-generation-tool/src/__tests__/generation/tools/uniforms/patternfly/PatternflyFormGenerationTool.test.ts
  packages/form-generation-tool/src/__tests__/generation/tools/uniforms/patternfly/mock.ts
  packages/form-generation-tool/src/__tests__/jest.setup.ts
  packages/form-generation-tool/src/cli/cli.ts
  packages/form-generation-tool/src/cli/index.ts
  packages/form-generation-tool/src/generation/formGenerationCommand.ts
  packages/form-generation-tool/src/generation/fs/checks.ts
  packages/form-generation-tool/src/generation/fs/index.ts
  packages/form-generation-tool/src/generation/fs/loadProjectSchemas.ts
  packages/form-generation-tool/src/generation/fs/storeFormAsset.ts
  packages/form-generation-tool/src/generation/index.ts
  packages/form-generation-tool/src/generation/tools/formGenerationToolRegistry.ts
  packages/form-generation-tool/src/generation/tools/index.ts
  packages/form-generation-tool/src/generation/tools/uniforms/UniformsFormGenerationTool.ts
  packages/form-generation-tool/src/generation/tools/uniforms/patternfly/PatternflyFormGenerationTool.ts
  packages/form-generation-tool/src/generation/types.ts
  packages/form-generation-tool/src/index.ts
  packages/form-generation-tool/tsconfig.json
  packages/form-generation-tool/webpack.config.js
  packages/uniforms-patternfly-codegen/src/__tests__/__snapshots__/AutoForm.test.tsx.snap
  packages/uniforms-patternfly-codegen/src/resources/dateFunctions.txt
  packages/uniforms-patternfly-codegen/src/resources/timeFunctions.txt
  packages/uniforms-patternfly-codegen/src/uniforms/AutoForm.tsx
  packages/uniforms-patternfly-codegen/src/uniforms/NestField.tsx
  packages/uniforms-patternfly-codegen/src/uniforms/index.ts
  packages/uniforms-patternfly-codegen/src/uniforms/renderForm.tsx
  yarn.lock
Labels: order: any

#553 KOGITO-5496: Upgrade vscode-extension-tester to 4.1.0
  package.json
  packages/vscode-extension-pack-kogito-kie-editors/it-tests/extension-editors.test.ts
  packages/vscode-extension-pack-kogito-kie-editors/it-tests/helpers/VSCodeTestHelper.ts
  packages/vscode-extension-pack-kogito-kie-editors/it-tests/resources/SaveAssetTest.bpmn
  yarn.lock
Labels: order: 1

#556 BAQE-1821: Introduce mocha-multi-reporters to allow test management
  package.json
  packages/vscode-extension-pack-kogito-kie-editors/.mocharc.json
  packages/vscode-extension-pack-kogito-kie-editors/mocha-reporter-config.json
  yarn.lock
Labels: order: any, waiting-review

#536 KOGITO-4827: Reuse Datatypes across process IT tests
  packages/vscode-extension-pack-kogito-kie-editors/it-tests/extension-editors.test.ts
  packages/vscode-extension-pack-kogito-kie-editors/it-tests/helpers/BpmnLocators.ts
  packages/vscode-extension-pack-kogito-kie-editors/it-tests/helpers/CommonLocators.ts
  packages/vscode-extension-pack-kogito-kie-editors/it-tests/helpers/VSCodeTestHelper.ts
  packages/vscode-extension-pack-kogito-kie-editors/it-tests/helpers/bpmn/BpmnEditorTestHelper.ts
  packages/vscode-extension-pack-kogito-kie-editors/it-tests/helpers/bpmn/BpmnLocators.ts
  packages/vscode-extension-pack-kogito-kie-editors/it-tests/helpers/bpmn/DiagramExplorerHelper.ts
  packages/vscode-extension-pack-kogito-kie-editors/it-tests/helpers/bpmn/PropertiesPanelHelper.ts
  packages/vscode-extension-pack-kogito-kie-editors/it-tests/helpers/dmn/PropertiesPanelHelper.ts
  packages/vscode-extension-pack-kogito-kie-editors/it-tests/resources/ReuseDataTypeTest.bpmn
  packages/vscode-extension-pack-kogito-kie-editors/it-tests/resources/SaveAssetTest.bpmn
Labels: order: any

#561 BAQE-1821: Use mocha-jenkins-reporter only
  packages/vscode-extension-pack-kogito-kie-editors/mocha-reporter-config.json
Labels: order: any, waiting-review

#560 KOGITO-5542: Form Generation CLI: add form config file
  packages/form-generation-tool/src/__tests__/generation/formGenerationCommand.test.ts
  packages/form-generation-tool/src/__tests__/generation/fs/storeFormAsset.test.ts
  packages/form-generation-tool/src/__tests__/generation/tools/uniforms/bootstrap4/Bootstrap4FormGenerationTool.test.ts
  packages/form-generation-tool/src/__tests__/generation/tools/uniforms/patternfly/PatternflyFormGenerationTool.test.ts
  packages/form-generation-tool/src/generation/fs/storeFormAsset.ts
  packages/form-generation-tool/src/generation/tools/uniforms/UniformsFormGenerationTool.ts
  packages/form-generation-tool/src/generation/tools/uniforms/bootstrap4/Bootstrap4FormGenerationTool.ts
  packages/form-generation-tool/src/generation/tools/uniforms/patternfly/PatternflyFormGenerationTool.ts
  packages/form-generation-tool/src/generation/tools/uniforms/utils/UniformsSchemaUtils.ts
  packages/form-generation-tool/src/generation/types.ts
Labels: order: 2

#555 FAI-526: PredicateTest
  packages/pmml-editor/dev-webapp/HistoryButtons.tsx
  packages/pmml-editor/it-tests/cypress.json
  packages/pmml-editor/it-tests/fixtures/compound-predicate.pmml
  packages/pmml-editor/it-tests/fixtures/empty-characteristics-DD-defined.pmml
  packages/pmml-editor/it-tests/fixtures/simple-predicate.pmml
  packages/pmml-editor/it-tests/integration/data-fields.ts
  packages/pmml-editor/it-tests/integration/predicate.ts
  packages/pmml-editor/it-tests/support/commands.d.ts
  packages/pmml-editor/it-tests/support/commands.ts
  packages/pmml-editor/it-tests/support/index.ts
  packages/pmml-editor/it-tests/tsconfig.json
  packages/pmml-editor/src/editor/components/DataDictionary/DataDictionaryContainer/DataDictionaryContainer.tsx
  packages/pmml-editor/src/editor/components/DataDictionary/DataTypeItem/DataTypeItem.tsx
  packages/pmml-editor/src/editor/components/EditorCore/atoms/ModelTitle.tsx
  packages/pmml-editor/src/editor/components/EditorScorecard/atoms/AttributesTableAction.tsx
  packages/pmml-editor/src/editor/components/EditorScorecard/molecules/AttributeEditor.tsx
  packages/pmml-editor/src/editor/components/EditorScorecard/molecules/AttributeToolbar.tsx
  packages/pmml-editor/src/editor/components/EditorScorecard/molecules/AttributesTableRow.tsx
  packages/pmml-editor/src/editor/components/EditorScorecard/molecules/CharacteristicsTableEditRow.tsx
  packages/pmml-editor/src/editor/components/EditorScorecard/molecules/CharacteristicsTableRow.tsx
  packages/pmml-editor/src/editor/components/EditorScorecard/molecules/CharacteristicsToolbar.tsx
  packages/pmml-editor/src/editor/components/EditorScorecard/molecules/EmptyStateNoCharacteristics.tsx
  packages/pmml-editor/src/editor/components/EditorScorecard/organisms/CharacteristicsContainer.tsx
  packages/pmml-editor/src/editor/components/MiningSchema/MiningSchemaAddFields/MiningSchemaAddFields.tsx
  packages/pmml-editor/src/editor/components/Outputs/molecules/OutputFieldEditRow.tsx
  packages/pmml-editor/src/editor/components/Outputs/molecules/OutputFieldRow.tsx
  packages/pmml-editor/src/editor/components/Outputs/organisms/OutputsContainer.tsx
Labels: order: any
