Repository apache/incubator-kie-tools, pull requests merged in 2021-02, with the labels that each got.

#403 FAI-381: Score Cards: Changes to unmarshalled Characteristics not producing immer patches
  packages/pmml-editor-marshaller/src/__tests__/marshaller/Scorecard.test.ts
  packages/pmml-editor-marshaller/src/__tests__/marshaller/TestData_ScoreCards.ts
  packages/pmml-editor-marshaller/src/marshaller/Marshaller.ts
  packages/pmml-editor/src/editor/reducers/CharacteristicReducer.ts
  tslint.json
Labels: order: any, waiting-review

#405 FAI-380 [Scorecard Editor] Output validation
  packages/pmml-editor/src/editor/components/EditorCore/molecules/EditorHeader.tsx
  packages/pmml-editor/src/editor/components/EditorScorecard/atoms/GenericSelector.tsx
  packages/pmml-editor/src/editor/components/MiningSchema/MiningSchemaContainer/MiningSchemaContainer.tsx
  packages/pmml-editor/src/editor/components/MiningSchema/MiningSchemaFields/MiningSchemaFields.tsx
  packages/pmml-editor/src/editor/components/MiningSchema/MiningSchemaHandler/MiningSchemaHandler.tsx
  packages/pmml-editor/src/editor/components/Outputs/atoms/OutputFieldLabel.tsx
  packages/pmml-editor/src/editor/components/Outputs/atoms/OutputLabels.tsx
  packages/pmml-editor/src/editor/components/Outputs/atoms/OutputLabelsEditMode.tsx
  packages/pmml-editor/src/editor/components/Outputs/molecules/OutputFieldEditRow.tsx
  packages/pmml-editor/src/editor/components/Outputs/molecules/OutputFieldRow.tsx
  packages/pmml-editor/src/editor/components/Outputs/organisms/OutputFieldExtendedProperties.tsx
  packages/pmml-editor/src/editor/components/Outputs/organisms/OutputFieldsTable.tsx
  packages/pmml-editor/src/editor/components/Outputs/organisms/OutputsContainer.scss
  packages/pmml-editor/src/editor/components/Outputs/organisms/OutputsContainer.tsx
  packages/pmml-editor/src/editor/components/Outputs/organisms/OutputsHandler.tsx
  packages/pmml-editor/src/editor/reducers/MiningSchemaReducer.ts
  packages/pmml-editor/src/editor/reducers/ModelReducer.ts
  packages/pmml-editor/src/editor/reducers/OutputFieldReducer.ts
  packages/pmml-editor/src/editor/reducers/ScorecardReducer.ts
  packages/pmml-editor/src/editor/validation/Outputs.ts
Labels: order: 1, waiting-review

#419 KOGITO-4346: Move VSCode UI test execution into it-tests github workflow
  .github/workflows/it-tests.yml
  packages/vscode-extension-pack-kogito-kie-editors/.gitignore
  packages/vscode-extension-pack-kogito-kie-editors/.mocharc.json
  packages/vscode-extension-pack-kogito-kie-editors/package.json
Labels: order: any, waiting-review

#413 FAI-398: [Scorecard Editor] Back button for Data Dictionary, Mining Schema and Outputs properties view
  packages/pmml-editor/src/editor/components/DataDictionary/DataDictionaryPropertiesEdit/DataDictionaryPropertiesEdit.tsx
  packages/pmml-editor/src/editor/components/MiningSchema/MiningSchemaPropertiesEdit/MiningSchemaPropertiesEdit.scss
  packages/pmml-editor/src/editor/components/MiningSchema/MiningSchemaPropertiesEdit/MiningSchemaPropertiesEdit.tsx
  packages/pmml-editor/src/editor/components/Outputs/organisms/OutputsContainer.tsx
Labels: order: any, waiting-review

#421 FAI-348: Score Cards: When characteristic filter matches no rows, filter text is cleared
  packages/pmml-editor/src/editor/components/EditorScorecard/molecules/CharacteristicsToolbar.tsx
  packages/pmml-editor/src/editor/components/EditorScorecard/organisms/CharacteristicsContainer.tsx
  packages/pmml-editor/src/editor/components/EditorScorecard/templates/ScorecardEditorPage.tsx
Labels: order: any, waiting-for-qe, waiting-review

#412 FAI-387 [Scorecard editor] Reason code and Baseline/Partial scores validation
  packages/pmml-editor/src/editor/components/EditorScorecard/atoms/AttributeLabels.tsx
  packages/pmml-editor/src/editor/components/EditorScorecard/atoms/CharacteristicLabels.tsx
  packages/pmml-editor/src/editor/components/EditorScorecard/molecules/AttributeEditor.tsx
  packages/pmml-editor/src/editor/components/EditorScorecard/molecules/AttributesTableRow.tsx
  packages/pmml-editor/src/editor/components/EditorScorecard/molecules/CharacteristicsTableEditRow.tsx
  packages/pmml-editor/src/editor/components/EditorScorecard/molecules/CharacteristicsTableRow.tsx
  packages/pmml-editor/src/editor/components/EditorScorecard/organisms/AttributesTable.tsx
  packages/pmml-editor/src/editor/components/EditorScorecard/organisms/CharacteristicsContainer.scss
  packages/pmml-editor/src/editor/components/EditorScorecard/organisms/CharacteristicsContainer.tsx
  packages/pmml-editor/src/editor/components/EditorScorecard/organisms/CharacteristicsTable.tsx
  packages/pmml-editor/src/editor/components/EditorScorecard/organisms/CorePropertiesTable.tsx
  packages/pmml-editor/src/editor/components/EditorScorecard/templates/ScorecardEditorPage.tsx
  packages/pmml-editor/src/editor/paths/PathBuilders.ts
  packages/pmml-editor/src/editor/reducers/AttributesReducer.ts
  packages/pmml-editor/src/editor/reducers/CharacteristicReducer.ts
  packages/pmml-editor/src/editor/reducers/ModelReducer.ts
  packages/pmml-editor/src/editor/reducers/ScorecardReducer.ts
  packages/pmml-editor/src/editor/validation/Attributes.ts
  packages/pmml-editor/src/editor/validation/Characteristics.ts
  packages/pmml-editor/src/editor/validation/ModelCoreProperties.ts
Labels: order: 1

#422 FAI-413: Score Cards: Increase visual cues for editable entries
  packages/pmml-editor/src/editor/components/EditorScorecard/molecules/AttributesTableRow.tsx
  packages/pmml-editor/src/editor/components/EditorScorecard/organisms/CorePropertiesTable.tsx
  packages/pmml-editor/src/editor/components/EditorScorecard/templates/ScorecardEditorPage.scss
Labels: order: any, waiting-for-qe

#423 FAI-414: Score Cards: Characteristics container should scroll
  packages/pmml-editor/src/editor/components/EditorScorecard/organisms/CharacteristicsContainer.scss
  packages/pmml-editor/src/editor/components/EditorScorecard/organisms/CharacteristicsTable.tsx
  packages/pmml-editor/src/editor/components/Outputs/organisms/OutputFieldsTable.tsx
Labels: order: any, waiting-for-qe

#424 FAI-415: Score Cards: Max width for editor
  packages/pmml-editor/src/editor/components/EditorCore/atoms/ModelTitle.scss
  packages/pmml-editor/src/editor/components/EditorScorecard/organisms/CorePropertiesTable.tsx
  packages/pmml-editor/src/editor/components/EditorScorecard/templates/ScorecardEditorPage.scss
  packages/pmml-editor/src/editor/components/EditorScorecard/templates/ScorecardEditorPage.tsx
Labels: order: any
