Repository apache/incubator-kie-tools, pull requests merged in 2021-08, with the labels that each got.

#583 PR workflow: Publish the online-editor into staging area
  .github/workflows/cleanup_prs.yml
  .github/workflows/monorepo_pr_ci.yml
Labels: order: any

#579 KOGITO-4107: Set Cypress baseUrl in package.json in Standalone Editors ITs
  packages/kie-editors-standalone/it-tests/cypress/integration/both-bpmn-dmn.spec.ts
  packages/kie-editors-standalone/it-tests/cypress/integration/bpmn-editable.spec.ts
  packages/kie-editors-standalone/it-tests/cypress/integration/bpmn-read-only.spec.ts
  packages/kie-editors-standalone/it-tests/cypress/integration/bpmn-workitem.spec.ts
  packages/kie-editors-standalone/it-tests/cypress/integration/dmn-editable-data-type.ts
  packages/kie-editors-standalone/it-tests/cypress/integration/dmn-editable.spec.ts
  packages/kie-editors-standalone/it-tests/cypress/integration/dmn-readonly.spec.ts
  packages/kie-editors-standalone/package.json
Labels: wip

#611 KOGITO-3909: Activate the DMN dirty indicator test
  packages/kie-editors-standalone/it-tests/cypress/integration/dmn-editable-data-type.ts
Labels: do not merge
