Repository apache/incubator-kie-tools, pull requests merged in 2021-09, with the labels that each got.

#618 KOGITO-5838: Update vscode-extension-tester to 4.2.0
  package.json
  packages/vscode-extension-pack-kogito-kie-editors/it-tests/helpers/VSCodeTestHelper.ts
  yarn.lock
Labels: order: any

#615 Incorporate `kogito-tooling-go`
  .github/actions/setup-env/action.yml
  .github/actions/setup-kogito-tooling-bot/action.yml
  .github/supporting-files/publish_jitexecutor_native/README.md
  .github/supporting-files/publish_jitexecutor_native/package.json
  .github/workflows/publish_jitexecutor_native.yml
  .github/workflows/release.yml
  .github/workflows/staging.yml
  .gitignore
  .gitmodules
  README.md
  examples/base64png-editor-vscode-extension/package.json
  examples/todo-list-view-vscode-extension/package.json
  examples/webapp/package.json
  package.json
  packages/build-env/cli.js
  packages/build-env/graph.dot
  packages/build-env/index.js
  packages/desktop/package.json
  packages/dmn-dev-sandbox-deployment-base-image/package.json
  packages/extended-services/.vscode/launch.json
  packages/extended-services/LICENSE
  packages/extended-services/Makefile
  packages/extended-services/README.md
  packages/extended-services/go.mod
  packages/extended-services/go.sum
  packages/extended-services/main.go
  packages/extended-services/package.json
  packages/extended-services/pkg/config/config.go
  packages/extended-services/pkg/config/config.yaml
  packages/extended-services/pkg/images/icon-loading-linux.go
  packages/extended-services/pkg/images/icon-loading.go
  packages/extended-services/pkg/images/icon-started-linux.go
  packages/extended-services/pkg/images/icon-started.go
  packages/extended-services/pkg/images/icon-stopped-linux.go
  packages/extended-services/pkg/images/icon-stopped.go
  packages/extended-services/pkg/images/loading.ico
  packages/extended-services/pkg/images/loading.png
  packages/extended-services/pkg/images/started.ico
  packages/extended-services/pkg/images/started.png
  packages/extended-services/pkg/images/stopped.ico
  packages/extended-services/pkg/images/stopped.png
  packages/extended-services/pkg/kogito/constants.go
  packages/extended-services/pkg/kogito/main.go
  packages/extended-services/pkg/kogito/server.go
  packages/extended-services/pkg/kogito/systray.go
  packages/extended-services/pkg/utils/utils.go
  packages/extended-services/scripts/macos/build.sh
  packages/extended-services/scripts/macos/src/Info.plist
  packages/extended-services/scripts/macos/src/KieLogo.png
  packages/form-generation-tool/package.json
  packages/kie-bc-editors/package.json
  packages/uniforms-bootstrap4-codegen/package.json
  scripts/update_version.js
  yarn.lock
Labels: order: 1

#622 Add missing dependencies to useImperativeHandle on `EditorEnvelopeView`
  .github/workflows/monorepo_pr_ci.yml
  packages/editor/src/envelope/EditorEnvelopeView.tsx
Labels: order: any

#616 FAI-558: Score Cards: Algorithm Name cannot be cleared
  packages/pmml-editor/it-tests/integration/scorecard-model.ts
  packages/pmml-editor/src/editor/components/EditorScorecard/organisms/CorePropertiesTable.tsx
  packages/pmml-editor/tests/editor/components/EditorScorecard/organisms/CorePropertiesTable.test.tsx
  packages/pmml-editor/tests/editor/components/EditorScorecard/organisms/__snapshots__/CorePropertiesTable.test.tsx.snap
Labels: order: any

#621 KOGITO-5428: Introduce DMN Runner cypress test
  packages/build-env/graph.dot
  packages/online-editor/it-tests/integration/DMNRunnerTest.ts
  packages/online-editor/package.json
  packages/online-editor/src/editor/KieToolingExtendedServices/KieToolingExtendedServicesModal.tsx
  packages/online-editor/src/tour/GuidedTourInitializer.tsx
Labels: order: 2
