Repository apache/incubator-kie-tools, pull requests merged in 2021-12, with the labels that each got.

#710 KOGITO-6340: Fix Gist integration issues
  packages/online-editor/src/editor/EditorToolbar.tsx
  packages/online-editor/src/i18n/locales/en.ts
  packages/online-editor/src/settings/SettingsContext.tsx
  packages/online-editor/src/workspace/WorkspacesContext.tsx
  packages/online-editor/src/workspace/WorkspacesContextProvider.tsx
  packages/online-editor/src/workspace/components/NewWorkspaceFromUrlPage.tsx
  packages/online-editor/src/workspace/hooks/ImportableUrlHooks.tsx
  packages/online-editor/src/workspace/services/GitService.tsx
Labels: waiting-for-qe

#662 KOGITO-6193: Reactivate tests for DMN's new Boxed Expression component
  packages/chrome-extension-pack-kogito-kie-editors/it-tests/framework/editor/dmn/DecisionNavigator.ts
  packages/chrome-extension-pack-kogito-kie-editors/it-tests/framework/editor/dmn/DmnEditor.ts
  packages/chrome-extension-pack-kogito-kie-editors/it-tests/framework/editor/dmn/DmnExpressionEditor.ts
  packages/chrome-extension-pack-kogito-kie-editors/it-tests/tests/DmnExpressionEditorTest.ts
  packages/kie-editors-standalone/it-tests/cypress/fixtures/Traffic Violation.dmn
  packages/kie-editors-standalone/it-tests/cypress/integration/dmn-editable-data-type.spec.ts
  packages/kie-editors-standalone/it-tests/cypress/integration/dmn-new-expression-editor.spec.ts
  packages/online-editor/it-tests/integration/DMNExpressionEditor.ts
  packages/online-editor/it-tests/support/commands.ts
  packages/vscode-extension-pack-kogito-kie-editors/it-tests/extension-editors.test.ts
  packages/vscode-extension-pack-kogito-kie-editors/it-tests/helpers/dmn/BuiltInType.ts
  packages/vscode-extension-pack-kogito-kie-editors/it-tests/helpers/dmn/DecisionNavigatorHelper.ts
  packages/vscode-extension-pack-kogito-kie-editors/it-tests/helpers/dmn/DmnEditorTestHelper.ts
  packages/vscode-extension-pack-kogito-kie-editors/it-tests/helpers/dmn/EditorTabs.ts
  packages/vscode-extension-pack-kogito-kie-editors/it-tests/helpers/dmn/ExpressionEditorHelper.ts
  packages/vscode-extension-pack-kogito-kie-editors/it-tests/helpers/dmn/ExpressionType.ts
  packages/vscode-extension-pack-kogito-kie-editors/it-tests/resources/demo-expression.dmn
Labels: waiting-for-ci

#723 Bump Editors to version 8.5.4
  packages/boxed-expression-component/package.json
  packages/chrome-extension-pack-kogito-kie-editors/package.json
  packages/desktop/package.json
  packages/feel-input-component/package.json
  packages/kie-editors-standalone/package.json
  packages/online-editor/package.json
  packages/online-editor/src/editor/EditorToolbar.tsx
  packages/unitables/src/boxed/DmnRunnerTable.tsx
  packages/unitables/src/dmn/DmnAutoTable.tsx
  packages/unitables/src/dmn/style.css
  packages/vscode-extension-bpmn-editor/package.json
  packages/vscode-extension-dmn-editor/package.json
  packages/vscode-extension-pack-kogito-kie-editors/it-tests/helpers/dmn/ExpressionEditorHelper.ts
  packages/vscode-extension-pack-kogito-kie-editors/package.json
  patches/boxed-expression-component+8.5.4.patch
  patches/feel-input-component+8.5.4.patch
  yarn.lock
Labels: order: 1
