Repository apache/incubator-kie-tools, pull requests merged in 2022-10, with the labels that each got.

#1252 Moving pnpm-lock.yml formatting to bootstrap.js
  package.json
  scripts/bootstrap/bootstrap.js
Labels: Foundation

#1253 Point cors-proxy URLs to the new cluster
  .github/workflows/daily_dev_publish.yml
  .github/workflows/release_build.yml
  .github/workflows/staging_build.yml
Labels: Foundation

#1259 KOGITO-8077: KIE Tools Security updates (Java code)
  packages/backend-extended-services/pom.xml
  packages/serverless-workflow-diagram-editor/errai-bom/pom.xml
  packages/serverless-workflow-diagram-editor/pom.xml
  packages/stunner-editors/errai-bom/pom.xml
  packages/stunner-editors/pom.xml
Labels: dependencies, java

#1247 KOGITO-7366: [SWF Editor] Channel to GWT bridge to highlight a node
  packages/editor/src/api/Editor.ts
  packages/kie-bc-editors/src/common/GwtEditorWrapper.tsx
  packages/kie-bc-editors/src/common/consumedInteropApi/GwtAppFormerConsumedInteropApi.ts
  packages/kie-bc-editors/tests/DummyEditor.tsx
  packages/kie-bc-editors/tests/GwtAppFormerApi.test.ts
  packages/kie-bc-editors/tests/GwtEditorWrapper.test.ts
  packages/serverless-workflow-combined-editor/src/impl/ServerlessWorkflowTextEditorChannelApiImpl.ts
  packages/serverless-workflow-diagram-editor-envelope/src/api/ServerlessWorkflowDiagramEditorEnvelopeApi.ts
  packages/serverless-workflow-diagram-editor-envelope/src/envelope/ServerlessWorkflowDiagramEditorEnvelopeApiImpl.ts
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-kogito-app/src/main/java/org/kie/workbench/common/stunner/sw/client/editor/DiagramEditor.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-kogito-app/src/main/java/org/kie/workbench/common/stunner/sw/client/editor/DiagramEditorActivity.java
  packages/serverless-workflow-diagram-editor/uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/EditorActivity.java
  packages/serverless-workflow-diagram-editor/uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/util/JSFunctions.java
  packages/serverless-workflow-text-editor/src/api/ServerlessWorkflowTextEditorChannelApi.ts
  packages/serverless-workflow-text-editor/src/editor/textEditor/SwfTextEditorController.ts
  packages/vscode-extension-serverless-workflow-editor/src/extension/ServerlessWorkflowDiagramEditorChannelApiImpl.ts
  packages/vscode-extension-serverless-workflow-editor/src/extension/builtInVsCodeEditorSwfContributions.ts
Labels: Serverless Workflow

#1256 KOGITO-8063: [SWF Editor] Disable cross-language autocompletion in YAML
  packages/serverless-workflow-language-service/src/channel/SwfJsonLanguageService.ts
  packages/serverless-workflow-language-service/src/channel/SwfLanguageService.ts
  packages/serverless-workflow-language-service/src/channel/SwfYamlLanguageService.ts
  packages/serverless-workflow-language-service/src/channel/getNodeFormat.ts
  packages/serverless-workflow-language-service/src/channel/index.ts
  packages/serverless-workflow-language-service/src/channel/matchNodeWithLocation.ts
  packages/serverless-workflow-language-service/src/channel/types.ts
  packages/serverless-workflow-language-service/tests/SwfJsonLanguageService.test.ts
  packages/serverless-workflow-language-service/tests/SwfYamlLanguageService.test.ts
  packages/serverless-workflow-language-service/tests/getNodeFormat.test.ts
  packages/serverless-workflow-language-service/tests/testUtils.ts
Labels: waiting-for-qe, Serverless Workflow

#1123 KOGITO-7199: SWF Viewer - Usability improvements for mediators (Mouse Pointers)
  packages/serverless-workflow-diagram-editor/kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/canvas/LienzoCanvasView.java
  packages/serverless-workflow-diagram-editor/kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/components/mediators/LienzoCanvasMediators.java
  packages/serverless-workflow-diagram-editor/kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/test/java/org/kie/workbench/common/stunner/client/lienzo/canvas/LienzoCanvasViewTest.java
  packages/serverless-workflow-diagram-editor/kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/test/java/org/kie/workbench/common/stunner/client/lienzo/components/mediators/LienzoCanvasMediatorsTest.java
  packages/serverless-workflow-diagram-editor/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/AbstractCanvas.java
  packages/serverless-workflow-diagram-editor/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/AbstractCanvasView.java
  packages/serverless-workflow-diagram-editor/lienzo-core/src/main/java/com/ait/lienzo/client/core/mediator/MousePanMediator.java
  packages/serverless-workflow-diagram-editor/lienzo-core/src/main/java/com/ait/lienzo/client/core/mediator/MouseWheelZoomMediator.java
  packages/serverless-workflow-diagram-editor/lienzo-core/src/main/java/com/ait/lienzo/client/core/style/Style.java
  packages/serverless-workflow-diagram-editor/lienzo-core/src/main/java/com/ait/lienzo/client/widget/panel/mediators/PanelMediators.java
Labels: waiting-for-review, Serverless Workflow

#1269 KOGITO-7805: Enable SVG previews on file switcher
  packages/online-editor/src/App.tsx
  packages/online-editor/src/ResponsiveDropdown/ResponsiveDropdown.tsx
  packages/online-editor/src/ResponsiveDropdown/ResponsiveDropdownContext.tsx
  packages/online-editor/src/ResponsiveDropdown/ResponsiveDropdownModal.tsx
  packages/online-editor/src/ResponsiveDropdown/ResponsiveDropdownToggle.tsx
  packages/online-editor/src/ResponsiveDropdown/hooks.ts
  packages/online-editor/src/companionFs/CompanionFsHooks.ts
  packages/online-editor/src/companionFs/CompanionFsService.ts
  packages/online-editor/src/companionFs/LfsFsCache.ts
  packages/online-editor/src/companionFs/LfsStorageService.ts
  packages/online-editor/src/dmnRunnerInputs/DmnRunnerInputsDispatchContext.tsx
  packages/online-editor/src/dmnRunnerInputs/DmnRunnerInputsDispatchContextProvider.tsx
  packages/online-editor/src/dmnRunnerInputs/DmnRunnerInputsHook.tsx
  packages/online-editor/src/dmnRunnerInputs/DmnRunnerInputsService.tsx
  packages/online-editor/src/editor/DeleteDropdownWithConfirmation.tsx
  packages/online-editor/src/editor/DmnDevSandbox/OpenshiftDeploymentsDropdown.tsx
  packages/online-editor/src/editor/EditorPage.tsx
  packages/online-editor/src/editor/EditorToolbar.tsx
  packages/online-editor/src/editor/FileSwitcher.tsx
  packages/online-editor/src/editor/KieSandboxExtendedServices/KieSandboxExtendedServicesButtons.tsx
  packages/online-editor/src/editor/NewFileDropdownMenu.tsx
  packages/online-editor/src/filesList/FileDataList.tsx
  packages/online-editor/src/home/HomePage.tsx
  packages/online-editor/src/previewSvgs/PreviewSvgHooks.ts
  packages/online-editor/src/previewSvgs/PreviewSvgsContext.tsx
  packages/online-editor/src/previewSvgs/PreviewSvgsService.ts
  packages/online-editor/src/responsiveBreakpoints/ResponsiveBreakpoints.ts
  packages/online-editor/src/workspace/WorkspacesContext.tsx
  packages/online-editor/src/workspace/components/WorkspaceLabel.tsx
  packages/online-editor/src/workspace/components/WorkspaceLoadingCard.tsx
  packages/online-editor/src/workspace/components/WorkspaceStatusIndicator.tsx
  packages/online-editor/src/workspace/hooks/WorkspaceFileHooks.tsx
  packages/online-editor/src/workspace/hooks/WorkspaceHooks.tsx
  packages/online-editor/src/workspace/hooks/WorkspacesHooks.tsx
  packages/online-editor/src/workspace/relativePath/WorkspaceFileRelativePathParser.ts
  packages/online-editor/src/workspace/services/FsService.tsx
  packages/online-editor/src/workspace/services/WorkspaceService.tsx
  packages/online-editor/src/workspace/worker/api/WorkspaceBroadcastEvents.ts
  packages/online-editor/src/workspace/worker/api/WorkspaceEvents.ts
  packages/online-editor/src/workspace/worker/api/WorkspaceFileBroadcastEvents.ts
  packages/online-editor/src/workspace/worker/api/WorkspacesBroadcastEvents.ts
  packages/online-editor/src/workspace/worker/sharedWorker.ts
  packages/online-editor/static/resources/style.css
Labels: Foundation

#1268 0.24.0 CHANGELOGs
  packages/vscode-extension-bpmn-editor/CHANGELOG.md
  packages/vscode-extension-dmn-editor/CHANGELOG.md
  packages/vscode-extension-kie-ba-bundle/CHANGELOG.md
  packages/vscode-extension-kogito-bundle/CHANGELOG.md
  packages/vscode-extension-pmml-editor/CHANGELOG.md
  packages/vscode-extension-red-hat-business-automation-bundle/CHANGELOG.md
  packages/vscode-extension-serverless-workflow-editor/CHANGELOG.md
Labels: Foundation

#1264 KOGITO-8077: KIE Tools Security updates (3rd round)
  packages/backend-extended-services/pom.xml
  packages/vscode-extension-serverless-workflow-editor/it-tests/resources/greeting-flow/pom.xml
Labels: dependencies, java

#1282 Bump `dependency-plugin` to version `3.3.0`
  packages/dashbuilder/pom.xml
  packages/serverless-workflow-diagram-editor/pom.xml
  packages/stunner-editors/pom.xml
Labels: Foundation

#1287 Bump kie version to `8.29.0.Final`
  packages/stunner-editors/pom.xml
Labels: dependencies, java

#1292 Align knative CLI dependencies with Kogito 1.29.0
  packages/kn-plugin-workflow/env/index.js
Labels: Serverless Workflow

#1280 KOGITO-8077: KIE Tools Security updates - Update `electron` in `desktop` module.
  packages/desktop/package.json
  packages/desktop/src/backend/index.ts
  packages/desktop/src/storage/core/UserData.ts
  pnpm-lock.yaml
Labels: Foundation

#1146 KOGITO-7471: Auto-layout for SWF
  packages/serverless-workflow-diagram-editor/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/graph/command/impl/SetConnectionTargetNodeCommand.java
  packages/serverless-workflow-diagram-editor/lienzo-core/src/main/java/com/ait/lienzo/client/core/layout/AbstractLayoutService.java
  packages/serverless-workflow-diagram-editor/lienzo-core/src/main/java/com/ait/lienzo/client/core/layout/Edge.java
  packages/serverless-workflow-diagram-editor/lienzo-core/src/main/java/com/ait/lienzo/client/core/layout/Layout.java
  packages/serverless-workflow-diagram-editor/lienzo-core/src/main/java/com/ait/lienzo/client/core/layout/OrientedEdgeImpl.java
  packages/serverless-workflow-diagram-editor/lienzo-core/src/main/java/com/ait/lienzo/client/core/layout/ReorderedGraph.java
  packages/serverless-workflow-diagram-editor/lienzo-core/src/main/java/com/ait/lienzo/client/core/layout/VertexPosition.java
  packages/serverless-workflow-diagram-editor/lienzo-core/src/main/java/com/ait/lienzo/client/core/layout/graph/OutgoingEdge.java
  packages/serverless-workflow-diagram-editor/lienzo-core/src/main/java/com/ait/lienzo/client/core/layout/graph/Vertex.java
  packages/serverless-workflow-diagram-editor/lienzo-core/src/main/java/com/ait/lienzo/client/core/layout/sugiyama/GraphLayer.java
  packages/serverless-workflow-diagram-editor/lienzo-core/src/main/java/com/ait/lienzo/client/core/layout/sugiyama/GraphLayerImpl.java
  packages/serverless-workflow-diagram-editor/lienzo-core/src/main/java/com/ait/lienzo/client/core/layout/sugiyama/LayeredGraph.java
  packages/serverless-workflow-diagram-editor/lienzo-core/src/main/java/com/ait/lienzo/client/core/layout/sugiyama/OrientedEdge.java
  packages/serverless-workflow-diagram-editor/lienzo-core/src/main/java/com/ait/lienzo/client/core/layout/sugiyama/SugiyamaLayoutService.java
  packages/serverless-workflow-diagram-editor/lienzo-core/src/main/java/com/ait/lienzo/client/core/layout/sugiyama/step01/CycleBreaker.java
  packages/serverless-workflow-diagram-editor/lienzo-core/src/main/java/com/ait/lienzo/client/core/layout/sugiyama/step01/ReverseEdgesCycleBreaker.java
  packages/serverless-workflow-diagram-editor/lienzo-core/src/main/java/com/ait/lienzo/client/core/layout/sugiyama/step02/LongestPathVertexLayerer.java
  packages/serverless-workflow-diagram-editor/lienzo-core/src/main/java/com/ait/lienzo/client/core/layout/sugiyama/step02/VertexLayerer.java
  packages/serverless-workflow-diagram-editor/lienzo-core/src/main/java/com/ait/lienzo/client/core/layout/sugiyama/step03/DefaultVertexOrdering.java
  packages/serverless-workflow-diagram-editor/lienzo-core/src/main/java/com/ait/lienzo/client/core/layout/sugiyama/step03/LayerCrossingCount.java
  packages/serverless-workflow-diagram-editor/lienzo-core/src/main/java/com/ait/lienzo/client/core/layout/sugiyama/step03/MedianVertexLayerPositioning.java
  packages/serverless-workflow-diagram-editor/lienzo-core/src/main/java/com/ait/lienzo/client/core/layout/sugiyama/step03/VertexLayerPositioning.java
  packages/serverless-workflow-diagram-editor/lienzo-core/src/main/java/com/ait/lienzo/client/core/layout/sugiyama/step03/VertexOrdering.java
  packages/serverless-workflow-diagram-editor/lienzo-core/src/main/java/com/ait/lienzo/client/core/layout/sugiyama/step03/VerticesTransposer.java
  packages/serverless-workflow-diagram-editor/lienzo-core/src/main/java/com/ait/lienzo/client/core/layout/sugiyama/step04/DefaultVertexPositioning.java
  packages/serverless-workflow-diagram-editor/lienzo-core/src/main/java/com/ait/lienzo/client/core/layout/sugiyama/step04/LayerArrangement.java
  packages/serverless-workflow-diagram-editor/lienzo-core/src/main/java/com/ait/lienzo/client/core/layout/sugiyama/step04/VertexPositioning.java
  packages/serverless-workflow-diagram-editor/lienzo-core/src/test/java/com/ait/lienzo/client/core/layout/Graphs.java
  packages/serverless-workflow-diagram-editor/lienzo-core/src/test/java/com/ait/lienzo/client/core/layout/IntegrationTests.java
  packages/serverless-workflow-diagram-editor/lienzo-core/src/test/java/com/ait/lienzo/client/core/layout/sugiyama/LayeredGraphTest.java
  packages/serverless-workflow-diagram-editor/lienzo-core/src/test/java/com/ait/lienzo/client/core/layout/sugiyama/SugiyamaLayoutServiceTest.java
  packages/serverless-workflow-diagram-editor/lienzo-core/src/test/java/com/ait/lienzo/client/core/layout/sugiyama/step01/ReverseEdgesCycleBreakerTest.java
  packages/serverless-workflow-diagram-editor/lienzo-core/src/test/java/com/ait/lienzo/client/core/layout/sugiyama/step02/LongestPathVertexLayererTest.java
  packages/serverless-workflow-diagram-editor/lienzo-core/src/test/java/com/ait/lienzo/client/core/layout/sugiyama/step03/VertexOrderingTest.java
  packages/serverless-workflow-diagram-editor/lienzo-core/src/test/java/com/ait/lienzo/client/core/layout/sugiyama/step04/DefaultVertexPositioningTest.java
  packages/serverless-workflow-diagram-editor/lienzo-core/src/test/java/com/ait/lienzo/client/core/layout/sugiyama/step04/VertexPositioningTest.java
  packages/serverless-workflow-diagram-editor/lienzo-webapp/src/main/java/org/kie/lienzo/client/AutomaticLayoutExample.java
  packages/serverless-workflow-diagram-editor/lienzo-webapp/src/main/java/org/kie/lienzo/client/BaseLienzoExamples.java
  packages/serverless-workflow-diagram-editor/lienzo-webapp/src/main/java/org/kie/lienzo/client/util/WiresUtils.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/pom.xml
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/autolayout/AutoLayout.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/autolayout/Position.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/autolayout/elkjs/ELKEdge.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/autolayout/elkjs/ELKLayoutProperties.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/autolayout/elkjs/ELKNode.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/autolayout/elkjs/ELKUtils.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/autolayout/lienzo/LienzoAutoLayout.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/marshall/BuilderContext.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/marshall/Marshaller.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/resources/org/kie/workbench/common/stunner/sw/autolayout/elkjs/elk.bundled.js
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/test/java/org/kie/workbench/common/stunner/sw/autolayout/AutoLayoutBrokenTransitionTest.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/test/java/org/kie/workbench/common/stunner/sw/autolayout/AutoLayoutTest.java
Labels: waiting-for-qe, waiting-for-review, Serverless Workflow

#1237 KOGITO-7078 : SWF Viewer connector Labels
  packages/serverless-workflow-diagram-editor/kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/shape/view/wires/ext/WiresConnectorViewExt.java
  packages/serverless-workflow-diagram-editor/kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/test/java/org/kie/workbench/common/stunner/client/lienzo/shape/view/wires/ext/WiresConnectorViewExtTest.java
  packages/serverless-workflow-diagram-editor/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-client-api/src/main/java/org/kie/workbench/common/stunner/core/client/shape/view/HasTitle.java
  packages/serverless-workflow-diagram-editor/lienzo-core/src/main/java/com/ait/lienzo/client/core/shape/Text.java
  packages/serverless-workflow-diagram-editor/lienzo-core/src/main/java/com/ait/lienzo/client/core/shape/TextBoundsWrap.java
  packages/serverless-workflow-diagram-editor/lienzo-core/src/main/java/com/ait/lienzo/client/core/shape/wires/util/WiresConnectorLabel.java
  packages/serverless-workflow-diagram-editor/lienzo-tests/src/test/java/com/ait/lienzo/client/core/shape/TextBoundsWrapTest.java
  packages/serverless-workflow-diagram-editor/lienzo-tests/src/test/java/com/ait/lienzo/client/core/shape/wires/util/WiresConnectorLabelTest.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-client/src/main/java/org/kie/workbench/common/stunner/sw/client/shapes/TransitionShape.java
Labels: DO NOT MERGE, Serverless Workflow

#1293 KOGITO-8128: [SWF Editor] Diagram nodes highlighting is triggered too many times
  packages/serverless-workflow-text-editor/src/editor/textEditor/SwfTextEditorController.ts
  packages/vscode-extension-serverless-workflow-editor/src/extension/builtInVsCodeEditorSwfContributions.ts
Labels: Serverless Workflow

#1290 KOGITO-8101: SWF Viewer - warn user about duplicated state name
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/marshall/BuilderContext.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/marshall/Marshaller.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/marshall/MessageCode.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/marshall/StateMarshalling.java
Labels: Serverless Workflow

#1296 KOGITO-8119: [DMN Editor] Import Java classes thrown an exception in Windows
  packages/vscode-java-code-completion-extension-plugin/pom.xml
  packages/vscode-java-code-completion-extension-plugin/vscode-java-code-completion-extension-plugin-core/pom.xml
  packages/vscode-java-code-completion-extension-plugin/vscode-java-code-completion-extension-plugin-core/src/main/java/org/kogito/core/internal/DelegateHandler.java
  packages/vscode-java-code-completion-extension-plugin/vscode-java-code-completion-extension-plugin-core/src/main/java/org/kogito/core/internal/engine/ActivationChecker.java
  packages/vscode-java-code-completion-extension-plugin/vscode-java-code-completion-extension-plugin-core/src/main/java/org/kogito/core/internal/engine/ActivationFileVisitor.java
  packages/vscode-java-code-completion-extension-plugin/vscode-java-code-completion-extension-plugin-core/src/main/java/org/kogito/core/internal/engine/BuildInformation.java
  packages/vscode-java-code-completion-extension-plugin/vscode-java-code-completion-extension-plugin-core/src/main/java/org/kogito/core/internal/engine/JavaEngine.java
  packages/vscode-java-code-completion-extension-plugin/vscode-java-code-completion-extension-plugin-core/src/main/java/org/kogito/core/internal/handlers/AutocompleteHandler.java
  packages/vscode-java-code-completion-extension-plugin/vscode-java-code-completion-extension-plugin-core/src/main/java/org/kogito/core/internal/handlers/GetAccessorsHandler.java
  packages/vscode-java-code-completion-extension-plugin/vscode-java-code-completion-extension-plugin-core/src/main/java/org/kogito/core/internal/handlers/GetClassesHandler.java
  packages/vscode-java-code-completion-extension-plugin/vscode-java-code-completion-extension-plugin-core/src/main/java/org/kogito/core/internal/util/WorkspaceUtil.java
  packages/vscode-java-code-completion-extension-plugin/vscode-java-code-completion-extension-plugin-core/src/test/java/org/kogito/core/internal/engine/ActivationCheckerTest.java
  packages/vscode-java-code-completion-extension-plugin/vscode-java-code-completion-extension-plugin-core/src/test/java/org/kogito/core/internal/engine/ActivationFileVisitorTest.java
  packages/vscode-java-code-completion-extension-plugin/vscode-java-code-completion-extension-plugin-core/src/test/java/org/kogito/core/internal/engine/JavaEngineTest.java
  packages/vscode-java-code-completion-extension-plugin/vscode-java-code-completion-extension-plugin-core/src/test/java/org/kogito/core/internal/handlers/IsLanguageServerAvailableHandlerTest.java
  packages/vscode-java-code-completion-extension-plugin/vscode-java-code-completion-extension-plugin-core/src/test/java/org/kogito/core/internal/util/TestUtil.java
  packages/vscode-java-code-completion-extension-plugin/vscode-java-code-completion-extension-plugin-core/src/test/resources/test projéct/MyActivator.java
Labels: DMN/SceSim

#1295 Include SWF apps in the readme file
  README.md
Labels: Serverless Workflow

#1299 [0.25.0-prerelease] 0.25.0 CHANGELOGs
  packages/vscode-extension-bpmn-editor/CHANGELOG.md
  packages/vscode-extension-dmn-editor/CHANGELOG.md
  packages/vscode-extension-kie-ba-bundle/CHANGELOG.md
  packages/vscode-extension-red-hat-business-automation-bundle/CHANGELOG.md
Labels: Foundation

#1298 KOGITO-8187: Provide `quarkus.knative.name` arg during deploy
  packages/serverless-logic-sandbox/src/openshift/FileTemplate.tsx
  packages/serverless-logic-sandbox/src/openshift/OpenShiftContextProvider.tsx
  packages/serverless-logic-sandbox/src/openshift/OpenShiftService.tsx
Labels: Serverless Workflow

#1302 Build `vscode-extension-dashbuilder-editor` on `vscode_extensions_prod` job
  .github/workflows/release_build.yml
Labels: Foundation

#1294 0.25.0 CHANGELOGs
  packages/vscode-extension-bpmn-editor/CHANGELOG.md
  packages/vscode-extension-dashbuilder-editor/CHANGELOG.md
  packages/vscode-extension-dmn-editor/CHANGELOG.md
  packages/vscode-extension-kie-ba-bundle/CHANGELOG.md
  packages/vscode-extension-kogito-bundle/CHANGELOG.md
  packages/vscode-extension-pmml-editor/CHANGELOG.md
  packages/vscode-extension-red-hat-business-automation-bundle/CHANGELOG.md
  packages/vscode-extension-serverless-workflow-editor/CHANGELOG.md
Labels: Foundation

#1297 KOGITO-7833: [KIE Sandbox] Allow selecting the branch name to be used when cloning a Git repository
  README.md
  packages/cors-proxy-image/package.json
  packages/cors-proxy-image/patches/@isomorphic-git+cors-proxy+2.7.1.patch
  packages/online-editor/env/index.js
  packages/online-editor/it-tests/e2e/OpenFromSource.cy.ts
  packages/online-editor/package.json
  packages/online-editor/src/App.tsx
  packages/online-editor/src/authSources/AuthSourceHooks.tsx
  packages/online-editor/src/authSources/AuthSourceIcon.tsx
  packages/online-editor/src/editor/DmnDevSandbox/DmnDevSandboxContextProvider.tsx
  packages/online-editor/src/editor/EditorPage.tsx
  packages/online-editor/src/editor/EditorPageErrorPage.tsx
  packages/online-editor/src/editor/EditorToolbar.tsx
  packages/online-editor/src/editor/NewFileDropdownMenu.tsx
  packages/online-editor/src/gitRefs/GitRefs.tsx
  packages/online-editor/src/home/HomePage.tsx
  packages/online-editor/src/home/ImportFromUrlCard.tsx
  packages/online-editor/src/importFromUrl/AdvancedImportModalContent.tsx
  packages/online-editor/src/importFromUrl/ImportFromUrlHomePageCard.tsx
  packages/online-editor/src/importFromUrl/ImportSingleFileFromUrlForm.tsx
  packages/online-editor/src/importFromUrl/ImportableUrlHooks.tsx
  packages/online-editor/src/importFromUrl/NewWorkspaceFromUrlPage.tsx
  packages/online-editor/src/importFromUrl/NewWorkspaceWithEmptyFilePage.tsx
  packages/online-editor/src/importFromUrl/fetchSingleFileContent.ts
  packages/online-editor/src/navigation/Routes.ts
  packages/online-editor/src/settings/GitHubSettingsTab.tsx
  packages/online-editor/src/workspace/WorkspacesContext.tsx
  packages/online-editor/src/workspace/WorkspacesContextProvider.tsx
  packages/online-editor/src/workspace/components/NewWorkspaceFromUrlPage.tsx
  packages/online-editor/src/workspace/components/WorkspaceLabel.tsx
  packages/online-editor/src/workspace/constants/GitConstants.ts
  packages/online-editor/src/workspace/hooks/ImportableUrlHooks.tsx
  packages/online-editor/src/workspace/hooks/PromiseState.tsx
  packages/online-editor/src/workspace/services/GitService.tsx
  packages/online-editor/src/workspace/worker/api/GitServerRef.ts
  packages/online-editor/src/workspace/worker/api/WorkspaceOrigin.tsx
  packages/online-editor/src/workspace/worker/api/WorkspacesWorkerGitApi.ts
  packages/online-editor/src/workspace/worker/sharedWorker.ts
Labels: Foundation
