Repository apache/incubator-kie-tools, pull requests merged in 2022-01, with the labels that each got.

#735 Update Selenium version to 4.1.0
  package.json
  yarn.lock
Labels: waiting-review

#722 AF-2917: External Data Sets: Support Client loading
  packages/dashbuilder/appformer/uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-api/src/main/java/org/uberfire/ext/layout/editor/api/editor/LayoutComponent.java
  packages/dashbuilder/appformer/uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/main/java/org/uberfire/ext/layout/editor/client/infra/ConfigurationContext.java
  packages/dashbuilder/dashbuilder-client/dashbuilder-displayer-editor/src/main/java/org/dashbuilder/client/editor/DisplayerDragComponent.java
  packages/dashbuilder/dashbuilder-client/dashbuilder-displayer-editor/src/test/java/org/dashbuilder/client/editor/DisplayerDragComponentTest.java
  packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-app/src/main/java/org/dashbuilder/backend/services/dataset/provider/RuntimeBeanDataSetProvider.java
  packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-app/src/main/java/org/dashbuilder/backend/services/impl/RuntimeModelParserImpl.java
  packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-app/src/test/java/org/dashbuilder/backend/services/impl/RuntimeModelParserImplTest.java
  packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-client/src/main/java/org/dashbuilder/client/RuntimeClientLoader.java
  packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-client/src/main/java/org/dashbuilder/client/RuntimeCommunication.java
  packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-client/src/main/java/org/dashbuilder/client/RuntimeModelContentListener.java
  packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-client/src/main/java/org/dashbuilder/client/RuntimeModelResourceClient.java
  packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-client/src/main/java/org/dashbuilder/client/external/ExternalDataSetRegister.java
  packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-client/src/main/java/org/dashbuilder/client/navbar/AppNavBar.java
  packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-client/src/main/java/org/dashbuilder/client/parser/JSONRuntimeModelClientParser.java
  packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-client/src/main/java/org/dashbuilder/client/parser/RuntimeModelClientParser.java
  packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-client/src/main/java/org/dashbuilder/client/parser/RuntimeModelClientParserFactory.java
  packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-client/src/main/java/org/dashbuilder/client/resources/i18n/AppConstants.java
  packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-client/src/main/java/org/dashbuilder/client/screens/RouterScreen.java
  packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-client/src/main/java/org/dashbuilder/client/services/RuntimeBackendComponentFunctionService.java
  packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-client/src/main/java/org/dashbuilder/client/services/RuntimeDataSetClientServices.java
  packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-client/src/main/java/org/dashbuilder/client/widgets/UploadWidget.java
  packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-client/src/main/java/org/dashbuilder/client/widgets/view/UploadWidgetView.java
  packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-client/src/main/resources/org/dashbuilder/client/resources/i18n/AppConstants.properties
  packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-client/src/test/java/org/dashbuilder/client/RuntimeClientLoaderTest.java
  packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-shared/pom.xml
  packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-shared/src/main/java/org/dashbuilder/shared/marshalling/LayoutTemplateJSONMarshaller.java
  packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-shared/src/main/java/org/dashbuilder/shared/marshalling/RuntimeModelJSONMarshaller.java
  packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-shared/src/main/java/org/dashbuilder/shared/model/RuntimeModel.java
  packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-shared/src/test/java/org/dashbuilder/shared/marshalling/LayoutTemplateJSONMarshallerTest.java
  packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-shared/src/test/java/org/dashbuilder/shared/marshalling/RuntimeModelJSONMarshallerTest.java
  packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-shared/src/test/java/org/dashbuilder/shared/marshalling/RuntimeServiceResponseJSONMarshallerTest.java
  packages/dashbuilder/dashbuilder-shared/dashbuilder-displayer-api/src/main/java/org/dashbuilder/displayer/json/DisplayerSettingsJSONMarshaller.java
  packages/dashbuilder/kie-soup-dataset/kie-soup-dataset-api/src/main/java/org/dashbuilder/dataset/json/DataSetDefJSONMarshaller.java
  packages/dashbuilder/kie-soup-dataset/kie-soup-dataset-api/src/main/java/org/dashbuilder/dataset/json/ExternalDataSetJSONParser.java
  packages/dashbuilder/kie-soup-dataset/kie-soup-dataset-api/src/test/java/org/dashbuilder/dataset/json/ExternalDataSetParserTest.java
  packages/dashbuilder/kie-soup-dataset/kie-soup-dataset-external/src/main/java/org/dashbuilder/dataprovider/external/ExternalDataSetCaller.java
  packages/dashbuilder/kie-soup-dataset/kie-soup-dataset-external/src/main/java/org/dashbuilder/dataprovider/external/ExternalDataSetHelper.java
  packages/dashbuilder/kie-soup-dataset/kie-soup-dataset-external/src/main/java/org/dashbuilder/dataprovider/external/ExternalDataSetProvider.java
Labels: order: any, waiting-review

#708 Fork LightningFS into `kie-sandbox-fs`
  .gitignore
  packages/build-env/graph.dot
  packages/kie-sandbox-fs/LICENSE
  packages/kie-sandbox-fs/README.md
  packages/kie-sandbox-fs/karma.conf.js
  packages/kie-sandbox-fs/package.json
  packages/kie-sandbox-fs/src/CacheFS.js
  packages/kie-sandbox-fs/src/DefaultBackend.d.ts
  packages/kie-sandbox-fs/src/DefaultBackend.js
  packages/kie-sandbox-fs/src/DexieBackend.d.ts
  packages/kie-sandbox-fs/src/DexieBackend.js
  packages/kie-sandbox-fs/src/IdbBackend.js
  packages/kie-sandbox-fs/src/Mutex.js
  packages/kie-sandbox-fs/src/Mutex2.js
  packages/kie-sandbox-fs/src/PromisifiedFS.js
  packages/kie-sandbox-fs/src/Stat.js
  packages/kie-sandbox-fs/src/clock.js
  packages/kie-sandbox-fs/src/errors.js
  packages/kie-sandbox-fs/src/index.d.ts
  packages/kie-sandbox-fs/src/index.js
  packages/kie-sandbox-fs/src/path.js
  packages/kie-sandbox-fs/src/superblocktxt.js
  packages/kie-sandbox-fs/tests/CacheFS.spec.js
  packages/kie-sandbox-fs/tests/__fixtures__/test-folder/.superblock.txt
  packages/kie-sandbox-fs/tests/__fixtures__/test-folder/0/a.txt
  packages/kie-sandbox-fs/tests/__fixtures__/test-folder/0/b.txt
  packages/kie-sandbox-fs/tests/__fixtures__/test-folder/0/c.txt
  packages/kie-sandbox-fs/tests/__fixtures__/test-folder/1/d.txt
  packages/kie-sandbox-fs/tests/__fixtures__/test-folder/1/e.txt
  packages/kie-sandbox-fs/tests/__fixtures__/test-folder/1/f.txt
  packages/kie-sandbox-fs/tests/__fixtures__/test-folder/2/a.txt
  packages/kie-sandbox-fs/tests/__fixtures__/test-folder/a.txt
  packages/kie-sandbox-fs/tests/__fixtures__/test-folder/b.txt
  packages/kie-sandbox-fs/tests/__fixtures__/test-folder/c.txt
  packages/kie-sandbox-fs/tests/__fixtures__/test-folder/not-in-superblock.txt
  packages/kie-sandbox-fs/tests/__fixtures__/tree.txt.js
  packages/kie-sandbox-fs/tests/fs-dexie.promises.bulk.spec.js
  packages/kie-sandbox-fs/tests/fs-dexie.promises.spec.js
  packages/kie-sandbox-fs/tests/fs-dexie.spec.js
  packages/kie-sandbox-fs/tests/fs.promises.spec.js
  packages/kie-sandbox-fs/tests/fs.spec.js
  packages/kie-sandbox-fs/tests/hotswap-backends-1.spec.js
  packages/kie-sandbox-fs/tests/hotswap-backends-2.spec.js
  packages/kie-sandbox-fs/tests/hotswap-backends-3.spec.js
  packages/kie-sandbox-fs/tests/hotswap-backends-4.spec.js
  packages/kie-sandbox-fs/tests/path.spec.js
  packages/online-editor/package.json
  packages/online-editor/src/workspace/WorkspacesContext.tsx
  packages/online-editor/src/workspace/WorkspacesContextProvider.tsx
  packages/online-editor/src/workspace/services/FsCache.tsx
  packages/online-editor/src/workspace/services/GitService.tsx
  packages/online-editor/src/workspace/services/InMemoryBackend.ts
  packages/online-editor/src/workspace/services/StorageService.tsx
  packages/online-editor/src/workspace/services/WorkspaceDescriptorService.tsx
  packages/online-editor/src/workspace/services/WorkspaceFsService.tsx
  packages/online-editor/src/workspace/services/WorkspaceService.tsx
  packages/online-editor/src/workspace/services/index.d.ts
  patches/@isomorphic-git+lightning-fs+4.4.1.patch
  patches/@types+isomorphic-git__lightning-fs+4.4.2.patch
  yarn.lock
Labels: waiting-review

#807 Use `@kie-tools/jitexecutor-native`
  packages/extended-services/package.json
  packages/kie-sandbox-fs/tests/hotswap-backends-1.spec.js
  packages/kie-sandbox-fs/tests/hotswap-backends-2.spec.js
  yarn.lock
Labels: Tools

#812 Upgrading dependencies following `Dependabot` recommendations
  packages/cors-proxy-image/package.json
  packages/kie-sandbox-fs/package.json
  packages/online-editor/package.json
  patches/@isomorphic-git+cors-proxy+2.7.1.patch
  yarn.lock
Labels: Tools

#817 KOGITO-6673 - Wrong label in Advanced Data Properties Tab
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/resources/org/kie/workbench/common/stunner/bpmn/resources/i18n/StunnerBPMNConstants.properties
Labels: BPMN/Stunner

#818 KOGITO-4686: Cannot open DMN/BPMN files from command line with VS Code
  packages/vscode-extension/src/KogitoEditorChannelApiImpl.ts
Labels: Tools

#819 Improvements for update deployment + deploy daily version
  .github/actions/deploy-openshift/action.yml
  .github/workflows/publish_daily_dev_version.yml
  .github/workflows/release_build.yml
  .github/workflows/staging_build.yml
Labels: Tools

#811 Create new env var to customize KIE Sandbox's URL in IT tests
  packages/build-env/index.js
  packages/online-editor/it-tests/integration/DMNExpressionEditor.ts
  packages/online-editor/it-tests/integration/DMNGuidedTourTest.ts
  packages/online-editor/it-tests/integration/DMNRunnerTest.ts
  packages/online-editor/it-tests/integration/NewFileTest.ts
  packages/online-editor/it-tests/integration/OpenFromSourceTest.ts
  packages/online-editor/it-tests/integration/TrySampleTest.ts
  packages/online-editor/it-tests/integration/UploadFileTest.ts
  packages/online-editor/package.json
Labels: Tools
