Repository apache/incubator-kie-tools, pull requests merged in 2022-02, with the labels that each got.

#815 Upgrade more dependencies following `Dependabot` recommendations
  examples/base64png-editor-chrome-extension/webpack.config.js
  examples/webapp/webpack.config.js
  package.json
  packages/boxed-expression-component/showcase/webpack.config.js
  packages/build-env/graph.dot
  packages/chrome-extension-pack-kogito-kie-editors/webpack.config.js
  packages/dmn-dev-sandbox-form-webapp/webpack.config.js
  packages/feel-input-component/showcase/webpack.config.js
  packages/import-java-classes-component/showcase/webpack.config.js
  packages/kie-editors-standalone/it-tests/webpack.config.js
  packages/kie-editors-standalone/webpack.package-resources.config.js
  packages/online-editor/webpack.config.js
  packages/pmml-editor/dev-webapp/webpack.config.js
  packages/stunner-editors/errai-bom/pom.xml
  packages/unitables/package.json
  yarn.lock
Labels: Tools

#826 KOGITO-6693: JavaCodeCompletion configuration
  packages/vscode-extension-bpmn-editor/package.json
  packages/vscode-extension-dmn-editor/package.json
  packages/vscode-extension-pack-kogito-kie-editors/package.json
  packages/vscode-extension/src/KogitoEditorChannelApiImpl.ts
  packages/vscode-java-code-completion-extension-plugin/README.md
  packages/vscode-java-code-completion-extension-plugin/vscode-java-code-completion-extension-plugin-core/META-INF/MANIFEST.MF
  packages/vscode-java-code-completion-extension-plugin/vscode-java-code-completion-extension-plugin-core/src/main/java/org/kogito/core/internal/engine/ActivationChecker.java
Labels: DMN/SceSim, Tools

#827 Fix build commands on examples for Windows
  examples/base64png-editor-chrome-extension/package.json
  examples/base64png-editor-vscode-extension/package.json
  examples/base64png-editor/package.json
  examples/ping-pong-view-react/package.json
  examples/ping-pong-view/package.json
  examples/todo-list-view-vscode-extension/package.json
  examples/todo-list-view/package.json
  examples/webapp/package.json
Labels: Tools

#824 Upgrade even more dependencies following `Dependabot` alerts
  package.json
  packages/kie-sandbox-fs/karma.conf.js
  packages/kie-sandbox-fs/package.json
  packages/online-editor/package.json
  yarn.lock
Labels: Tools

#828 Mutually exclusive decision to run `CI` or `CI :: Full`
  .github/actions/deploy-openshift/action.yml
  .github/actions/merge-pr-changes/action.yml
  .github/workflows/monorepo_pr_ci.yml
  .github/workflows/monorepo_pr_ci_full.yml
Labels: Tools

#771 KOGITO-6449: [DMN Designer] Regression for setting name/dataType for BKM nodes, after KOGITO-4195
  packages/kie-editors-standalone/it-tests/cypress/integration/dmn-readonly.spec.ts
  packages/online-editor/it-tests/fixtures/testModelWithCustomDataType.dmn
  packages/online-editor/it-tests/integration/DMNExpressionEditor.ts
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionEditorViewImpl.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/SaveCurrentStateCommand.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/commands/ClearExpressionCommand.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/commands/FillContextExpressionCommand.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/commands/FillDecisionTableExpressionCommand.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/commands/FillExpressionCommand.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/commands/FillFunctionExpressionCommand.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/commands/FillInvocationExpressionCommand.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/commands/FillListExpressionCommand.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/commands/FillLiteralExpressionCommand.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/commands/FillRelationExpressionCommand.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/commands/UpdateCanvasNodeNameCommand.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/util/ExpressionState.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/util/HasNameUtils.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionEditorViewImplTest.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/SaveCurrentStateCommandTest.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/commands/ClearExpressionCommandTest.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/commands/FillContextExpressionCommandTest.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/commands/FillDecisionTableExpressionCommandTest.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/commands/FillExpressionCommandTest.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/commands/FillFunctionExpressionCommandTest.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/commands/FillInvocationExpressionCommandTest.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/commands/FillListExpressionCommandTest.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/commands/FillLiteralExpressionCommandTest.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/commands/FillRelationExpressionCommandTest.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/commands/UpdateCanvasNodeNameCommandTest.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/util/ExpressionStateTest.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/util/HasNameUtilsTest.java
Labels: DMN/SceSim

#829 Fix CI workflows
  .github/workflows/monorepo_pr_ci.yml
  .github/workflows/monorepo_pr_ci_full.yml
Labels: Tools

#814 KOGITO-6671: Render Question, Allowed Answers and Text Annotations on DMN Documentaion page
  packages/online-editor/it-tests/fixtures/testModelDocumentation.dmn
  packages/online-editor/it-tests/integration/DMNDocumentationTest.ts
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/documentation/common/DMNDocumentationDRD.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/documentation/common/DMNDocumentationDRDsFactory.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/documentation/common/DMNDocumentationI18n.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/documentation/template/dmn-documentation-template.html
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/resources/i18n/DMNEditorConstants.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/resources/org/kie/workbench/common/dmn/client/resources/i18n/DMNClientConstants.properties
Labels: DMN/SceSim

#822 KOGITO-6421: Unskip DMN New Expression editor tests
  packages/chrome-extension-pack-kogito-kie-editors/it-tests/tests/DmnExpressionEditorTest.ts
  packages/kie-editors-standalone/it-tests/cypress/integration/dmn-new-expression-editor.spec.ts
  packages/online-editor/it-tests/integration/DMNExpressionEditor.ts
Labels: DMN/SceSim

#810 Update MockitoJUnitRunner to non deprecated one
  packages/dashbuilder/kie-soup-dataset/kie-soup-dataset-core/src/test/java/org/dashbuilder/dataprovider/CustomProviderTest.java
  packages/dashbuilder/kie-soup-dataset/kie-soup-dataset-core/src/test/java/org/dashbuilder/dataset/DataSetDefDeployerTest.java
  packages/dashbuilder/kie-soup-dataset/kie-soup-dataset-core/src/test/java/org/dashbuilder/dataset/DataSetDefRegistryTest.java
  packages/dashbuilder/kie-soup-dataset/kie-soup-dataset-sql/src/test/java/org/dashbuilder/dataprovider/sql/JDBCUtilsTest.java
  packages/dashbuilder/kie-soup-dataset/kie-soup-dataset-sql/src/test/java/org/dashbuilder/dataprovider/sql/SQLDataSetMetadataTest.java
  packages/dashbuilder/kie-soup-dataset/kie-soup-dataset-sql/src/test/java/org/dashbuilder/dataprovider/sql/SQLInjectionAttacksTest.java
  packages/dashbuilder/kie-soup-dataset/kie-soup-dataset-sql/src/test/java/org/dashbuilder/dataprovider/sql/SelectStatementTest.java
  packages/stunner-editors/appformer-client-api/src/test/java/org/appformer/client/stateControl/registry/impl/DefaultRegistryImplTest.java
  packages/stunner-editors/appformer-kogito-bridge/src/test/java/org/appformer/kogito/bridge/client/guided/tour/GuidedTourBridgeTest.java
  packages/stunner-editors/appformer-kogito-bridge/src/test/java/org/appformer/kogito/bridge/client/guided/tour/GuidedTourObserverTest.java
  packages/stunner-editors/appformer-kogito-bridge/src/test/java/org/appformer/kogito/bridge/client/pmmleditor/marshaller/PMMLEditorMarshallerServiceProducerTest.java
  packages/stunner-editors/appformer-kogito-bridge/src/test/java/org/appformer/kogito/bridge/client/pmmleditor/marshaller/PMMLEditorMarshallerServiceTest.java
  packages/stunner-editors/appformer-kogito-bridge/src/test/java/org/appformer/kogito/bridge/client/stateControl/registry/impl/KogitoCommandRegistryTest.java
  packages/stunner-editors/appformer-kogito-bridge/src/test/java/org/appformer/kogito/bridge/client/stateControl/registry/producer/RegistryProducerTest.java
  packages/stunner-editors/drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/metadata/ScenarioHeaderMetaDataTest.java
  packages/stunner-editors/drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-runtime/src/test/java/org/drools/workbench/screens/scenariosimulation/webapp/client/services/ScenarioSimulationKogitoRuntimeResourceContentServiceTest.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/test/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/processes/DataTypeCacheTest.java
  packages/stunner-editors/uberfire-api/src/test/java/org/uberfire/backend/vfs/PathFactoryTest.java
  packages/stunner-editors/uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/src/test/java/org/uberfire/ext/editor/commons/client/file/exports/FileExportProducerTest.java
  packages/stunner-editors/uberfire-extensions/uberfire-layout-editor/uberfire-layout-editor-client/src/test/java/org/uberfire/ext/layout/editor/client/generator/LayoutGeneratorTest.java
  packages/stunner-editors/uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/test/java/org/uberfire/ext/widgets/common/client/dropdown/SingleLiveSearchSelectionHandlerTest.java
  packages/stunner-editors/uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/test/java/org/uberfire/ext/widgets/common/client/dropdown/footer/LiveSearchFooterTest.java
  packages/stunner-editors/uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/test/java/org/uberfire/ext/widgets/common/client/select/SelectComponentTest.java
  packages/stunner-editors/uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/test/java/org/uberfire/ext/widgets/common/client/select/SelectOptionComponentTest.java
  packages/stunner-editors/uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/util/LoggingTest.java
  packages/stunner-editors/uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/animation/GridWidgetEnterPinnedModeAnimationTest.java
  packages/stunner-editors/uberfire-extensions/uberfire-wires/uberfire-wires-core/uberfire-wires-core-grids/src/test/java/org/uberfire/ext/wires/core/grids/client/widget/grid/animation/GridWidgetExitPinnedModeAnimationTest.java
  packages/stunner-editors/uberfire-workbench/uberfire-workbench-client-views-patternfly/src/test/java/org/uberfire/client/views/pfly/widgets/InlineNotificationTest.java
  packages/stunner-editors/uberfire-workbench/uberfire-workbench-client-views-patternfly/src/test/java/org/uberfire/client/views/pfly/widgets/ModalTest.java
  packages/stunner-editors/uberfire-workbench/uberfire-workbench-client-views-patternfly/src/test/java/org/uberfire/client/views/pfly/widgets/SelectTest.java
Labels: Tools

#830 Fix baseUrl and remove unused imports
  packages/online-editor/it-tests/integration/DMNDocumentationTest.ts
  packages/online-editor/it-tests/integration/DMNExpressionEditor.ts
  packages/online-editor/it-tests/integration/DMNGuidedTourTest.ts
  packages/online-editor/it-tests/integration/DMNRunnerTest.ts
  packages/online-editor/it-tests/integration/NewFileTest.ts
  packages/online-editor/it-tests/integration/OpenFromSourceTest.ts
  packages/online-editor/it-tests/integration/TrySampleTest.ts
  packages/online-editor/it-tests/integration/UploadFileTest.ts
Labels: Tools

#834 Workflows: change daily run time
  .github/workflows/daily_cleanup.yml
  .github/workflows/publish_daily_dev_version.yml
  .github/workflows/release_dry_run.yml
  .github/workflows/staging_dry_run.yml
Labels: Tools

#832 Update Cypress version to 9.4.1
  package.json
  yarn.lock
Labels: Tools

#838 Update `@vscode/test-web` to `0.0.22`
  package.json
  yarn.lock
Labels: Tools

#833 KOGITO-6704: Fix long DMN data type constraint documentation
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/documentation/template/dmn-documentation-template.html
Labels: DMN/SceSim

#837 KOGITO-3660: Generate input/output columns, based on the type of the input nodes/the type decision node
  packages/boxed-expression-component/showcase/index.tsx
  packages/boxed-expression-component/src/api/BoxedExpressionEditor.ts
  packages/boxed-expression-component/src/api/BoxedExpressionEditorGWTService.ts
  packages/boxed-expression-component/src/components/LogicTypeSelector/LogicTypeSelector.tsx
  packages/stunner-editors-dmn-loader/src/index.tsx
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionEditorViewImpl.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/jsinterop/util/BoxedExpressionService.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/ExpressionType.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionEditorViewImplTest.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/types/ExpressionTypeTest.java
Labels: DMN/SceSim

#847 KOGITO-6745: Extend VS Code Channel API to enable support to custom implementations
  packages/vscode-extension/src/KogitoEditorChannelApiProducer.ts
  packages/vscode-extension/src/KogitoEditorFactory.ts
  packages/vscode-extension/src/index.ts
Labels: Tools

#808 KOGITO-6067 : Tasks in BPMN and specifically BR Node do not allow type to be Collection with a generic
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/property/diagram/AbstractDataTypeCache.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/test/java/org/kie/workbench/common/stunner/bpmn/definition/property/diagram/AbstractDataTypeCacheTest.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/dataproviders/VariablesProvider.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/artifacts/DataObjectTypeWidget.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/assignmentsEditor/ActivityDataIOEditorWidget.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/assignmentsEditor/AssignmentListItemWidgetViewImpl.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/assignmentsEditor/AssignmentsEditorWidget.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/i18n/StunnerFormsClientFieldsConstants.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/model/AssignmentData.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/multipleInstanceVariableEditor/MultipleInstanceVariableEditorView.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/variablesEditor/VariableListItemWidgetViewImpl.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/variablesEditor/VariablesEditorFieldRenderer.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/util/ListBoxValues.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/util/StringUtils.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/widgets/AbstractValidatingTextBox.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/widgets/AttributeValueTextBox.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/widgets/CustomDataTypeTextBox.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/widgets/VariableNameTextBox.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/resources/org/kie/workbench/common/stunner/bpmn/client/forms/fields/i18n/StunnerFormsClientFieldsConstants.properties
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/assignmentsEditor/AssignmentListItemWidgetTest.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/assignmentsEditor/AssignmentListItemWidgetViewImplTest.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/variablesEditor/VariableListItemWidgetTest.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/util/StringUtilsTest.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/widgets/CustomDataTypeTextBoxTest.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime/src/main/java/org/kie/workbench/common/stunner/kogito/client/services/DataTypeNamesStandaloneService.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/customproperties/elements/GlobalVariablesElement.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/fromstunner/properties/ActivityPropertyWriter.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/fromstunner/properties/ProcessPropertyWriter.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/fromstunner/properties/SubProcessPropertyWriter.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/processes/DataTypeCache.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/properties/ProcessVariableReader.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/test/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/customproperties/elements/GlobalVariablesElementTest.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/test/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/fromstunner/properties/ProcessPropertyWriterTest.java
Labels: BPMN/Stunner

#787 KOGITO-6589: [DMN Designer] Provide options to improve performance when opening DMN models without dmndi information
  packages/online-editor/it-tests/fixtures/testModelWithoutLayout.dmn
  packages/online-editor/it-tests/integration/UploadFileTest.ts
  packages/online-editor/it-tests/support/commands.ts
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/resources/i18n/DMNEditorConstants.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/resources/org/kie/workbench/common/dmn/client/resources/i18n/DMNClientConstants.properties
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/main/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/editor/AbstractDMNDiagramEditor.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-common/src/test/java/org/kie/workbench/common/dmn/webapp/kogito/common/client/editor/AbstractDMNDiagramEditorTest.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/src/main/java/org/kie/workbench/common/dmn/showcase/client/editor/DMNDiagramEditor.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/src/test/java/org/kie/workbench/common/dmn/showcase/client/large/model/DMNDesignerLargeAssetIT.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime/src/test/java/org/kie/workbench/common/dmn/showcase/client/selenium/locator/EditorXPathLocator.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-testing/src/main/java/org/kie/workbench/common/dmn/showcase/client/editor/DMNDiagramEditor.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/components/layout/LayoutHelper.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/components/layout/OpenDiagramLayoutExecutor.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/graph/processing/layout/AbstractLayoutService.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/i18n/CoreTranslationMessages.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/resources/org/kie/workbench/common/stunner/core/resources/i18n/StunnerCoreConstants.properties
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/test/java/org/kie/workbench/common/stunner/core/graph/processing/layout/AbstractLayoutServiceTest.java
Labels: DMN/SceSim

#835 KOGITO-6703: Render DMN Text Annotations in Documentation
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/documentation/common/DMNDocumentationDRD.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/documentation/common/DMNDocumentationDRDsFactory.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/documentation/template/dmn-documentation-template.html
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/documentation/common/DMNDocumentationDRDsFactoryTest.java
Labels: DMN/SceSim

#836 Skip GWT compiler in `lienzo-webapp` for yarn builds
  packages/stunner-editors/lienzo-webapp/pom.xml
Labels: BPMN/Stunner, DMN/SceSim, Tools

#855 KOGITO-6790: Stabilize UploadFileTest - should upload DMN file
  packages/online-editor/it-tests/integration/UploadFileTest.ts
Labels: DMN/SceSim

#859 Add SWF VS Code extension to `Jenkinsfile.vscode`
  .ci/jenkins/Jenkinsfile.vscode
Labels: Tools

#862 KOGITO-6796: Disable fetching schemas on Serverless Workflow Monaco editor.
  packages/serverless-workflow-editor/src/monaco/augmentation/language/json/index.ts
  packages/serverless-workflow-editor/src/monaco/augmentation/language/yaml/index.ts
Labels: Tools, SWF

#857 KOGITO-6402: Create test for DMN Boxed Expression Editor undo operation
  packages/boxed-expression-component/package.json
  packages/online-editor/it-tests/integration/DMNExpressionEditor.ts
  packages/online-editor/it-tests/support/index.ts
  packages/online-editor/it-tests/tsconfig.json
  packages/online-editor/package.json
  yarn.lock
Labels: DMN/SceSim, Tools

#794 KOGITO-6181 : Stunner-based editors are loosing focus when asked for the SVG
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/canvas/LienzoCanvas.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/components/toolbox/actions/AbstractActionsToolboxView.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/test/java/org/kie/workbench/common/stunner/client/lienzo/components/toolbox/actions/AbstractActionsToolboxViewTest.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/canvas/ScrollableLienzoPanel.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/presenters/session/impl/SessionEditorImpl.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/test/java/org/kie/workbench/common/stunner/client/widgets/canvas/ScrollableLienzoPanelTest.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/canvas/util/CanvasFileExport.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/test/java/org/kie/workbench/common/stunner/core/client/canvas/util/CanvasFileExportTest.java
  packages/stunner-editors/lienzo-core/src/main/java/com/ait/lienzo/client/widget/panel/impl/LienzoPanelScrollEvent.java
  packages/stunner-editors/lienzo-core/src/main/java/com/ait/lienzo/client/widget/panel/impl/ScrollablePanel.java
Labels: BPMN/Stunner

#864 KOGITO-6793: Fix EnvelopeMappings in "vscode_extension_kogito_kie_editors"
  packages/vscode-extension-pack-kogito-kie-editors/src/extension/extension.ts
Labels: Tools

#866 KOGITO-6506: Support transformation in External Data Sets
  packages/dashbuilder/dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-c3/src/main/java/org/dashbuilder/renderer/c3/client/C3DisplayerView.java
  packages/dashbuilder/dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-c3/src/main/java/org/dashbuilder/renderer/c3/client/C3Renderer.java
  packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-client/pom.xml
  packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-client/src/main/java/org/dashbuilder/client/RuntimeClientLoader.java
  packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-client/src/main/java/org/dashbuilder/client/RuntimeCommunication.java
  packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-client/src/main/java/org/dashbuilder/client/error/DefaultRuntimeErrorCallback.java
  packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-client/src/main/java/org/dashbuilder/client/external/ExternalDataSetClientProvider.java
  packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-client/src/main/java/org/dashbuilder/client/external/transformer/JSONAta.java
  packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-client/src/main/java/org/dashbuilder/client/external/transformer/JSONAtaTransformer.java
  packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-client/src/main/java/org/dashbuilder/client/external/transformer/resources/JSONAtaInjector.java
  packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-client/src/main/java/org/dashbuilder/client/external/transformer/resources/NativeLibraryResources.java
  packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-client/src/main/java/org/dashbuilder/client/navbar/AppNavBar.java
  packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-client/src/main/java/org/dashbuilder/client/resources/i18n/AppConstants.java
  packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-client/src/main/java/org/dashbuilder/client/screens/RouterScreen.java
  packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-client/src/main/java/org/dashbuilder/client/screens/RuntimeScreen.java
  packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-client/src/main/java/org/dashbuilder/client/services/RuntimeDataSetClientServices.java
  packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-client/src/main/resources/org/dashbuilder/client/resources/i18n/AppConstants.properties
  packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-client/src/test/java/org/dashbuilder/client/RuntimeClientLoaderTest.java
  packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-client/src/test/java/org/dashbuilder/client/screens/RouterScreenTest.java
  packages/dashbuilder/kie-soup-dataset/kie-soup-dataset-api/src/main/java/org/dashbuilder/dataset/def/ExternalDataSetDef.java
  packages/dashbuilder/kie-soup-dataset/kie-soup-dataset-api/src/main/java/org/dashbuilder/dataset/json/DataSetLookupJSONMarshaller.java
  packages/dashbuilder/kie-soup-dataset/kie-soup-dataset-api/src/main/java/org/dashbuilder/dataset/json/ExternalDefJSONMarshaller.java
  packages/dashbuilder/pom.xml
Labels: Tools

#850 KOGITO-6496: Remove unused/unnecessary dependencies with KIE V7 from `stunner-editors`
  packages/stunner-editors/drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-api/src/main/java/org/drools/workbench/screens/scenariosimulation/model/ScenarioSimulationModelContent.java
  packages/stunner-editors/drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/editor/ScenarioSimulationEditorPresenter.java
  packages/stunner-editors/drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/editor/strategies/AbstractDMNDataManagementStrategy.java
  packages/stunner-editors/drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/editor/strategies/DataManagementStrategy.java
  packages/stunner-editors/drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/editor/AbstractScenarioSimulationEditorTest.java
  packages/stunner-editors/drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/editor/ScenarioSimulationEditorPresenterTest.java
  packages/stunner-editors/drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/editor/strategies/AbstractDMNDataManagementStrategyTest.java
  packages/stunner-editors/drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/editor/strategies/AbstractDMODataManagementStrategyTest.java
  packages/stunner-editors/drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/editor/strategies/AbstractDataManagementStrategyTest.java
  packages/stunner-editors/drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-client/src/main/java/org/drools/workbench/screens/scenariosimulation/kogito/client/converters/ApiJSInteropConverter.java
  packages/stunner-editors/drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-client/src/main/java/org/drools/workbench/screens/scenariosimulation/kogito/client/converters/JSInteropApiConverter.java
  packages/stunner-editors/drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-client/src/main/java/org/drools/workbench/screens/scenariosimulation/kogito/client/editor/strategies/KogitoDMODataManagementStrategy.java
  packages/stunner-editors/drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-client/src/test/java/org/drools/workbench/screens/scenariosimulation/kogito/client/editor/strategies/KogitoDMODataManagementStrategyTest.java
  packages/stunner-editors/drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-runtime/pom.xml
  packages/stunner-editors/drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-testing/pom.xml
  packages/stunner-editors/kie-wb-common-widgets/kie-wb-common-ui/pom.xml
  packages/stunner-editors/kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/datamodel/AsyncPackageDataModelOracle.java
  packages/stunner-editors/kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/datamodel/AsyncPackageDataModelOracleFactory.java
  packages/stunner-editors/kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/datamodel/AsyncPackageDataModelOracleImpl.java
  packages/stunner-editors/kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/datamodel/AsyncPackageDataModelOracleUtilities.java
  packages/stunner-editors/kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/datamodel/CEPOracle.java
  packages/stunner-editors/kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/datamodel/DataModelHelper.java
  packages/stunner-editors/kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/datamodel/EnumDropDownDataFactory.java
  packages/stunner-editors/kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/datamodel/FactNameToFQCNHandleRegistry.java
  packages/stunner-editors/kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/datamodel/FilteredEnumLists.java
  packages/stunner-editors/kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/datamodel/ImportAddedEvent.java
  packages/stunner-editors/kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/datamodel/ImportRemovedEvent.java
  packages/stunner-editors/kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/datamodel/OracleUtils.java
  packages/stunner-editors/kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/datamodel/copied/IncrementalDataModelService.java
  packages/stunner-editors/kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/datamodel/copied/LazyModelField.java
  packages/stunner-editors/kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/datamodel/copied/PackageDataModelOracleIncrementalPayload.java
  packages/stunner-editors/kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/datamodel/copied/SortHelper.java
  packages/stunner-editors/kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/workitems/IBindingProvider.java
  packages/stunner-editors/kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/workitems/WorkItemBooleanParameterWidget.java
  packages/stunner-editors/kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/workitems/WorkItemBooleanParameterWidget.ui.xml
  packages/stunner-editors/kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/workitems/WorkItemEnumParameterWidget.java
  packages/stunner-editors/kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/workitems/WorkItemEnumParameterWidget.ui.xml
  packages/stunner-editors/kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/workitems/WorkItemFloatParameterWidget.java
  packages/stunner-editors/kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/workitems/WorkItemFloatParameterWidget.ui.xml
  packages/stunner-editors/kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/workitems/WorkItemIntegerParameterWidget.java
  packages/stunner-editors/kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/workitems/WorkItemIntegerParameterWidget.ui.xml
  packages/stunner-editors/kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/workitems/WorkItemListParameterWidget.java
  packages/stunner-editors/kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/workitems/WorkItemObjectParameterWidget.java
  packages/stunner-editors/kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/workitems/WorkItemObjectParameterWidget.ui.xml
  packages/stunner-editors/kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/workitems/WorkItemParameterWidget.java
  packages/stunner-editors/kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/workitems/WorkItemParameterWidgetFactory.java
  packages/stunner-editors/kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/workitems/WorkItemParametersWidget.java
  packages/stunner-editors/kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/workitems/WorkItemStringParameterWidget.java
  packages/stunner-editors/kie-wb-common-widgets/kie-wb-common-ui/src/main/java/org/kie/workbench/common/widgets/client/workitems/WorkItemStringParameterWidget.ui.xml
  packages/stunner-editors/kie-wb-common-widgets/kie-wb-common-ui/src/main/resources/org/kie/workbench/common/widgets/KieWorkbenchWidgetsCommon.gwt.xml
  packages/stunner-editors/pom.xml
Labels: BPMN/Stunner, DMN/SceSim

#871 KOGITO-6828: Monaco font is not configured properly on the Serverless Workflow Editor
  packages/serverless-workflow-editor/dev-webapp/webpack.config.js
  packages/vscode-extension-serverless-workflow-editor/webpack.config.js
Labels: Tools, SWF

#839 KOGITO-6540 : Stunner - Ability to set the priority of a task as a process variable in the BC BPMN editor
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/property/task/BaseUserTaskExecutionSet.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/property/task/TaskPriority.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/property/task/UserTaskExecutionSet.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/resources/org/kie/workbench/common/stunner/bpmn/resources/i18n/StunnerBPMNConstants.properties
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/test/java/org/kie/workbench/common/stunner/bpmn/definition/HashCodeAndEqualityTest.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/documentation/ClientBPMNDocumentationServiceTest.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/fromstunner/properties/UserTaskPropertyWriter.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/fromstunner/tasks/TaskConverter.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/tasks/TaskConverter.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/test/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/fromstunner/tasks/TaskConverterPriorityTest.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/test/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/tasks/TaskConverterPriorityTest.java
Labels: BPMN/Stunner

#868 KOGITO-6807: Implement undo, redo and isDirty on the Serverless Workflow Editor
  packages/serverless-workflow-editor/src/editor/ServerlessWorkflowEditor.tsx
  packages/serverless-workflow-editor/src/editor/ServerlessWorkflowEditorInterface.tsx
  packages/serverless-workflow-editor/src/monaco/MonacoEditor.tsx
  packages/serverless-workflow-editor/src/monaco/augmentation/MonacoEditorApi.ts
  packages/serverless-workflow-editor/src/monaco/augmentation/index.ts
  packages/vscode-extension-serverless-workflow-editor/src/extension/ServerlessWorkflowChannelApiImpl.ts
  packages/vscode-extension-serverless-workflow-editor/src/extension/ServerlessWorkflowChannelApiProducer.ts
  packages/vscode-extension-serverless-workflow-editor/src/extension/extension.ts
Labels: Tools, SWF

#854 KOGITO-6003: Serialize inputs of DMN Runner
  packages/online-editor/it-tests/integration/DMNRunnerTest.ts
  packages/online-editor/src/App.tsx
  packages/online-editor/src/dmnRunnerInputs/DmnRunnerInputsContext.tsx
  packages/online-editor/src/dmnRunnerInputs/DmnRunnerInputsContextProvider.tsx
  packages/online-editor/src/dmnRunnerInputs/DmnRunnerInputsHook.tsx
  packages/online-editor/src/dmnRunnerInputs/DmnRunnerInputsService.tsx
  packages/online-editor/src/editor/DeleteDropdownWithConfirmation.tsx
  packages/online-editor/src/editor/DmnDevSandbox/DmnDevSandboxContextProvider.tsx
  packages/online-editor/src/editor/DmnRunner/DmnRunnerContext.tsx
  packages/online-editor/src/editor/DmnRunner/DmnRunnerDrawerPanelContent.tsx
  packages/online-editor/src/editor/DmnRunner/DmnRunnerLoading.tsx
  packages/online-editor/src/editor/DmnRunner/DmnRunnerProvider.tsx
  packages/online-editor/src/editor/DmnRunner/DmnRunnerTabular.tsx
  packages/online-editor/src/editor/EditorPageDockDrawer.tsx
  packages/online-editor/src/editor/EditorToolbar.tsx
  packages/online-editor/src/editor/KieSandboxExtendedServices/KieSandboxExtendedServicesButtons.tsx
  packages/online-editor/src/home/HomePage.tsx
  packages/online-editor/src/reactExt/Hooks.ts
  packages/online-editor/src/workspace/WorkspacesContext.tsx
  packages/online-editor/src/workspace/WorkspacesContextProvider.tsx
  packages/online-editor/src/workspace/services/WorkspaceService.tsx
  packages/online-editor/static/resources/style.css
Labels: Tools
