Repository apache/incubator-kie-tools, pull requests merged in 2022-04, with the labels that each got.

#920 [swf-editor-dev-webapp] Fix missing channelType property in dev-webapp
  packages/serverless-workflow-editor/dev-webapp/App.tsx
Labels: SWF

#923 KOGITO-6956: Fix css selection to bring back 'See as diagram' button
  package.json
  packages/chrome-extension/src/app/Dependencies.ts
  yarn.lock
Labels: Tools

#916 KOGITO-6932: DMN editor: text annotation is not saved correctly when creating it by copy and paste
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/commands/clone/DMNDeepCloneProcess.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/commands/clone/DMNDeepCloneProcessTest.java
Labels: DMN/SceSim

#917 KOGITO-6928: Expression in Assignments that contains comma is saved with incorrect value when reopening a process
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/model/AssignmentData.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/model/AssignmentDataTest.java
Labels: BPMN/Stunner

#927 Serverless Workflow Editor dev webapp fix
  packages/serverless-workflow-editor/src/monaco/SwfMonacoEditor.tsx
Labels: SWF

#908 KOGITO-6417: [DMN Designer] Undo/redo in Boxed Expression Editor for editable cells is not working properly
  packages/boxed-expression-component/showcase/index.tsx
  packages/boxed-expression-component/src/@types/react-table.d.ts
  packages/boxed-expression-component/src/components/Table/EditableCell.tsx
  packages/boxed-expression-component/src/index.tsx
  packages/feel-input-component/src/FeelInput/FeelInput.tsx
Labels: waiting-for-qe, DMN/SceSim

#937 Reverted removed theme undefined check.
  packages/serverless-workflow-editor/src/monaco/SwfMonacoEditor.tsx
Labels: SWF

#942 KOGITO-6973: Fix gitignore for new serverless-workflow-diagram-editor streamline
  .gitignore
Labels: waiting-for-review, SWF

#922 KOGITO-6399: DMN Expression Editor - undo decision table annotation column
  packages/boxed-expression-component/src/components/Table/TableHeader.tsx
  packages/boxed-expression-component/tests/components/DecisionTableExpression/DecisionTableExpression.test.tsx
  packages/boxed-expression-component/tests/components/Table/Table.test.tsx
Labels: waiting-for-qe, DMN/SceSim

#940 RHPAM-4271: Update `minimist` to 1.2.6
  packages/dashbuilder/dashbuilder-shared/dashbuilder-js/packages/time-series-component/yarn.lock
  packages/dashbuilder/dashbuilder-shared/dashbuilder-js/yarn.lock
  yarn.lock
Labels: Tools, DashBuilder

#915 KOGITO-6915: [DMN Editor] add visual regression tests to cypress
  packages/boxed-expression-component/README.md
  packages/boxed-expression-component/it-tests/cypress/plugins/index.js
  packages/boxed-expression-component/it-tests/cypress/snapshots/context_expression_spec.ts/data_cell_focus.snap.png
  packages/boxed-expression-component/it-tests/cypress/snapshots/context_expression_spec.ts/header_cell_focus.snap.png
  packages/boxed-expression-component/it-tests/cypress/snapshots/decision_table_expression_spec.ts/input_header_cell_focus.snap.png
  packages/boxed-expression-component/it-tests/cypress/snapshots/decision_table_expression_spec.ts/output_header_cell_focus.snap.png
  packages/boxed-expression-component/it-tests/cypress/snapshots/invocation_expression_spec.ts/function_parameter_focus.snap.png
  packages/boxed-expression-component/it-tests/cypress/snapshots/list_expression_spec.ts/data_cell_focus.snap.png
  packages/boxed-expression-component/it-tests/cypress/snapshots/literal_expression_spec.ts/data_cell_focus.snap.png
  packages/boxed-expression-component/it-tests/cypress/snapshots/literal_expression_spec.ts/no_focus.snap.png
  packages/boxed-expression-component/it-tests/cypress/snapshots/relation_expression_spec.ts/data_cell_focus.snap.png
  packages/boxed-expression-component/it-tests/integration/context_expression_spec.ts
  packages/boxed-expression-component/it-tests/integration/decision_table_expression_spec.ts
  packages/boxed-expression-component/it-tests/integration/invocation_expression_spec.ts
  packages/boxed-expression-component/it-tests/integration/list_expression_spec.ts
  packages/boxed-expression-component/it-tests/integration/literal_expression_spec.ts
  packages/boxed-expression-component/it-tests/integration/relation_expression_spec.ts
  packages/boxed-expression-component/it-tests/support/commands.ts
  packages/boxed-expression-component/package.json
  yarn.lock
Labels: DMN/SceSim, Tools

#914 KOGITO-6859: [DMN Editor] Enabling Import Java Classes feature
  packages/import-java-classes-component/showcase/index.tsx
  packages/import-java-classes-component/src/__tests__/ImportJavaClasses/ImportJavaClasses.test.tsx
  packages/import-java-classes-component/src/__tests__/ImportJavaClasses/__snapshots__/ImportJavaClasses.test.tsx.snap
  packages/import-java-classes-component/src/api/ImportJavaClasses.ts
  packages/import-java-classes-component/src/components/ImportJavaClasses/ImportJavaClassesWizardFieldListTable.tsx
  packages/import-java-classes-component/src/components/ImportJavaClasses/ImportJavaClassesWizardFirstStep.tsx
  packages/import-java-classes-component/src/components/ImportJavaClasses/ImportJavaClassesWizardSecondStep.tsx
  packages/import-java-classes-component/src/components/ImportJavaClasses/model/DMNSimpleType.ts
  packages/import-java-classes-component/src/components/ImportJavaClasses/model/JavaClassUtils.ts
  packages/import-java-classes-component/src/components/ImportJavaClasses/services/JavaCodeCompletionService.ts
  packages/import-java-classes-component/src/i18n/locales/en.ts
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/DataTypesPage.java
  packages/vscode-java-code-completion-extension-plugin/pom.xml
  packages/vscode-java-code-completion-extension-plugin/vscode-java-code-completion-extension-plugin-core/pom.xml
  packages/vscode-java-code-completion-extension-plugin/vscode-java-code-completion-extension-plugin-core/src/main/java/org/kogito/core/internal/DelegateHandler.java
  packages/vscode-java-code-completion-extension-plugin/vscode-java-code-completion-extension-plugin-core/src/main/java/org/kogito/core/internal/ExtensionActivator.java
  packages/vscode-java-code-completion-extension-plugin/vscode-java-code-completion-extension-plugin-core/src/main/java/org/kogito/core/internal/engine/ActivationChecker.java
  packages/vscode-java-code-completion-extension-plugin/vscode-java-code-completion-extension-plugin-core/src/main/java/org/kogito/core/internal/engine/JavaEngine.java
  packages/vscode-java-code-completion-extension-plugin/vscode-java-code-completion-extension-plugin-core/src/main/java/org/kogito/core/internal/handlers/GetAccessorsHandler.java
  packages/vscode-java-code-completion-extension-plugin/vscode-java-code-completion-extension-plugin-core/src/main/java/org/kogito/core/internal/handlers/GetClassesHandler.java
  packages/vscode-java-code-completion-extension-plugin/vscode-java-code-completion-extension-plugin-core/src/main/java/org/kogito/core/internal/handlers/Handler.java
  packages/vscode-java-code-completion-extension-plugin/vscode-java-code-completion-extension-plugin-core/src/main/java/org/kogito/core/internal/handlers/IsLanguageServerAvailableHandler.java
  packages/vscode-java-code-completion-extension-plugin/vscode-java-code-completion-extension-plugin-core/src/test/java/org/kogito/core/internal/handlers/GetAccessorsHandlerTest.java
  packages/vscode-java-code-completion/src/api/JavaCodeCompletionAccessor.ts
  packages/vscode-java-code-completion/src/api/JavaCodeCompletionClass.ts
Labels: waiting-for-qe, DMN/SceSim, Tools

#945 Bump `org.kie` to `8.20.0.Beta`
  packages/serverless-workflow-diagram-editor/pom.xml
  packages/stunner-editors/pom.xml
Labels: Tools

#938 KOGITO-6972: Add zoom control buttons to the mermaid generated SVG
  packages/serverless-workflow-editor/src/editor/ServerlessWorkflowEditor.tsx
  packages/serverless-workflow-editor/static/css/editor.css
Labels: SWF

#951 KOGITO-6978: Update insecure dependencies
  packages/dashbuilder/appformer/pom.xml
  packages/serverless-workflow-diagram-editor/errai-bom/pom.xml
  packages/serverless-workflow-diagram-editor/pom.xml
  packages/serverless-workflow-editor/package.json
  packages/stunner-editors/pom.xml
  yarn.lock
Labels: Tools

#929 KOGITO-6918: [DMN Editor] interaction with name and data type popover with keyboard
  packages/boxed-expression-component/it-tests/integration/context_expression_spec.ts
  packages/boxed-expression-component/it-tests/integration/popover.spec.ts
  packages/boxed-expression-component/src/components/EditExpressionMenu/DataTypeSelector.tsx
  packages/boxed-expression-component/src/components/EditExpressionMenu/EditExpressionMenu.tsx
  packages/boxed-expression-component/src/components/PopoverMenu/PopoverMenu.tsx
  packages/boxed-expression-component/src/components/Table/Table.tsx
  packages/boxed-expression-component/src/components/common/NavigationKeysUtils.ts
  packages/boxed-expression-component/src/components/common/index.ts
  packages/boxed-expression-component/tests/components/Table/common/NavigationKeysUtils.test.ts
Labels: waiting-for-qe, DMN/SceSim

#952 Bump `maven-jaxb2-plugin` version to `0.15.1`
  packages/serverless-workflow-diagram-editor/pom.xml
  packages/stunner-editors/pom.xml
Labels: DO NOT MERGE, dependencies, java

#957 KOGITO-7070: Check Dashbuilder security alerts on kie-tools repository
  packages/dashbuilder/appformer/pom.xml
  packages/dashbuilder/appformer/uberfire-extensions/uberfire-widgets/uberfire-widgets-service/uberfire-widgets-service-backend/pom.xml
  packages/dashbuilder/pom.xml
Labels: DashBuilder

#958 Dependabot alert #165 and #166: Upgrade async package
  yarn.lock
Labels: Tools

#955 Make InsecureSkipVerify default to false
  packages/extended-services/pkg/config/config.go
  packages/extended-services/pkg/config/config.yaml
  packages/extended-services/pkg/kogito/constants.go
  packages/extended-services/pkg/kogito/server.go
  packages/extended-services/pkg/kogito/systray.go
Labels: Tools

#928 KOGITO-6787: Serverless Workflow validation
  packages/build-env/graph.dot
  packages/notifications/src/api/Notification.ts
  packages/notifications/src/vscode/ProblemsTabNotificationHandler.ts
  packages/serverless-workflow-editor/src/editor/ServerlessWorkflowEditor.tsx
  packages/serverless-workflow-editor/src/monaco/SwfMonacoEditor.tsx
  packages/serverless-workflow-editor/src/monaco/SwfMonacoEditorApi.ts
  packages/serverless-workflow-editor/src/monaco/augmentation/language/json/index.ts
  packages/serverless-workflow-editor/src/monaco/augmentation/language/schemas/common.ts
  packages/serverless-workflow-editor/src/monaco/augmentation/language/schemas/events.ts
  packages/serverless-workflow-editor/src/monaco/augmentation/language/schemas/functions.ts
  packages/serverless-workflow-editor/src/monaco/augmentation/language/schemas/index.ts
  packages/serverless-workflow-editor/src/monaco/augmentation/language/schemas/retries.ts
  packages/serverless-workflow-editor/src/monaco/augmentation/language/schemas/workflow.ts
  packages/serverless-workflow-editor/src/monaco/augmentation/language/yaml/index.ts
  packages/unitables-dmn/package.json
Labels: waiting-for-review, SWF
