Repository apache/incubator-kie-tools, pull requests merged in 2023-05, with the labels that each got.

#1598 [0.28.0-prerelease] NO-ISSUE: Replace "-" by "_" in serverless_workflow_vscode_extension vsix file name
  packages/serverless-workflow-vscode-extension/package.json
Labels: waiting-for-review, waiting-for-ci

#1594 [0.26.2] KOGITO-8959: Take screenshots of failed VSCode extension integration tests
  packages/vscode-extension-pack-kogito-kie-editors/it-tests/extension-editors-bpmn.test.ts
  packages/vscode-extension-pack-kogito-kie-editors/it-tests/extension-editors-dmn.test.ts
  packages/vscode-extension-pack-kogito-kie-editors/it-tests/extension-editors-scesim.test.ts
  packages/vscode-extension-pack-kogito-kie-editors/it-tests/extension-editors-smoke.test.ts
  packages/vscode-extension-pack-kogito-kie-editors/it-tests/helpers/VSCodeTestHelper.ts
  packages/vscode-extension-pack-kogito-kie-editors/package.json
  packages/vscode-extension-serverless-workflow-editor/it-tests/helpers/VSCodeTestHelper.ts
  packages/vscode-extension-serverless-workflow-editor/it-tests/serverless-workflow-editor-extension-autocompletion.test.ts
  packages/vscode-extension-serverless-workflow-editor/it-tests/serverless-workflow-editor-extension-smoke.test.ts
  packages/vscode-extension-serverless-workflow-editor/it-tests/serverless-workflow-editor-extension-syntax-highlight.test.ts
  packages/vscode-extension-serverless-workflow-editor/package.json
  packages/vscode-extension-yard-editor/it-tests/helpers/VSCodeTestHelper.ts
  packages/vscode-extension-yard-editor/it-tests/yard-editor.test.ts
  packages/vscode-extension-yard-editor/package.json
  pnpm-lock.yaml
Labels: Foundation, cherry-pick 🍒

#1593 NO-ISSUE: Bump `vcse` to `2.19.0`
  examples/base64png-editor-vscode-extension/package.json
  examples/todo-list-view-vscode-extension/package.json
  packages/bpmn-vscode-extension/package.json
  packages/dmn-vscode-extension/package.json
  packages/kie-editors-dev-vscode-extension/package.json
  packages/pmml-vscode-extension/package.json
  packages/serverless-workflow-vscode-extension/package.json
  packages/vscode-extension-dashbuilder-editor/package.json
  packages/vscode-extension-kie-ba-bundle/package.json
  packages/vscode-extension-kogito-bundle/package.json
  packages/vscode-extension-serverless-workflow-editor/package.json
  packages/yard-vscode-extension/package.json
  pnpm-lock.yaml
Labels: Foundation

#1602 KOGITO-9093: Update Cypress version to 12.11.0
  packages/boxed-expression-component/package.json
  packages/kie-editors-standalone/package.json
  packages/online-editor/package.json
  packages/pmml-editor/package.json
  packages/serverless-logic-web-tools/package.json
  pnpm-lock.yaml
Labels: waiting-for-ci

#1608 NO-ISSUE: Replace deprecated `vsce` in favor of `@vscode/vsce` on `Jenkinsfile`
  .ci/jenkins/Jenkinsfile.vscode
Labels: Foundation

#1600 KOGITO-8986: SWF Viewer - missing icon for parameters for Switch state
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/resources/i18n/SWConstants.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/resources/org/kie/workbench/common/stunner/sw/resources/i18n/SWConstants.properties
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-client/src/main/java/org/kie/workbench/common/stunner/sw/client/shapes/HasConditionsAndHasDataFilter.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-client/src/main/java/org/kie/workbench/common/stunner/sw/client/shapes/SwitchStateShape.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-client/src/main/java/org/kie/workbench/common/stunner/sw/client/shapes/icons/IconPath.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-client/src/test/java/org/kie/workbench/common/stunner/sw/client/shapes/HasConditionsAndHasDataFilterTest.java
Labels: waiting-for-ci, Serverless Workflow, java

#1596 NO-ISSUE: 0.28.0 CHANGELOGs
  packages/bpmn-vscode-extension/CHANGELOG.md
  packages/dmn-vscode-extension/CHANGELOG.md
  packages/pmml-vscode-extension/CHANGELOG.md
  packages/serverless-workflow-vscode-extension/CHANGELOG.md
  packages/vscode-extension-dashbuilder-editor/CHANGELOG.md
  packages/vscode-extension-kie-ba-bundle/CHANGELOG.md
  packages/vscode-extension-kogito-bundle/CHANGELOG.md
  packages/vscode-extension-serverless-workflow-editor/CHANGELOG.md
Labels: Foundation

#1609 KOGITO-9105: Add KIE prefix to `displayName` of new VS Code extensions
  packages/bpmn-vscode-extension/package.json
  packages/dmn-vscode-extension/package.json
  packages/pmml-vscode-extension/package.json
  packages/serverless-workflow-vscode-extension/package.json
Labels: Foundation

#1610 NO-ISSUE: 0.28.1 CHANGELOGs
  packages/bpmn-vscode-extension/CHANGELOG.md
  packages/dmn-vscode-extension/CHANGELOG.md
  packages/pmml-vscode-extension/CHANGELOG.md
  packages/serverless-workflow-vscode-extension/CHANGELOG.md
  packages/vscode-extension-kie-ba-bundle/CHANGELOG.md
  packages/vscode-extension-kogito-bundle/CHANGELOG.md
Labels: Foundation

#1601 kie-issues#113: Remove unnecessary rendering calls to DMN Editor's Boxed Expression Editor
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionEditorViewImpl.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/SaveCurrentStateCommand.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/util/ExpressionState.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionEditorViewImplTest.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/SaveCurrentStateCommandTest.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/util/ExpressionStateTest.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-extensions/kie-wb-common-stunner-kogito/kie-wb-common-stunner-kogito-client/src/main/java/org/kie/workbench/common/stunner/kogito/client/session/command/impl/KogitoKeyEventHandlerImpl.java
Labels: DMN/SceSim, java

#1606 KOGITO-8890: Refactor workspace files listing according to UX redesign
  packages/serverless-logic-web-tools/src/AppConstants.ts
  packages/serverless-logic-web-tools/src/editor/EditorToolbar.tsx
  packages/serverless-logic-web-tools/src/homepage/overView/Overview.tsx
  packages/serverless-logic-web-tools/src/homepage/pageTemplate/OnlineEditorPage.tsx
  packages/serverless-logic-web-tools/src/homepage/recentModels/ConfirmDeleteModal.tsx
  packages/serverless-logic-web-tools/src/homepage/recentModels/RecentModels.tsx
  packages/serverless-logic-web-tools/src/homepage/recentModels/WorkspacesTable.tsx
  packages/serverless-logic-web-tools/src/homepage/recentModels/WorkspacesTableRow.tsx
  packages/serverless-logic-web-tools/src/homepage/recentModels/workspaceFiles/WorkspaceFiles.tsx
  packages/serverless-logic-web-tools/src/homepage/recentModels/workspaceFiles/WorkspaceFilesTable.tsx
  packages/serverless-logic-web-tools/src/homepage/recentModels/workspaceFiles/WorkspaceFilesTableRow.tsx
  packages/serverless-logic-web-tools/src/homepage/routes/HomePageRoutes.tsx
  packages/serverless-logic-web-tools/src/homepage/uiNav/HomePageNav.tsx
  packages/serverless-logic-web-tools/src/navigation/Routes.ts
  packages/serverless-logic-web-tools/src/table/ConfirmDeleteModal.tsx
  packages/serverless-logic-web-tools/src/table/TablePagination.tsx
  packages/serverless-logic-web-tools/src/table/TableToolbar.tsx
  packages/serverless-logic-web-tools/static/resources/style.css
Labels: waiting-for-ci, Serverless Workflow, DashBuilder

#1549 SWF Editor - Issues on state selection & tooltip overlapping toolbox
  packages/serverless-workflow-diagram-editor/lienzo-core/src/main/java/com/ait/lienzo/client/core/shape/toolbox/items/tooltip/PrimitiveTextTooltip.java
  packages/serverless-workflow-diagram-editor/lienzo-core/src/main/java/com/ait/lienzo/client/core/shape/wires/WiresManager.java
  packages/serverless-workflow-diagram-editor/lienzo-tests/src/test/java/com/ait/lienzo/client/core/shape/toolbox/items/tooltip/PrimitiveTextTooltipTest.java
  packages/serverless-workflow-diagram-editor/lienzo-tests/src/test/java/com/ait/lienzo/client/core/shape/wires/WiresShapeTest.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-client/src/main/java/org/kie/workbench/common/stunner/sw/client/shapes/ServerlessWorkflowShapeView.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-client/src/main/java/org/kie/workbench/common/stunner/sw/client/shapes/StateShapeView.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-client/src/main/java/org/kie/workbench/common/stunner/sw/client/shapes/icons/BottomDepiction.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-client/src/main/java/org/kie/workbench/common/stunner/sw/client/shapes/icons/BottomText.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-client/src/main/java/org/kie/workbench/common/stunner/sw/client/shapes/icons/CornerIcon.java
Labels: Serverless Workflow

#1613 KOGITO-9108: Rename the new Serverless Workflow VS Code extension to `swf-vscode-extension`
  .github/workflows/release_build.yml
  packages/serverless-workflow-vscode-extension/package.json
  packages/serverless-workflow-vscode-extension/src/extension/extension.ts
  packages/vscode-extension-kogito-bundle/package.json
  packages/vscode-extension-serverless-workflow-editor/README.md
  packages/vscode-extension-serverless-workflow-editor/src/extension/setupDeprecationNotification.ts
  repo/graph.dot
  repo/graph.json
Labels: Foundation

#1615 NO-ISSUE: 0.28.2 CHANGELOGs
  packages/serverless-workflow-vscode-extension/CHANGELOG.md
  packages/vscode-extension-kogito-bundle/CHANGELOG.md
  packages/vscode-extension-serverless-workflow-editor/CHANGELOG.md
Labels: waiting-for-ci, Foundation

#1619 NO-ISSUE: Update release process
  RELEASE_PROCESS.md
Labels: Foundation

#1604 kie-issues#90: The option to embed a Gist is always available in a Gist Workspace on KIE Sandbox
  packages/online-editor/src/editor/Toolbar/EditorToolbar.tsx
  packages/online-editor/src/editor/Toolbar/EditorToolbarContextProvider.tsx
  packages/online-editor/src/editor/Toolbar/Share/EmbedModal.tsx
  packages/online-editor/src/i18n/OnlineI18n.ts
  packages/online-editor/src/i18n/locales/en.ts
Labels: Foundation

#1623 Remove circular symlinks but keep --env live functionality
  packages/uniforms-patternfly/src/cjs
  packages/uniforms-patternfly/src/esm
  packages/webpack-base/multi-package-live-reload-loader.js
Labels: Foundation

#1626 kie-issues#114: Update JDT.LS to `1.23.0.20230427142853` version
  packages/vscode-java-code-completion-extension-plugin/pom.xml
Labels: DMN/SceSim

#1627 kie-issues#253: DMN Runner is not supporting nested List DataTypes
  packages/online-editor/src/__tests__/jsonSchema/dereference.test.ts
  packages/online-editor/src/jsonSchema/dereference.ts
Labels: waiting-for-review, Foundation

#1631 kie-issues#255: A Not-collect Hit Policy should clear aggregation type
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/jsinterop/util/ExpressionModelFiller.java
Labels: DMN/SceSim

#1625 kie-issues#250: Width changes are not correctly persisted
  packages/boxed-expression-component/src/resizing/WidthConstants.ts
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/ExpressionEditorViewImpl.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/jsinterop/util/ExpressionModelFiller.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/context/ContextGrid.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/dtable/DecisionTableGrid.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/invocation/InvocationGrid.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/list/ListGrid.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/literal/LiteralExpressionGrid.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/types/relation/RelationGrid.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/jsinterop/util/ExpressionModelFillerTest.java
Labels: DMN/SceSim, java

#1635 KOGITO-8153: Create an extensible Samples page (now Catalog)
  packages/serverless-logic-web-tools/src/home/sample/SampleCard.tsx
  packages/serverless-logic-web-tools/src/home/sample/SampleCardSkeleton.css
  packages/serverless-logic-web-tools/src/home/sample/Showcase.tsx
  packages/serverless-logic-web-tools/src/home/sample/hooks/SampleContext.tsx
  packages/serverless-logic-web-tools/src/home/sample/sampleApi.ts
Labels: waiting-for-review, Serverless Workflow, DashBuilder

#1614 KOGITO-8988: SWF Viewer - add icons for ForEch state
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/definition/ForEachState.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/definition/ParallelState.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/definition/custom/NumCompletedJsonTypeSerializer.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/definition/custom/json/BatchSizeJsonTypeSerializer.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/definition/custom/json/NumCompletedJsonTypeSerializer.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/definition/custom/yaml/StringNumberYamlTypeSerializer.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/resources/i18n/SWConstants.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/resources/org/kie/workbench/common/stunner/sw/resources/i18n/SWConstants.properties
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-client/src/main/java/org/kie/workbench/common/stunner/sw/client/shapes/ForEachStateShape.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-client/src/main/java/org/kie/workbench/common/stunner/sw/client/shapes/HasCollections.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-client/src/main/java/org/kie/workbench/common/stunner/sw/client/shapes/HasConditionsAndHasDataFilter.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-client/src/main/java/org/kie/workbench/common/stunner/sw/client/shapes/HasDataFilter.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-client/src/main/java/org/kie/workbench/common/stunner/sw/client/shapes/HasEventAndDataFilter.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-client/src/main/java/org/kie/workbench/common/stunner/sw/client/shapes/icons/IconPath.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-client/src/main/java/org/kie/workbench/common/stunner/sw/client/shapes/icons/IconPosition.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-client/src/test/java/org/kie/workbench/common/stunner/sw/client/shapes/HasCollectionsTest.java
Labels: Serverless Workflow, java

#1638 kie-issues#258: Use data type current value when opening DMN constraint modal
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/listview/constraint/DataTypeConstraintModal.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/types/listview/constraint/DataTypeConstraintModalView.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/types/listview/constraint/DataTypeConstraintModalViewTest.java
Labels: waiting-for-review, DMN/SceSim

#1634 kie-issues#222: When editing a BeeTable cell with selected text, the selection is lost when mouse hovers in or out of it
  packages/boxed-expression-component/src/table/BeeTable/BeeTableTd.tsx
  packages/boxed-expression-component/src/table/BeeTable/BeeTableThResizable.tsx
Labels: Foundation

#1632 kie-issue#210: Keyboard shortcuts stop working after blurring out of some components on the BeeTable
  packages/boxed-expression-component/src/selection/BeeTableSelectionContext.tsx
  packages/stunner-editors-dmn-loader/src/index.tsx
Labels: DMN/SceSim, Foundation

#1639 NO-ISSUE: Ignoring failing GraphUtilsTest
  packages/serverless-workflow-diagram-editor/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/test/java/org/kie/workbench/common/stunner/core/graph/util/GraphUtilsTest.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/test/java/org/kie/workbench/common/stunner/core/graph/util/GraphUtilsTest.java
Labels: java

#1648 KOGITO-8972: Refactor UX Minor fixes
  packages/serverless-logic-web-tools/src/PageTitle.tsx
  packages/serverless-logic-web-tools/src/editor/EditorPage.tsx
  packages/serverless-logic-web-tools/src/editor/NewFileDropdownMenu.tsx
  packages/serverless-logic-web-tools/src/home/sample/SamplesCatalog.tsx
  packages/serverless-logic-web-tools/src/home/sample/sampleApi.ts
  packages/serverless-logic-web-tools/src/homepage/overView/ImportFromUrlCard.tsx
  packages/serverless-logic-web-tools/src/homepage/overView/NewModelCard.tsx
  packages/serverless-logic-web-tools/src/homepage/overView/NewServerlessModelCard.tsx
  packages/serverless-logic-web-tools/src/homepage/overView/Overview.tsx
  packages/serverless-logic-web-tools/src/homepage/recentModels/RecentModels.tsx
  packages/serverless-logic-web-tools/src/homepage/recentModels/workspaceFiles/WorkspaceFiles.tsx
  packages/serverless-logic-web-tools/src/homepage/routes/HomePageRoutes.tsx
  packages/serverless-logic-web-tools/src/kieSandboxExtendedServices/KieSandboxExtendedServicesModal.tsx
  packages/serverless-logic-web-tools/src/navigation/Routes.ts
  packages/serverless-logic-web-tools/src/openshift/dropdown/OpenshiftDeploymentsDropdown.tsx
  packages/serverless-logic-web-tools/src/quickstarts-data/ApplicationServicesIntegrationQuickStart.ts
  packages/serverless-logic-web-tools/src/settings/SettingsContext.tsx
  packages/serverless-logic-web-tools/src/settings/extendedServices/KieSandboxExtendedServicesSettings.tsx
  packages/serverless-logic-web-tools/src/settings/featurePreview/FeaturePreviewSettings.tsx
  packages/serverless-logic-web-tools/src/settings/github/GitHubSettings.tsx
  packages/serverless-logic-web-tools/src/settings/openshift/OpenShiftSettings.tsx
  packages/serverless-logic-web-tools/src/settings/serviceAccount/ServiceAccountSettings.tsx
  packages/serverless-logic-web-tools/src/settings/serviceRegistry/ServiceRegistrySettings.tsx
  packages/serverless-logic-web-tools/src/workspace/components/ImportFromUrlForm.tsx
Labels: waiting-for-ci, Serverless Workflow, DashBuilder

#1649 NO-ISSUE: Add 'patches' dir to the Sparse Checkout script
  scripts/sparse-checkout/run.sh
Labels: Foundation

#1651 KOGITO-9175: Support types for Dashbuilder external datasets
  packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-client/src/main/java/org/dashbuilder/client/external/ExternalDataSetClientProvider.java
  packages/dashbuilder/kie-soup-dataset/kie-soup-dataset-api/src/main/java/org/dashbuilder/dataset/def/ExternalDataSetDef.java
  packages/dashbuilder/kie-soup-dataset/kie-soup-dataset-api/src/main/java/org/dashbuilder/dataset/def/ExternalServiceType.java
  packages/dashbuilder/kie-soup-dataset/kie-soup-dataset-api/src/main/java/org/dashbuilder/dataset/json/ExternalDefJSONMarshaller.java
Labels: DashBuilder

#1654 KOGITO-9186: Handle NaN values in Dashbuilder metrics dataset
  packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-client/src/main/java/org/dashbuilder/client/external/metrics/MetricsParser.java
  packages/dashbuilder/dashbuilder-runtime-parent/dashbuilder-runtime-client/src/test/java/org/dashbuilder/client/external/metrics/MetricsParserTest.java
Labels: waiting-for-ci, DashBuilder

#1628 kie-issues#245: Create a Docker Compose file to run KIE Sandbox and its related services
  packages/kie-sandbox-distribution/README.md
  packages/kie-sandbox-distribution/docker-compose.yaml
  packages/kie-sandbox-distribution/env/index.js
  packages/kie-sandbox-distribution/package.json
  pnpm-lock.yaml
  repo/graph.dot
  repo/graph.json
  scripts/build-env/src/bin.ts
Labels: Foundation

#1589 KOGITO-7066: SWF - Expose Stunner API through multiplying architecture
  packages/serverless-workflow-combined-editor/src/editor/ServerlessWorkflowCombinedEditor.tsx
  packages/serverless-workflow-diagram-editor-envelope/src/api/ServerlessWorkflowDiagramEditorEnvelopeApi.ts
  packages/serverless-workflow-diagram-editor-envelope/src/api/StunnerAPI.ts
  packages/serverless-workflow-diagram-editor-envelope/src/api/StunnerEditorEnvelopeAPI.ts
  packages/serverless-workflow-diagram-editor-envelope/src/api/StunnerEditorEnvelopeAPIFactory.ts
  packages/serverless-workflow-diagram-editor-envelope/src/api/SwfStunnerEditorAPI.ts
  packages/serverless-workflow-diagram-editor-envelope/src/envelope/ServerlessWorkflowDiagramEditor.ts
  packages/serverless-workflow-diagram-editor-envelope/src/envelope/ServerlessWorkflowDiagramEditorEnvelopeApiImpl.ts
  packages/serverless-workflow-diagram-editor-envelope/src/envelope/ServerlessWorkflowStunnerEditor.ts
  packages/serverless-workflow-diagram-editor/kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/canvas/controls/ControlPointControlImpl.java
  packages/serverless-workflow-diagram-editor/kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-widgets/src/main/java/org/kie/workbench/common/stunner/client/widgets/editor/StunnerEditor.java
  packages/serverless-workflow-diagram-editor/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-core-api/src/main/java/org/kie/workbench/common/stunner/core/graph/content/Bound.java
  packages/serverless-workflow-diagram-editor/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-core-api/src/main/java/org/kie/workbench/common/stunner/core/graph/content/Bounds.java
  packages/serverless-workflow-diagram-editor/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-core-api/src/main/java/org/kie/workbench/common/stunner/core/graph/content/view/ControlPoint.java
  packages/serverless-workflow-diagram-editor/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-core-api/src/main/java/org/kie/workbench/common/stunner/core/graph/content/view/Point2D.java
  packages/serverless-workflow-diagram-editor/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/api/JsStunnerEditor.java
  packages/serverless-workflow-diagram-editor/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/api/JsStunnerSession.java
  packages/serverless-workflow-diagram-editor/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-client-common/src/main/java/org/kie/workbench/common/stunner/core/client/api/JsWindow.java
  packages/serverless-workflow-diagram-editor/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/graph/content/view/MagnetConnection.java
  packages/serverless-workflow-diagram-editor/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/graph/content/view/Point2DConnection.java
  packages/serverless-workflow-diagram-editor/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/graph/content/view/ViewConnectorImpl.java
  packages/serverless-workflow-diagram-editor/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/graph/content/view/ViewImpl.java
  packages/serverless-workflow-diagram-editor/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/main/java/org/kie/workbench/common/stunner/core/graph/impl/NodeImpl.java
  packages/serverless-workflow-diagram-editor/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-commons/kie-wb-common-stunner-core-common/src/test/java/org/kie/workbench/common/stunner/core/graph/command/impl/AbstractControlPointCommandTest.java
  packages/serverless-workflow-diagram-editor/lienzo-core/src/main/java/com/ait/lienzo/client/core/types/JsCanvas.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-kogito-app/src/main/java/org/kie/workbench/common/stunner/sw/client/editor/DiagramEditor.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-kogito-app/src/test/java/org/kie/workbench/common/stunner/sw/client/editor/DiagramEditorTest.java
Labels: Serverless Workflow

#1655 KOGITO-9165: Bump `vscode-extension-tester` version to 5.6.0
  packages/kie-editors-dev-vscode-extension/package.json
  packages/serverless-workflow-vscode-extension/package.json
  packages/vscode-extension-common-test-helpers/package.json
  packages/vscode-extension-dashbuilder-editor/package.json
  packages/yard-vscode-extension/package.json
  pnpm-lock.yaml
Labels: Foundation

#1656 KOGITO-8966: Ability to completely erase stored data on browser
  packages/serverless-logic-web-tools/src/cookies/index.ts
  packages/serverless-logic-web-tools/src/home/sample/SamplesCatalog.tsx
  packages/serverless-logic-web-tools/src/homepage/pageTemplate/OnlineEditorPage.tsx
  packages/serverless-logic-web-tools/src/navigation/Routes.ts
  packages/serverless-logic-web-tools/src/settings/routes/SettingsPageRoutes.tsx
  packages/serverless-logic-web-tools/src/settings/storage/StorageSettings.tsx
  packages/serverless-logic-web-tools/src/settings/uiNav/SettingsPageNav.tsx
  packages/serverless-logic-web-tools/src/workspace/startupBlockers/SupportedBrowsers.ts
Labels: waiting-for-ci, Serverless Workflow, DashBuilder

#1659 NO-ISSUE: Bump `moment` dependencies version
  packages/stunner-editors/pom.xml
Labels: BPMN/Stunner, DMN/SceSim, Foundation, dependencies, java

#1661 KOGITO-8475: Adapt existing integration tests with new UI
  packages/serverless-logic-web-tools/it-tests/e2e/CreateNewFile.cy.ts
  packages/serverless-logic-web-tools/it-tests/e2e/RecentModel.cy.ts
  packages/serverless-logic-web-tools/it-tests/support/commands.ts
  packages/serverless-logic-web-tools/it-tests/support/e2e.ts
  packages/serverless-logic-web-tools/package.json
  packages/serverless-logic-web-tools/src/homepage/overView/NewModelCard.tsx
  packages/serverless-logic-web-tools/src/homepage/overView/Overview.tsx
  packages/serverless-logic-web-tools/src/homepage/pageTemplate/OnlineEditorPage.tsx
  packages/serverless-logic-web-tools/src/homepage/uiNav/HomePageNav.tsx
Labels: waiting-for-review, Serverless Workflow, DashBuilder

#1650 KOGITO-6347: Enhance vscode-extension test to verify SVG filepath settings
  packages/serverless-workflow-vscode-extension/it-tests/resources/svg-filepath/src/main/resources/hello-world.sw.json
  packages/serverless-workflow-vscode-extension/it-tests/serverless-workflow-editor-extension-svg-filepath.test.ts
  packages/vscode-extension-common-test-helpers/src/VSCodeTestHelper.ts
Labels: Serverless Workflow

#1660 NO-ISSUE: Prevent `schemas` folder from being deleted during release
  .github/workflows/release_build.yml
Labels: waiting-for-ci, Serverless Workflow

#1488 KOGITO-8720: Auto complete and YAML schema validation for YARD Editor
  packages/yard-editor/src/textEditor/YardTextEditorController.ts
  packages/yard-editor/src/textEditor/augmentation/language/schemas/yardSchema.ts
  packages/yard-editor/src/textEditor/augmentation/language/yaml/index.ts
  packages/yard-vscode-extension/package.json
Labels: waiting-for-ci, yard

#1581 KOGITO-9052: Fix test failures on first IT test of VSCode extension
  packages/serverless-workflow-vscode-extension/.vscodeignore
  packages/serverless-workflow-vscode-extension/it-tests/serverless-workflow-editor-extension-expression.test.ts
  packages/serverless-workflow-vscode-extension/it-tests/serverless-workflow-editor-extension-smoke.test.ts
  packages/serverless-workflow-vscode-extension/it-tests/settings.json
  packages/vscode-extension-common-test-helpers/src/CommonLocators.ts
  packages/vscode-extension-common-test-helpers/src/VSCodeTestHelper.ts
Labels: Foundation

#1662 kie-issues#278: Duplicate row should not copy the inputEntry id of that row
  packages/boxed-expression-component/src/expressions/DecisionTableExpression/DecisionTableExpression.tsx
Labels: DMN/SceSim, Foundation

#1647 kie-issues#252: A Decision Table's single output column header should be merged
  packages/boxed-expression-component/src/expressions/DecisionTableExpression/DecisionTableExpression.tsx
  packages/boxed-expression-component/src/table/BeeTable/BeeTableHeader.tsx
Labels: DMN/SceSim, Foundation

#1577 BXMSPROD-2016: Updating references to the new kie-ci actions folder.
  .github/workflows/jenkins-tests-PR.yml
Labels: waiting-for-ci, Foundation

#1657 kie-issues#245: Add default .env and update README
  .gitignore
  packages/kie-sandbox-distribution/.env
  packages/kie-sandbox-distribution/README.md
  packages/kie-sandbox-distribution/package.json
Labels: Foundation

#1676 KOGITO-9232: Increase memory opts for deployment builders
  packages/serverless-logic-web-tools/src/openshift/deploy/BaseContainerImages.ts
Labels: waiting-for-ci, Serverless Workflow

#1677 KOGITO-9232: Increase memory opts for deployment builders
  packages/serverless-logic-web-tools/src/openshift/deploy/BaseContainerImages.ts
Labels: waiting-for-ci, Serverless Workflow, cherry-pick 🍒

#1678 KOGITO-9238: Update SWF Basic Metrics Dashboard
  packages/dashbuilder-swf-monitoring-dashboard/src/ServerlessWorkflowMetrics.dash.yaml
Labels: waiting-for-ci, Serverless Workflow, DashBuilder

#1672 kie-issues#281: dmn-dev-deployment-quarkus-app is failing to unzip files sent from KIE Sandbox on Dev deployments
  packages/dmn-dev-deployment-base-image/Containerfile
  packages/dmn-dev-deployment-base-image/scripts/createTestImage.js
  packages/dmn-dev-deployment-quarkus-app/src/main/java/org/kie/kogito/service/ZipService.java
  packages/dmn-dev-deployment-quarkus-app/src/main/java/org/kie/kogito/service/ZipServiceImpl.java
  packages/workspaces-git-fs/src/services/WorkspaceService.tsx
  pnpm-lock.yaml
Labels: Foundation

#1674 kie-issues#282: [DMN Editor] Default output value disappears
  packages/boxed-expression-component/src/api/ExpressionDefinition.ts
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/jsinterop/props/DecisionTableProps.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/jsinterop/props/LiteralProps.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/jsinterop/props/OutputClauseProps.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/jsinterop/util/ExpressionModelFiller.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/jsinterop/util/ExpressionPropsFiller.java
  packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/test/java/org/kie/workbench/common/dmn/client/editors/expressions/jsinterop/util/ExpressionModelFillerTest.java
Labels: DMN/SceSim, Foundation

#1629 KOGITO-9100: [SWF Editor] Add AsyncAPI autocomplete support for events array
  packages/serverless-logic-web-tools/src/editor/api/SwfServiceCatalogChannelApiImpl.ts
  packages/serverless-workflow-combined-editor/src/impl/NoOpSwfServiceCatalogChannelApiImpl.ts
  packages/serverless-workflow-combined-editor/src/impl/ServerlessWorkflowTextEditorChannelApiImpl.ts
  packages/serverless-workflow-combined-editor/src/impl/SwfServiceCatalogChannelApiImpl.ts
  packages/serverless-workflow-language-service/src/api/SwfLanguageServiceChannelApi.ts
  packages/serverless-workflow-language-service/src/assets/code-completions/events-completions.ts
  packages/serverless-workflow-language-service/src/channel/SwfLanguageService.ts
  packages/serverless-workflow-language-service/src/channel/SwfLanguageServiceCodeCompletion.ts
  packages/serverless-workflow-language-service/src/channel/SwfLanguageServiceCodeLenses.ts
  packages/serverless-workflow-language-service/tests/SwfYamlLanguageService.test.ts
  packages/serverless-workflow-language-service/tests/__snapshots__/SwfJsonLanguageService.test.ts.snap
  packages/serverless-workflow-language-service/tests/__snapshots__/SwfYamlLanguageService.test.ts.snap
  packages/serverless-workflow-service-catalog/src/api/SwfServiceCatalogChannelApi.ts
  packages/serverless-workflow-service-catalog/src/api/types.ts
  packages/serverless-workflow-service-catalog/src/channel/parsers/impl/asyncapi/asyncapi.ts
  packages/serverless-workflow-text-editor/src/editor/textEditor/augmentation/commands/index.tsx
  packages/serverless-workflow-vscode-extension/src/extension/builtInVsCodeEditorSwfContributions.ts
  packages/serverless-workflow-vscode-extension/src/extension/serviceCatalog/SwfServiceCatalogChannelApiImpl.ts
  packages/serverless-workflow-vscode-extension/src/extension/serviceCatalog/SwfServiceCatalogSupportActions.ts
Labels: Serverless Workflow

#1684 NO-ISSUE: Cherry-pick kie-issues#281 fix to 0.29.0-prerelease
  packages/dmn-dev-deployment-base-image/Containerfile
  packages/dmn-dev-deployment-base-image/scripts/createTestImage.js
  packages/dmn-dev-deployment-quarkus-app/src/main/java/org/kie/kogito/service/ZipService.java
  packages/dmn-dev-deployment-quarkus-app/src/main/java/org/kie/kogito/service/ZipServiceImpl.java
  packages/workspaces-git-fs/src/services/WorkspaceService.tsx
  pnpm-lock.yaml
Labels: waiting-for-ci, Foundation

#1682 kie-issues#287: After deleting a Decision Table row, cells are wrongly selected
  packages/boxed-expression-component/src/selection/BeeTableSelectionContext.tsx
Labels: DMN/SceSim

#1673 NO-ISSUE: 0.29.0 CHANGELOGs
  packages/bpmn-vscode-extension/CHANGELOG.md
  packages/dmn-vscode-extension/CHANGELOG.md
  packages/pmml-vscode-extension/CHANGELOG.md
  packages/serverless-workflow-vscode-extension/CHANGELOG.md
  packages/vscode-extension-dashbuilder-editor/CHANGELOG.md
  packages/vscode-extension-kie-ba-bundle/CHANGELOG.md
  packages/vscode-extension-kogito-bundle/CHANGELOG.md
  packages/yard-vscode-extension/CHANGELOG.md
Labels: waiting-for-ci, Foundation

#1688 kie-issues#114: Temporarily disable `fetch classes` functionality of Import Java Classes
  packages/import-java-classes-component/src/__tests__/ImportJavaClasses/ImportJavaClasses.test.tsx
  packages/import-java-classes-component/src/__tests__/ImportJavaClasses/__snapshots__/ImportJavaClasses.test.tsx.snap
  packages/import-java-classes-component/src/components/ImportJavaClasses/ImportJavaClassesWizardFieldListTable.tsx
  packages/vscode-java-code-completion-extension-plugin/vscode-java-code-completion-extension-plugin-core/src/main/java/org/kogito/core/internal/handlers/GetAccessorsHandler.java
Labels: DMN/SceSim, java

#1690 kie-issues#289: Remove @KieActivator annotation used in Import Java Classes
  packages/vscode-java-code-completion-extension-plugin/vscode-java-code-completion-extension-plugin-core/src/main/java/org/kogito/core/internal/engine/ActivationFileVisitor.java
Labels: DMN/SceSim, java

#1669 kie-issues#272: Context Menu should always choose the best strategy to render, based on the available space of its container element
  packages/boxed-expression-component/src/contextMenu/Hooks.ts
  packages/boxed-expression-component/src/contextMenu/PopoverMenu/PopoverMenu.tsx
  packages/boxed-expression-component/src/expressions/ExpressionDefinitionHeaderMenu/DataTypeSelector.tsx
  packages/boxed-expression-component/src/table/BeeTable/BeeTableContextMenuHandler.tsx
  packages/boxed-expression-component/src/table/BeeTable/BeeTableThResizable.tsx
Labels: DMN/SceSim
