Repository apache/incubator-kie-tools, pull requests merged in 2023-10, with the labels that each got.

#1993 NO-ISSUE: Updated fixes for staging and release workflows
  .github/workflows/release_build.yml
  .github/workflows/staging_build.yml
Labels: Foundation

#1998 NO-ISSUE: Copy samples to e2e directory
  packages/chrome-extension-pack-kogito-kie-editors/e2e-tests/samples/test.bpmn
  packages/chrome-extension-pack-kogito-kie-editors/e2e-tests/samples/test.dmn
  packages/chrome-extension-serverless-workflow-editor/e2e-tests/samples/chrome_sample.sw.json
  packages/chrome-extension-serverless-workflow-editor/e2e-tests/samples/chrome_sample.sw.yaml
Labels: Serverless Workflow

#1992 NO-ISSUE: Rename findings of it tests to e2e tests
  .github/workflows/ci_build.yml
  README.md
  packages/chrome-extension-pack-kogito-kie-editors/e2e-tests/tests/BpmnFullScreenTest.ts
  packages/chrome-extension-pack-kogito-kie-editors/e2e-tests/tests/BpmnTest.ts
  packages/chrome-extension-pack-kogito-kie-editors/e2e-tests/tests/DmnExpressionEditorTest.ts
  packages/chrome-extension-pack-kogito-kie-editors/e2e-tests/tests/DmnFullScreenTest.ts
  packages/chrome-extension-pack-kogito-kie-editors/e2e-tests/tests/DmnTest.ts
  packages/chrome-extension-pack-kogito-kie-editors/it-tests/samples/test.bpmn
  packages/chrome-extension-pack-kogito-kie-editors/it-tests/samples/test.dmn
  packages/chrome-extension-serverless-workflow-editor/e2e-tests/tests/SwfFullScreenTest.ts
  packages/chrome-extension-serverless-workflow-editor/e2e-tests/tests/SwfTest.ts
  packages/chrome-extension-serverless-workflow-editor/it-tests/samples/chrome_sample.sw.json
  packages/chrome-extension-serverless-workflow-editor/it-tests/samples/chrome_sample.sw.yaml
  packages/kie-editors-dev-vscode-extension/e2e-tests/extension-editors-bpmn.test.ts
  packages/kie-editors-dev-vscode-extension/e2e-tests/extension-editors-dmn.test.ts
  packages/kie-editors-dev-vscode-extension/e2e-tests/extension-editors-scesim.test.ts
  packages/kie-editors-dev-vscode-extension/e2e-tests/extension-editors-smoke.test.ts
  packages/kn-plugin-workflow/.vscode/settings.json
  packages/kn-plugin-workflow/README.md
  packages/kn-plugin-workflow/e2e-tests/create_test.go
  packages/kn-plugin-workflow/e2e-tests/deploy_test.go
  packages/kn-plugin-workflow/e2e-tests/helper_test.go
  packages/kn-plugin-workflow/e2e-tests/main_test.go
  packages/kn-plugin-workflow/e2e-tests/quarkus_build_test.go
  packages/kn-plugin-workflow/e2e-tests/quarkus_convert_test.go
  packages/kn-plugin-workflow/e2e-tests/quarkus_create_test.go
  packages/kn-plugin-workflow/e2e-tests/quarkus_run_test.go
  packages/kn-plugin-workflow/e2e-tests/run_test.go
  packages/kn-plugin-workflow/e2e-tests/test_env.go
  packages/online-editor/README.md
  packages/serverless-workflow-vscode-extension/e2e-tests/serverless-workflow-editor-extension-autocompletion.test.ts
  packages/serverless-workflow-vscode-extension/e2e-tests/serverless-workflow-editor-extension-basic-operations.test.ts
  packages/serverless-workflow-vscode-extension/e2e-tests/serverless-workflow-editor-extension-diagram-navigation.test.ts
  packages/serverless-workflow-vscode-extension/e2e-tests/serverless-workflow-editor-extension-events.test.ts
  packages/serverless-workflow-vscode-extension/e2e-tests/serverless-workflow-editor-extension-expression.test.ts
  packages/serverless-workflow-vscode-extension/e2e-tests/serverless-workflow-editor-extension-functions.test.ts
  packages/serverless-workflow-vscode-extension/e2e-tests/serverless-workflow-editor-extension-smoke.test.ts
  packages/serverless-workflow-vscode-extension/e2e-tests/serverless-workflow-editor-extension-svg-filepath.test.ts
  packages/serverless-workflow-vscode-extension/e2e-tests/serverless-workflow-editor-extension-syntax-highlight.test.ts
  packages/vscode-extension-dashbuilder-editor/e2e-tests/dashbuilder-editor-extension-smoke.test.ts
  packages/yard-vscode-extension/e2e-tests/yard-editor.test.ts
Labels: waiting-for-ci

#1999 NO-ISSUE: `jspdf` CVEs
  packages/stunner-editors/uberfire-extensions/uberfire-commons-editor/uberfire-commons-editor-client/pom.xml
Labels: dependencies

#2000 Revert "NO-ISSUE: Update `go` to `1.21.1` follow-up (#1966)"
  examples/commit-message-validation-service/go.mod
  examples/commit-message-validation-service/go.sum
  packages/extended-services/go.mod
  packages/kn-plugin-workflow/go.mod
  packages/kn-plugin-workflow/go.sum
  packages/kn-plugin-workflow/go.work
Labels: Foundation, dependencies

#2002 [0.32.0] Revert "NO-ISSUE: Update go to 1.21.1 follow-up (#1966)"
  examples/commit-message-validation-service/go.mod
  examples/commit-message-validation-service/go.sum
  packages/extended-services/go.mod
  packages/kn-plugin-workflow/go.mod
  packages/kn-plugin-workflow/go.sum
  packages/kn-plugin-workflow/go.work
Labels: waiting-for-ci, Foundation, cherry-pick 🍒

#2006 KOGITO-9862: Manifest gen should not required a cluster connection
  packages/kn-plugin-workflow/.gitignore
  packages/kn-plugin-workflow/pkg/command/gen_manifest.go
Labels: Serverless Workflow, go

#2004 NO-ISSUE: Do not run e2e tests on build image steps in the staging job
  .github/workflows/staging_build.yml
Labels: waiting-for-ci, Foundation

#2007 [0.32.0] KOGITO-9862: Manifest gen should not required a cluster connection
  packages/kn-plugin-workflow/.gitignore
  packages/kn-plugin-workflow/pkg/command/gen_manifest.go
Labels: go, cherry-pick 🍒

#2005 kie-issues#603: Colorize Decision Services call in FEEL expressions in DMN Editor's Boxed Expression Editor
  packages/dmn-feel-antlr4-parser/src/index.ts
  packages/dmn-feel-antlr4-parser/src/parser/FeelVariable.ts
  packages/dmn-feel-antlr4-parser/src/parser/SymbolType.ts
  packages/dmn-feel-antlr4-parser/src/parser/Variable.ts
  packages/dmn-feel-antlr4-parser/src/parser/VariablesRepository.ts
  packages/dmn-feel-antlr4-parser/src/parser/grammar/ParserHelper.ts
  packages/dmn-feel-antlr4-parser/src/parser/grammar/VariableSymbol.ts
  packages/feel-input-component/src/FeelConfigs.ts
  packages/feel-input-component/src/FeelInput.tsx
  packages/feel-input-component/src/themes/Element.ts
Labels: waiting-for-review, DMN

#2009 NO-ISSUE: Remove deleted packages on the lock file
  pnpm-lock.yaml
Labels: Foundation

#1995 KOGITO-9837: Reuse components migrated from kogito-apps
  packages/runtime-tools-enveloped-components/jest.config.js
  packages/runtime-tools-enveloped-components/src/__tests__/components/validateCloudEventRequest.test.ts
  packages/runtime-tools-enveloped-components/src/__tests__/components/validateWorkflowData.test.ts
  packages/runtime-tools-enveloped-components/src/__tests__/jest.setup.ts
  packages/runtime-tools-enveloped-components/src/workflowForm/envelope/components/WorkflowResult/WorkflowResult.tsx
  packages/runtime-tools-gateway-api/jest.config.js
  packages/runtime-tools-gateway-api/package.json
  packages/runtime-tools-gateway-api/src/__tests__/apis/apis.test.tsx
  packages/runtime-tools-gateway-api/src/__tests__/jest.setup.ts
  packages/runtime-tools-gateway-api/src/gatewayApi/apis.tsx
  packages/runtime-tools-gateway-api/src/types.ts
  packages/serverless-logic-web-tools/src/runtimeTools/workflows/WorkflowForm/WorkflowFormGatewayApi.ts
  packages/sonataflow-deployment-webapp/package.json
  packages/sonataflow-deployment-webapp/src/__tests__/components/validateWorkflowData.test.ts
  packages/sonataflow-deployment-webapp/src/__tests__/impl/CloudEventFormGatewayApiImpl.test.ts
  packages/sonataflow-deployment-webapp/src/__tests__/impl/WorkflowFormGatewayApiImpl.test.ts
  packages/sonataflow-deployment-webapp/src/apis/WorkflowResponse.ts
  packages/sonataflow-deployment-webapp/src/apis/apis.tsx
  packages/sonataflow-deployment-webapp/src/apis/index.ts
  packages/sonataflow-deployment-webapp/src/components/CloudEventCustomHeadersEditor.tsx
  packages/sonataflow-deployment-webapp/src/components/CloudEventFieldLabelIcon.tsx
  packages/sonataflow-deployment-webapp/src/components/CustomWorkflowForm.tsx
  packages/sonataflow-deployment-webapp/src/components/FormNotification.tsx
  packages/sonataflow-deployment-webapp/src/components/FormRenderer.tsx
  packages/sonataflow-deployment-webapp/src/components/WorkflowResult.tsx
  packages/sonataflow-deployment-webapp/src/components/index.ts
  packages/sonataflow-deployment-webapp/src/components/utils/FormActionsUtils.tsx
  packages/sonataflow-deployment-webapp/src/components/utils/FormValidator.ts
  packages/sonataflow-deployment-webapp/src/components/utils/ModelConversionTool.ts
  packages/sonataflow-deployment-webapp/src/components/validateCloudEventRequest.ts
  packages/sonataflow-deployment-webapp/src/components/validateWorkflowData.ts
  packages/sonataflow-deployment-webapp/src/impl/CloudEventFormGatewayApiImpl.ts
  packages/sonataflow-deployment-webapp/src/impl/WorkflowFormGatewayApiImpl.ts
  packages/sonataflow-deployment-webapp/src/pages/ErrorPage.tsx
  packages/sonataflow-deployment-webapp/src/pages/Workflows/CloudEventFormPage.tsx
  packages/sonataflow-deployment-webapp/src/pages/Workflows/WorkflowFormPage.tsx
  pnpm-lock.yaml
Labels: Serverless Workflow

#2010 NO-ISSUE: Fix standalone job in the release workflow
  .github/workflows/release_build.yml
Labels: Foundation

#2013 KOGITO-9892: Layout of boxes in SWF Web Tools is broken when sidebar is hidden
  pnpm-lock.yaml
Labels: Foundation, Serverless Workflow

#1989 NO-ISSUE: 0.32.0 CHANGELOGs
  packages/bpmn-vscode-extension/CHANGELOG.md
  packages/dmn-vscode-extension/CHANGELOG.md
  packages/pmml-vscode-extension/CHANGELOG.md
  packages/serverless-workflow-vscode-extension/CHANGELOG.md
  packages/vscode-extension-dashbuilder-editor/CHANGELOG.md
  packages/vscode-extension-kie-ba-bundle/CHANGELOG.md
  packages/vscode-extension-kogito-bundle/CHANGELOG.md
  packages/yard-vscode-extension/CHANGELOG.md
Labels: Foundation

#2017 kie-issues#366: Translate the Extended Services Go App to a new Java Application.
  packages/extended-services-java/LICENSE
  packages/extended-services-java/README.md
  packages/extended-services-java/env/index.js
  packages/extended-services-java/install.js
  packages/extended-services-java/package.json
  packages/extended-services-java/pom.xml
  packages/extended-services-java/src/main/java/org/kie/tools/PingResource.java
  packages/extended-services-java/src/main/java/org/kie/tools/PingResponse.java
  packages/extended-services-java/src/main/java/org/kie/tools/ProxyConfig.java
  packages/extended-services-java/src/main/resources/application.properties
  packages/extended-services-java/src/test/java/org/kie/tools/PingResourceTest.java
  packages/extended-services-java/src/test/java/org/kie/tools/PingResponseTest.java
  packages/extended-services-java/src/test/java/org/kie/tools/ProxyConfigTest.java
  pnpm-lock.yaml
  repo/graph.dot
  repo/graph.json
Labels: Foundation

#2021 kie-issue#374: DMN Editor: user can not increase the number of added rows/columns quickly in nested expressions
  packages/boxed-expression-component/src/table/BeeTable/BeeTableContextMenuHandler.tsx
Labels: waiting-for-review, DMN

#2020 kie-issue#636: DMN Monaco highlighting throws error when used with DMN Runner
  packages/online-editor/src/dmnRunner/DmnRunnerDrawer.tsx
Labels: waiting-for-review, DMN

#2018 kie-issue#206: Enable autocomplete suggestions for Literal Expressions and Decision Table input cells on DMN Editor's Boxed Expression Editor
  packages/boxed-expression-component/src/expressions/ContextExpression/ContextExpression.tsx
  packages/dmn-feel-antlr4-parser/src/index.ts
  packages/dmn-feel-antlr4-parser/src/parser/DataType.ts
  packages/dmn-feel-antlr4-parser/src/parser/FeelSymbol.ts
  packages/dmn-feel-antlr4-parser/src/parser/FeelSyntacticSymbolNature.ts
  packages/dmn-feel-antlr4-parser/src/parser/FeelVariable.ts
  packages/dmn-feel-antlr4-parser/src/parser/FeelVariablesParser.ts
  packages/dmn-feel-antlr4-parser/src/parser/ParsedExpression.ts
  packages/dmn-feel-antlr4-parser/src/parser/Variable.ts
  packages/dmn-feel-antlr4-parser/src/parser/VariablesRepository.ts
  packages/dmn-feel-antlr4-parser/src/parser/grammar/MapBackedType.ts
  packages/dmn-feel-antlr4-parser/src/parser/grammar/ParserHelper.ts
  packages/dmn-feel-antlr4-parser/src/parser/grammar/Type.ts
  packages/dmn-feel-antlr4-parser/src/parser/grammar/VariableSymbol.ts
  packages/feel-input-component/src/FeelConfigs.ts
  packages/feel-input-component/src/FeelInput.tsx
Labels: waiting-for-review, DMN

#2024 NO-ISSUE: Avoid render loop in Extended Services Wizard component in KIE Sandbox
  packages/online-editor/src/extendedServices/ExtendedServicesModal.tsx
Labels: Foundation

#2026 NO-ISSUE: Bump `webdriver` to version 5.5.3
  packages/serverless-workflow-diagram-editor/pom.xml
  packages/stunner-editors/pom.xml
Labels: dependencies

#2023 NO-ISSUE: Bump `eslint` and related dependencies versions
  packages/eslint/package.json
  pnpm-lock.yaml
Labels: dependencies
