Repository apache/incubator-kie-tools, pull requests merged in 2024-10, with the labels that each got.

#2546 kie-issues#886: On the DMN Editor, adding waypoints to edges that don't have a corresponding DMNEdge associated with it should create the DMNEdge and add the waypoint normally
  packages/dmn-editor/src/diagram/Diagram.tsx
  packages/dmn-editor/src/diagram/connections/isValidConnection.ts
  packages/dmn-editor/src/diagram/edges/usePotentialWaypointControls.ts
  packages/dmn-editor/src/mutations/addEdge.ts
  packages/dmn-editor/src/mutations/addEdgeWaypoint.ts
  packages/dmn-editor/src/mutations/addShape.ts
  packages/dmn-editor/src/mutations/addStandaloneNode.ts
  packages/dmn-editor/src/mutations/deleteEdge.ts
  packages/dmn-editor/src/store/computed/computeDiagramData.ts
  packages/dmn-editor/tests-e2e/__fixtures__/drgNodes.ts
  packages/dmn-editor/tests-e2e/__screenshots__/Google-Chrome/drds/drds-ar-edge-depiction-waypoint.png
  packages/dmn-editor/tests-e2e/__screenshots__/Google-Chrome/drds/drds-ir-edge-depiction-waypoint.png
  packages/dmn-editor/tests-e2e/__screenshots__/Google-Chrome/drds/drds-kr-edge-depiction-waypoint.png
  packages/dmn-editor/tests-e2e/__screenshots__/chromium/drds/drds-ar-edge-depiction-waypoint.png
  packages/dmn-editor/tests-e2e/__screenshots__/chromium/drds/drds-ir-edge-depiction-waypoint.png
  packages/dmn-editor/tests-e2e/__screenshots__/chromium/drds/drds-kr-edge-depiction-waypoint.png
  packages/dmn-editor/tests-e2e/__screenshots__/webkit/drds/drds-ar-edge-depiction-waypoint.png
  packages/dmn-editor/tests-e2e/__screenshots__/webkit/drds/drds-ir-edge-depiction-waypoint.png
  packages/dmn-editor/tests-e2e/__screenshots__/webkit/drds/drds-kr-edge-depiction-waypoint.png
  packages/dmn-editor/tests-e2e/drds/modelDrd.spec.ts
Labels: area:dmn

#2636 NO-ISSUE: Fix `turbo ls` command with too many filters on the Windows runner in GitHub Actions
  .github/supporting-files/ci/build-partitioning/build_partitioning.ts
Labels: area:monorepo

#2639 NO-ISSUE: Increase Playwright toHaveScreenshot assertion threshold to 10%
  packages/boxed-expression-component/playwright.config.ts
  packages/playwright-base/playwright.config.ts
  packages/scesim-editor/playwright.config.ts
Labels: area:tests

#2640 [10.0.x] Release job image upload fixes and updates
  .ci/jenkins/release-jobs/Jenkinsfile.extended-services
  .ci/jenkins/release-jobs/Jenkinsfile.kie-sandbox
  .ci/jenkins/release-jobs/Jenkinsfile.kogito-swf-builder
  .ci/jenkins/release-jobs/Jenkinsfile.kogito-swf-devmode
  .ci/jenkins/release-jobs/Jenkinsfile.online-editor
  packages/dmn-marshaller-backend-compatibility-tester/src/DmnMarshallerBackendCompatibilityTesterScript.java
Labels: area:cicd

#2643 [10.0.x][NO-ISSUE] Missing maven settings file updates on sonataflow image release jobs
  .ci/jenkins/release-jobs/Jenkinsfile.kn-plugin-workflow
  .ci/jenkins/release-jobs/Jenkinsfile.kogito-serverless-operator
  .ci/jenkins/release-jobs/Jenkinsfile.npm-packages
  .ci/jenkins/release-jobs/Jenkinsfile.serverless-logic-web-tools-swf-builder-image
Labels: area:cicd

#2644 NO-ISSUE: In AJV v8 the `validation` object `dataPath` property was renamed to `instancePath`
  packages/form/src/FormHook.tsx
Labels: area:dmn

#2647 NO-ISSUE: CI partitioning script was leaving out the last package
  .github/supporting-files/ci/build-partitioning/build_partitioning.ts
Labels: area:monorepo, area:cicd

#2611 kie-issues#1158: On the Boxed Expression Component, changing the ExpressionVariableCell text content will fail to commit if the focus is changed to another cell
  packages/boxed-expression-component/src/expressions/FunctionExpression/FunctionExpression.tsx
  packages/boxed-expression-component/src/expressions/FunctionExpression/FunctionKindSelector.tsx
  packages/boxed-expression-component/src/selection/BeeTableSelectionContext.tsx
  packages/boxed-expression-component/tests-e2e/__screenshots__/Google-Chrome/boxedExpressions/decisionTable/boxed-decision-table-commit-annotation-by-cell-click.png
  packages/boxed-expression-component/tests-e2e/__screenshots__/Google-Chrome/boxedExpressions/every/boxed-every-commit-variable-by-cell-click.png
  packages/boxed-expression-component/tests-e2e/__screenshots__/Google-Chrome/boxedExpressions/invocation/boxed-invocation-commit-function-by-cell-click.png
  packages/boxed-expression-component/tests-e2e/__screenshots__/Google-Chrome/boxedExpressions/some/boxed-some-commit-variable-by-cell-click.png
  packages/boxed-expression-component/tests-e2e/__screenshots__/chromium/boxedExpressions/decisionTable/boxed-decision-table-commit-annotation-by-cell-click.png
  packages/boxed-expression-component/tests-e2e/__screenshots__/chromium/boxedExpressions/every/boxed-every-commit-variable-by-cell-click.png
  packages/boxed-expression-component/tests-e2e/__screenshots__/chromium/boxedExpressions/invocation/boxed-invocation-commit-function-by-cell-click.png
  packages/boxed-expression-component/tests-e2e/__screenshots__/chromium/boxedExpressions/some/boxed-some-commit-variable-by-cell-click.png
  packages/boxed-expression-component/tests-e2e/__screenshots__/webkit/boxedExpressions/decisionTable/boxed-decision-table-commit-annotation-by-cell-click.png
  packages/boxed-expression-component/tests-e2e/__screenshots__/webkit/boxedExpressions/decisionTable/decision-table-routing.png
  packages/boxed-expression-component/tests-e2e/__screenshots__/webkit/boxedExpressions/every/boxed-every-commit-variable-by-cell-click.png
  packages/boxed-expression-component/tests-e2e/__screenshots__/webkit/boxedExpressions/invocation/boxed-invocation-commit-function-by-cell-click.png
  packages/boxed-expression-component/tests-e2e/__screenshots__/webkit/boxedExpressions/some/boxed-some-commit-variable-by-cell-click.png
  packages/boxed-expression-component/tests-e2e/api/annotationCell.ts
  packages/boxed-expression-component/tests-e2e/api/expressions/contextExpressionElement.ts
  packages/boxed-expression-component/tests-e2e/api/expressions/decisionTableExpressionElement.ts
  packages/boxed-expression-component/tests-e2e/api/expressions/functionExpressionElement.ts
  packages/boxed-expression-component/tests-e2e/api/expressions/invocationExpressionElement.ts
  packages/boxed-expression-component/tests-e2e/api/functionType.ts
  packages/boxed-expression-component/tests-e2e/api/nameAndDataTypeWithStandalonePopoverCell.ts
  packages/boxed-expression-component/tests-e2e/boxedExpressions/context/populate.spec.ts
  packages/boxed-expression-component/tests-e2e/boxedExpressions/decisionTable/decisionTableExpression.spec.ts
  packages/boxed-expression-component/tests-e2e/boxedExpressions/decisionTable/populate.spec.ts
  packages/boxed-expression-component/tests-e2e/boxedExpressions/every/everyExpression.spec.ts
  packages/boxed-expression-component/tests-e2e/boxedExpressions/filter/filterExpression.spec.ts
  packages/boxed-expression-component/tests-e2e/boxedExpressions/filter/populate.spec.ts
  packages/boxed-expression-component/tests-e2e/boxedExpressions/function/functionExpression.spec.ts
  packages/boxed-expression-component/tests-e2e/boxedExpressions/function/parameters.spec.ts
  packages/boxed-expression-component/tests-e2e/boxedExpressions/function/populate.spec.ts
  packages/boxed-expression-component/tests-e2e/boxedExpressions/invocation/invocationExpression.spec.ts
  packages/boxed-expression-component/tests-e2e/boxedExpressions/invocation/populate.spec.ts
  packages/boxed-expression-component/tests-e2e/boxedExpressions/list/populate.spec.ts
  packages/boxed-expression-component/tests-e2e/boxedExpressions/literal/populate.spec.ts
  packages/boxed-expression-component/tests-e2e/boxedExpressions/relation/populate.spec.ts
  packages/boxed-expression-component/tests-e2e/boxedExpressions/some/someExpression.spec.ts
Labels: area:dmn

#2676 NO-ISSUE: Fixes `pnpm start` in jbpm-quarkus-dev-ui
  packages/jbpm-quarkus-devui/dev/pom.xml
Labels: area:bpmn

#2663 NO-ISSUE: Fix Storybook static web application build
  packages/boxed-expression-component/package.json
  packages/dmn-editor/package.json
  packages/scesim-editor/package.json
  packages/storybook-base/src/config/baseConfig.ts
Labels: area:monorepo

#2664 [incubator-kie-issues#1534] Remove less.jar from errai-ui
  packages/stunner-editors/errai-ui/src/test/resources/less.jar
Labels: pr: DO NOT MERGE

#2682 kie-tools#2621: Remove build-kogito-app stage from Kogito images
  packages/kogito-base-builder-image/package.json
  packages/kogito-data-index-ephemeral-image/package.json
  packages/kogito-data-index-ephemeral-image/resources/app/pom.xml
  packages/kogito-data-index-ephemeral-image/resources/incubator-kie-kogito-data-index-ephemeral-image.yaml
  packages/kogito-data-index-ephemeral-image/resources/modules/kogito-data-index-ephemeral/module.yaml
  packages/kogito-data-index-postgresql-image/package.json
  packages/kogito-data-index-postgresql-image/resources/app/pom.xml
  packages/kogito-data-index-postgresql-image/resources/incubator-kie-kogito-data-index-postgresql-image.yaml
  packages/kogito-data-index-postgresql-image/resources/modules/kogito-data-index-postgresql/module.yaml
  packages/kogito-jit-runner-image/package.json
  packages/kogito-jit-runner-image/resources/app/pom.xml
  packages/kogito-jit-runner-image/resources/incubator-kie-kogito-jit-runner-image.yaml
  packages/kogito-jit-runner-image/resources/modules/kogito-jit-runner/module.yaml
  packages/kogito-jobs-service-allinone-image/package.json
  packages/kogito-jobs-service-allinone-image/resources/app/ephemeral/pom.xml
  packages/kogito-jobs-service-allinone-image/resources/app/pom.xml
  packages/kogito-jobs-service-allinone-image/resources/app/postgresql/pom.xml
  packages/kogito-jobs-service-allinone-image/resources/incubator-kie-kogito-jobs-service-allinone-image.yaml
  packages/kogito-jobs-service-allinone-image/resources/modules/kogito-jobs-service-all-in-one/module.yaml
  packages/kogito-jobs-service-ephemeral-image/package.json
  packages/kogito-jobs-service-ephemeral-image/resources/app/pom.xml
  packages/kogito-jobs-service-ephemeral-image/resources/incubator-kie-kogito-jobs-service-ephemeral-image.yaml
  packages/kogito-jobs-service-ephemeral-image/resources/modules/kogito-jobs-service-ephemeral/added/kogito-app-launch.sh
  packages/kogito-jobs-service-ephemeral-image/resources/modules/kogito-jobs-service-ephemeral/configure
  packages/kogito-jobs-service-ephemeral-image/resources/modules/kogito-jobs-service-ephemeral/module.yaml
  packages/kogito-jobs-service-ephemeral-image/test-resources/tests/features/kogito-jobs-service-ephemeral.feature
  packages/kogito-jobs-service-postgresql-image/package.json
  packages/kogito-jobs-service-postgresql-image/resources/app/pom.xml
  packages/kogito-jobs-service-postgresql-image/resources/incubator-kie-kogito-jobs-service-postgresql-image.yaml
  packages/kogito-jobs-service-postgresql-image/resources/modules/kogito-jobs-service-postgresql/added/kogito-app-launch.sh
  packages/kogito-jobs-service-postgresql-image/resources/modules/kogito-jobs-service-postgresql/module.yaml
  packages/kogito-jobs-service-postgresql-image/test-resources/tests/features/kogito-jobs-service-postgresql.feature
  packages/sonataflow-image-common/resources/Makefile
  packages/sonataflow-image-common/resources/modules/kogito-maven/common/tests/bats/maven-settings.bats
  packages/sonataflow-image-common/resources/scripts/README.md
  packages/sonataflow-image-common/resources/scripts/common.py
  pnpm-lock.yaml
  repo/graph.dot
  repo/graph.json
Labels: area:monorepo

#2628 kie-issues#1463: Test Scenario Editor: Manage `@kie-tools/scesim-editor`'s state with Zustand + Immer
  packages/dmn-editor/package.json
  packages/dmn-editor/stories/useCases/loanPreQualification/LoanPreQualification.stories.tsx
  packages/scesim-editor/.storybook/preview.tsx
  packages/scesim-editor/README.md
  packages/scesim-editor/package.json
  packages/scesim-editor/src/TestScenarioEditor.tsx
  packages/scesim-editor/src/TestScenarioEditorContext.tsx
  packages/scesim-editor/src/TestScenarioEditorErrorFallback.tsx
  packages/scesim-editor/src/common/TestScenarioCommonFunctions.tsx
  packages/scesim-editor/src/creation/TestScenarioCreationPanel.tsx
  packages/scesim-editor/src/drawer/TestScenarioDrawerCheatSheetPanel.tsx
  packages/scesim-editor/src/drawer/TestScenarioDrawerDataSelectorPanel.tsx
  packages/scesim-editor/src/drawer/TestScenarioDrawerPanel.tsx
  packages/scesim-editor/src/drawer/TestScenarioDrawerSettingsPanel.tsx
  packages/scesim-editor/src/hook/useEffectAfterFirstRender.ts
  packages/scesim-editor/src/i18n/TestScenarioEditorI18n.ts
  packages/scesim-editor/src/i18n/locales/en.ts
  packages/scesim-editor/src/mutations/addColumn.ts
  packages/scesim-editor/src/mutations/addRow.ts
  packages/scesim-editor/src/mutations/deleteColumn.ts
  packages/scesim-editor/src/mutations/deleteRow.ts
  packages/scesim-editor/src/mutations/duplicateRow.ts
  packages/scesim-editor/src/mutations/updateCell.ts
  packages/scesim-editor/src/mutations/updateColumn.ts
  packages/scesim-editor/src/mutations/updateColumnWidth.ts
  packages/scesim-editor/src/reactExt/ErrorBoundary.tsx
  packages/scesim-editor/src/sidebar/TestScenarioSideBarMenu.tsx
  packages/scesim-editor/src/store/ComputedStateCache.ts
  packages/scesim-editor/src/store/TestScenarioEditorStore.ts
  packages/scesim-editor/src/store/TestScenarioStoreContext.ts
  packages/scesim-editor/src/store/computed/computeTestScenarioDataObjects.ts
  packages/scesim-editor/src/store/computed/initial.ts
  packages/scesim-editor/src/table/TestScenarioTable.tsx
  packages/scesim-editor/stories/dev/DevWebApp.stories.tsx
  packages/scesim-editor/stories/examples/AvailableDMNModels.ts
  packages/scesim-editor/stories/misc/empty/Empty.stories.tsx
  packages/scesim-editor/stories/scesimEditor/SceSimEditor.mdx
  packages/scesim-editor/stories/scesimEditorStoriesWrapper.tsx
  packages/scesim-editor/stories/useCases/IsOldEnoughRule.stories.tsx
  packages/scesim-editor/stories/useCases/TrafficViolationDmn.stories.tsx
  packages/scesim-editor/tests-e2e/__screenshots__/Google-Chrome/misc/emptyExpression/create-a-new-test-scenario.png
  packages/scesim-editor/tests-e2e/__screenshots__/chromium/misc/emptyExpression/create-a-new-test-scenario.png
  packages/scesim-editor/tests-e2e/__screenshots__/webkit/misc/emptyExpression/create-a-new-test-scenario.png
  packages/scesim-marshaller/src/schemas/scesim-1_8/SceSim.xsd
  pnpm-lock.yaml
Labels: pr: order: 1, area:scesim

#2689 kie-issues#2679: [SonataFlow] SonataFlow Management Console on KIE Tools daily dev job
  .ci/jenkins/Jenkinsfile.daily-dev-publish
Labels: pr: DO NOT MERGE, area:cicd

#2690 Revert "kie-issues#2679: [SonataFlow] SonataFlow Management Console on KIE Tools daily dev job (#2689)"
  .ci/jenkins/Jenkinsfile.daily-dev-publish
Labels: area:cicd

#2675 [Incubator-kie-issues#1314] @kie-tools/jbpm-quarkus-devui: Wrong behaviors on the Error notification in Start Process Form component
  packages/runtime-tools-components/src/common/components/FormNotification/FormNotification.tsx
  packages/runtime-tools-process-dev-ui-webapp/src/components/containers/ProcessFormContainer/ProcessFormContainer.tsx
  packages/runtime-tools-process-dev-ui-webapp/src/components/pages/ProcessFormPage/ProcessFormPage.tsx
Labels: area:bpmn

#2669 NO-ISSUE: Bump up `vscode-extension-tester` to 8.8.0
  packages/kie-editors-dev-vscode-extension/package.json
  packages/serverless-workflow-vscode-extension/package.json
  packages/vscode-extension-common-test-helpers/package.json
  packages/vscode-extension-dashbuilder-editor/package.json
  packages/yard-vscode-extension/package.json
  pnpm-lock.yaml
Labels: area:dependencies

#2688 NO-ISSUE: install libraries in CI docker image
  .ci/incubator-kie-tools-ci-build.Dockerfile
Labels: area:cicd

#2699 NO-ISSUE: Upgrade `syncpack` to 13.0.0 on Jenkins jobs
  .ci/jenkins/ci-jobs/Jenkinsfile.ci-check-dependencies
Labels: area:cicd

#2678 NO-ISSUE: Upgrade Kogito to `999-20241016-SNAPSHOT`
  examples/jbpm-compact-architecture-example/pom.xml
  examples/jbpm-compact-architecture-example/src/main/resources/application.properties
  packages/maven-base/pom.xml
  packages/root-env/env/index.js
  packages/sonataflow-operator/test/testdata/platform/noservices/preview/ephemeral/02-sonataflow_platform.yaml
  packages/sonataflow-operator/test/testdata/platform/services/dev/ephemeral/02-sonataflow_platform.yaml
  packages/sonataflow-operator/test/testdata/platform/services/dev/postgreSQL/02-sonataflow_platform.yaml
  packages/sonataflow-operator/test/testdata/platform/services/preview/cluster-wide-ephemeral/02-sonataflow_platform.yaml
  packages/sonataflow-operator/test/testdata/platform/services/preview/ephemeral-data-index/02-sonataflow_platform.yaml
  packages/sonataflow-operator/test/testdata/platform/services/preview/ephemeral-job-service/02-sonataflow_platform.yaml
  packages/sonataflow-operator/test/testdata/workflow/persistence/by_service/02-sonataflow_platform.yaml
  packages/sonataflow-operator/test/testdata/workflow/persistence/from_platform_overwritten_by_service/02-sonataflow_platform.yaml
  packages/sonataflow-operator/test/testdata/workflow/persistence/from_platform_with_di_and_js_services/02-sonataflow_platform.yaml
  packages/sonataflow-operator/test/testdata/workflow/persistence/from_platform_with_no_persistence_required/02-sonataflow_platform.yaml
  packages/sonataflow-operator/test/testdata/workflow/persistence/from_platform_without_di_and_js_services/02-sonataflow_platform.yaml
  repo/MANUAL.md
Labels: area:dependencies

#2683 kie-issues#2654: [SonataFlow] Empty WF Instance page if variables is null
  packages/runtime-tools-swf-enveloped-components/src/workflowDetails/envelope/components/WorkflowDetails/WorkflowDetails.tsx
  packages/runtime-tools-swf-enveloped-components/tests/components/WorkflowDefinitionList.test.tsx
  packages/runtime-tools-swf-enveloped-components/tests/components/WorkflowDetails.test.tsx
Labels: area:sonataflow

#2710 NO-ISSUE: jBPM Quarkus Dev UI and Compact Architecture Example general adjustments (Part 1)
  _intellij-project/.idea/jsLibraryMappings.xml
  _intellij-project/.idea/prettier.xml
  examples/jbpm-compact-architecture-example/.gitignore
  examples/jbpm-compact-architecture-example/README.md
  examples/jbpm-compact-architecture-example/docker-compose/.gitignore
  examples/jbpm-compact-architecture-example/docker-compose/README.md
  examples/jbpm-compact-architecture-example/docker-compose/docker-compose.yml
  examples/jbpm-compact-architecture-example/docker-compose/startContainers.sh
  examples/jbpm-compact-architecture-example/docs/images/new_hiring_offer_dmn.png
  examples/jbpm-compact-architecture-example/docs/images/new_hiring_offer_dmn_decision.png
  examples/jbpm-compact-architecture-example/docs/images/new_hiring_offer_dmn_types.png
  examples/jbpm-compact-architecture-example/docs/images/new_hiring_offer_dmn_types_tCandidateData.png
  examples/jbpm-compact-architecture-example/docs/images/new_hiring_offer_dmn_types_tOffer.png
  examples/jbpm-compact-architecture-example/package.json
  examples/jbpm-compact-architecture-example/pom.xml
  packages/jbpm-quarkus-devui/dev/pom.xml
  packages/jbpm-quarkus-devui/jbpm-quarkus-devui-deployment/src/main/java/org/jbpm/quarkus/devui/deployment/DevConsoleProcessor.java
  packages/jbpm-quarkus-devui/jbpm-quarkus-devui-runtime/src/main/java/org/jbpm/quarkus/devui/runtime/config/DevConsoleRuntimeConfig.java
  packages/runtime-tools-management-console-webapp/src/components/pages/TaskDetailsPage/TaskDetailsPage.tsx
  packages/runtime-tools-management-console-webapp/src/components/pages/TasksPage/TasksPage.tsx
  packages/runtime-tools-process-dev-ui-webapp/src/components/DevUI/DevUINav/DevUINav.tsx
  packages/runtime-tools-process-dev-ui-webapp/src/components/DevUI/DevUIRoutes/DevUIRoutes.tsx
  packages/runtime-tools-process-dev-ui-webapp/src/components/containers/TaskInboxContainer/TaskInboxContainer.tsx
  packages/runtime-tools-process-dev-ui-webapp/src/components/pages/JobsManagementPage/JobsManagementPage.tsx
  packages/runtime-tools-process-dev-ui-webapp/src/components/pages/TaskDetailsPage/TaskDetailsPage.tsx
  packages/runtime-tools-process-dev-ui-webapp/src/components/pages/TaskInboxPage/TaskInboxPage.tsx
  packages/runtime-tools-process-dev-ui-webapp/src/components/pages/TaskInboxPage/components/TaskInboxSwitchUser.tsx
  packages/runtime-tools-process-enveloped-components/src/jobsManagement/envelope/JobsManagementEnvelope.tsx
  packages/runtime-tools-process-enveloped-components/src/jobsManagement/envelope/JobsManagementEnvelopeContext.ts
  packages/runtime-tools-process-enveloped-components/src/jobsManagement/envelope/components/JobsManagementTable/JobsManagementTable.tsx
  packages/runtime-tools-process-enveloped-components/src/taskInbox/api/TaskInboxChannelApi.ts
  packages/runtime-tools-process-enveloped-components/src/taskInbox/envelope/components/TaskInbox/TaskInbox.tsx
  packages/runtime-tools-process-enveloped-components/src/taskInbox/envelope/components/TaskInboxToolbar/TaskInboxToolbar.tsx
Labels: area:bpmn

#2713 NO-ISSUE: Fixed typo in incubator-kie-serverless-logic-web-tools-swf-dev-mode image name
  packages/serverless-logic-web-tools-swf-dev-mode-image-env/env/index.js
Labels: area:sonataflow

#2685 kie-issues#1549: kn-workflow-plugin check for the presence of an image in the local Docker image does not cover all cases
  packages/kn-plugin-workflow/go.mod
  packages/kn-plugin-workflow/go.sum
  packages/kn-plugin-workflow/pkg/common/containers.go
  packages/kn-plugin-workflow/pkg/common/containers_test.go
Labels: area:sonataflow

#2684 kie-issues#2549: Decision Service cannot be recognized in columns of decision table
  packages/dmn-feel-antlr4-parser/src/parser/VariablesRepository.ts
  packages/feel-input-component/package.json
  packages/feel-input-component/tests-data/variables-inside-decision-tables/included.dmn
  packages/feel-input-component/tests-data/variables-inside-decision-tables/modelWithInclude.dmn
  packages/feel-input-component/tests/semanticTokensProvider.test.ts
  pnpm-lock.yaml
Labels: pr: waiting-for-review, area:dmn

#2717 NO-ISSUE: Upgrade `path-to-regexp@1.8.0` to `1.9.0`
  pnpm-lock.yaml
Labels: area:dependencies

#2719 NO-ISSUE: fix sonataflow management console ocp permission denied
  packages/sonataflow-management-console-image/resources/modules/sonataflow/management-console/configure-httpd.sh
Labels: area:sonataflow
