Repository apache/incubator-kie-tools, pull requests merged in 2024-09, with the labels that each got.

#2555 NO-ISSUE: Update screenshots for failing tests
  .github/supporting-files/ci/patterns/non-source-files-patterns.txt
  packages/online-editor/tests-e2e/__screenshots__/Google-Chrome/createFiles/new-file-dmn.png
  packages/scesim-editor/tests-e2e/__screenshots__/Google-Chrome/features/keyboard/navigation-down.png
  packages/scesim-editor/tests-e2e/__screenshots__/Google-Chrome/features/keyboard/navigation-escaped.png
  packages/scesim-editor/tests-e2e/__screenshots__/Google-Chrome/features/keyboard/navigation-left.png
  packages/scesim-editor/tests-e2e/__screenshots__/Google-Chrome/features/keyboard/navigation-right.png
  packages/scesim-editor/tests-e2e/__screenshots__/Google-Chrome/features/keyboard/navigation-up.png
  packages/scesim-editor/tests-e2e/__screenshots__/Google-Chrome/misc/emptyExpression/create-a-new-test-scenario.png
  packages/scesim-editor/tests-e2e/__screenshots__/Google-Chrome/misc/emptyExpression/empty-background-table.png
  packages/scesim-editor/tests-e2e/__screenshots__/Google-Chrome/misc/emptyExpression/empty-test-scenario-table.png
  packages/scesim-editor/tests-e2e/__screenshots__/Google-Chrome/scesimEditor/backgroundTable/background-table-add-instance-column-left.png
  packages/scesim-editor/tests-e2e/__screenshots__/Google-Chrome/scesimEditor/backgroundTable/background-table-add-instance-column-right.png
  packages/scesim-editor/tests-e2e/__screenshots__/Google-Chrome/scesimEditor/backgroundTable/background-table-add-property-column-left.png
  packages/scesim-editor/tests-e2e/__screenshots__/Google-Chrome/scesimEditor/backgroundTable/background-table-add-property-column-right.png
  packages/scesim-editor/tests-e2e/__screenshots__/Google-Chrome/scesimEditor/backgroundTable/background-table-decision.png
  packages/scesim-editor/tests-e2e/__screenshots__/Google-Chrome/scesimEditor/backgroundTable/background-table-rule.png
  packages/scesim-editor/tests-e2e/__screenshots__/Google-Chrome/scesimEditor/backgroundTable/background-table-traffic-violation-headers.png
  packages/scesim-editor/tests-e2e/__screenshots__/Google-Chrome/scesimEditor/testScenarioTable/test-scenario-table-add-instance-column-left.png
  packages/scesim-editor/tests-e2e/__screenshots__/Google-Chrome/scesimEditor/testScenarioTable/test-scenario-table-add-instance-column-right.png
  packages/scesim-editor/tests-e2e/__screenshots__/Google-Chrome/scesimEditor/testScenarioTable/test-scenario-table-add-property-column-left.png
  packages/scesim-editor/tests-e2e/__screenshots__/Google-Chrome/scesimEditor/testScenarioTable/test-scenario-table-add-property-column-right.png
  packages/scesim-editor/tests-e2e/__screenshots__/Google-Chrome/scesimEditor/testScenarioTable/test-scenario-table-decision.png
  packages/scesim-editor/tests-e2e/__screenshots__/Google-Chrome/scesimEditor/testScenarioTable/test-scenario-table-rule.png
  packages/scesim-editor/tests-e2e/__screenshots__/Google-Chrome/useCases/are-they-old-enough-test.png
Labels: area:monorepo, area:tests

#2553 NO-ISSUE: Extended services wizard refer to non existing binaries
  packages/online-editor/src/extendedServices/ExtendedServicesModal.tsx
  packages/online-editor/src/i18n/locales/de.ts
  packages/online-editor/src/i18n/locales/en.ts
Labels: pr: waiting-for-review, area:core

#2558 NO-ISSUE: Fix Helm Charts template notes
  packages/kie-sandbox-helm-chart/src/templates/NOTES.txt
  packages/runtime-tools-consoles-helm-chart/src/templates/NOTES.txt
Labels: area:monorepo

#2557 NO-ISSUE: Use correct properties on jbpm-compact-architecture-example
  examples/jbpm-compact-architecture-example/src/main/resources/application.properties
Labels: area:bpmn

#2465 kie-issues#1362: Migrate kn-workflow-plugin to kubernetes/client-go
  packages/kn-plugin-workflow/go.mod
  packages/kn-plugin-workflow/pkg/command/deploy.go
  packages/kn-plugin-workflow/pkg/command/deploy_undeploy_common.go
  packages/kn-plugin-workflow/pkg/command/gen_manifest.go
  packages/kn-plugin-workflow/pkg/command/quarkus/deploy.go
  packages/kn-plugin-workflow/pkg/command/quarkus/deploy_test.go
  packages/kn-plugin-workflow/pkg/command/quarkus/testdata/knative.yml
  packages/kn-plugin-workflow/pkg/command/quarkus/testdata/kogito-complex-custom-namespace.yml
  packages/kn-plugin-workflow/pkg/command/quarkus/testdata/kogito-complex.yml
  packages/kn-plugin-workflow/pkg/command/quarkus/testdata/kogito-complex2-custom-namespace.yml
  packages/kn-plugin-workflow/pkg/command/quarkus/testdata/kogito-complex2.yml
  packages/kn-plugin-workflow/pkg/command/quarkus/testdata/kogito-complex3-custom-namespace.yml
  packages/kn-plugin-workflow/pkg/command/quarkus/testdata/kogito-complex3.yml
  packages/kn-plugin-workflow/pkg/command/quarkus/testdata/kogito-default-custom-namespace.yml
  packages/kn-plugin-workflow/pkg/command/quarkus/testdata/kogito-default.yml
  packages/kn-plugin-workflow/pkg/command/undeploy.go
  packages/kn-plugin-workflow/pkg/common/exec.go
  packages/kn-plugin-workflow/pkg/common/k8sclient/fake.go
  packages/kn-plugin-workflow/pkg/common/k8sclient/goapi.go
  packages/kn-plugin-workflow/pkg/common/kubectl.go
  packages/kn-plugin-workflow/pkg/common/operator.go
  packages/kn-plugin-workflow/pkg/common/test_helper.go
  packages/kn-plugin-workflow/pkg/metadata/constants.go
Labels: area:sonataflow

#2560 [10.0.x] NO-ISSUE: Update screenshots for failing tests
  .github/supporting-files/ci/patterns/non-source-files-patterns.txt
  packages/online-editor/tests-e2e/__screenshots__/Google-Chrome/createFiles/new-file-dmn.png
  packages/scesim-editor/tests-e2e/__screenshots__/Google-Chrome/features/keyboard/navigation-down.png
  packages/scesim-editor/tests-e2e/__screenshots__/Google-Chrome/features/keyboard/navigation-escaped.png
  packages/scesim-editor/tests-e2e/__screenshots__/Google-Chrome/features/keyboard/navigation-left.png
  packages/scesim-editor/tests-e2e/__screenshots__/Google-Chrome/features/keyboard/navigation-right.png
  packages/scesim-editor/tests-e2e/__screenshots__/Google-Chrome/features/keyboard/navigation-up.png
  packages/scesim-editor/tests-e2e/__screenshots__/Google-Chrome/misc/emptyExpression/create-a-new-test-scenario.png
  packages/scesim-editor/tests-e2e/__screenshots__/Google-Chrome/misc/emptyExpression/empty-background-table.png
  packages/scesim-editor/tests-e2e/__screenshots__/Google-Chrome/misc/emptyExpression/empty-test-scenario-table.png
  packages/scesim-editor/tests-e2e/__screenshots__/Google-Chrome/scesimEditor/backgroundTable/background-table-add-instance-column-left.png
  packages/scesim-editor/tests-e2e/__screenshots__/Google-Chrome/scesimEditor/backgroundTable/background-table-add-instance-column-right.png
  packages/scesim-editor/tests-e2e/__screenshots__/Google-Chrome/scesimEditor/backgroundTable/background-table-add-property-column-left.png
  packages/scesim-editor/tests-e2e/__screenshots__/Google-Chrome/scesimEditor/backgroundTable/background-table-add-property-column-right.png
  packages/scesim-editor/tests-e2e/__screenshots__/Google-Chrome/scesimEditor/backgroundTable/background-table-decision.png
  packages/scesim-editor/tests-e2e/__screenshots__/Google-Chrome/scesimEditor/backgroundTable/background-table-rule.png
  packages/scesim-editor/tests-e2e/__screenshots__/Google-Chrome/scesimEditor/backgroundTable/background-table-traffic-violation-headers.png
  packages/scesim-editor/tests-e2e/__screenshots__/Google-Chrome/scesimEditor/testScenarioTable/test-scenario-table-add-instance-column-left.png
  packages/scesim-editor/tests-e2e/__screenshots__/Google-Chrome/scesimEditor/testScenarioTable/test-scenario-table-add-instance-column-right.png
  packages/scesim-editor/tests-e2e/__screenshots__/Google-Chrome/scesimEditor/testScenarioTable/test-scenario-table-add-property-column-left.png
  packages/scesim-editor/tests-e2e/__screenshots__/Google-Chrome/scesimEditor/testScenarioTable/test-scenario-table-add-property-column-right.png
  packages/scesim-editor/tests-e2e/__screenshots__/Google-Chrome/scesimEditor/testScenarioTable/test-scenario-table-decision.png
  packages/scesim-editor/tests-e2e/__screenshots__/Google-Chrome/scesimEditor/testScenarioTable/test-scenario-table-rule.png
  packages/scesim-editor/tests-e2e/__screenshots__/Google-Chrome/useCases/are-they-old-enough-test.png
Labels: pr: cherry-pick 🍒, area:monorepo, area:tests

#2556 [10.0.x] NO-ISSUE: Release jobs adjustments for the Apache 10 release
  .ci/jenkins/Jenkinsfile.daily-dev-publish
  .ci/jenkins/Jenkinsfile.weekly-publish
  .ci/jenkins/release-jobs/Jenkinsfile.jbpm-quarkus-devui
  .ci/jenkins/release-jobs/Jenkinsfile.sonataflow-quarkus-devui
  .ci/jenkins/shared-scripts/pipelineVars.groovy
  .ci/jenkins/shared-scripts/releaseUtils.groovy
  .github/workflows/release_build_extended_services.yml
Labels: area:cicd

#2565 NO-ISSUE: Upgrade lima and colima for GH Actions
  .github/actions/setup-env/action.yml
Labels: area:monorepo, area:cicd

#2566 kie-tools-issues#2567: sonataflow-management-console-webapp topbar restyle
  packages/runtime-tools-components/src/common/components/PageToolbar/PageToolbar.tsx
  packages/sonataflow-management-console-webapp/package.json
  packages/sonataflow-management-console-webapp/src/components/console/ManagementConsole/ManagementConsole.tsx
  packages/sonataflow-management-console-webapp/src/components/pages/BasePage.tsx
  packages/sonataflow-management-console-webapp/src/components/styles.css
  packages/sonataflow-management-console-webapp/src/index.html
  packages/sonataflow-management-console-webapp/src/static/favicon.svg
  packages/sonataflow-management-console-webapp/webpack.config.ts
  pnpm-lock.yaml
Labels: area:sonataflow

#2559 kie-issues#1365: Revisit all React-dependent packages on `kie-tools` declaring `react` as a `dependency` instead of a `peerDependency`
  .github/workflows/ci_check_dependencies_consistency.yaml
  .syncpackrc.json
  examples/base64png-editor/package.json
  examples/ping-pong-view-react/package.json
  examples/ping-pong-view/package.json
  examples/todo-list-view/package.json
  packages/boxed-expression-component/package.json
  packages/chrome-extension/package.json
  packages/dashbuilder-component-api/package.json
  packages/dashbuilder-component-echarts-base/package.json
  packages/dashbuilder-component-echarts/package.json
  packages/dashbuilder-component-map/package.json
  packages/dashbuilder-component-svg-heatmap/package.json
  packages/dashbuilder-component-table/package.json
  packages/dashbuilder-component-timeseries/package.json
  packages/dashbuilder-component-uniforms/package.json
  packages/dashbuilder-component-victory-charts/package.json
  packages/dashbuilder-editor/package.json
  packages/dashbuilder-viewer/package.json
  packages/dev-deployment-dmn-form-webapp/package.json
  packages/dmn-editor-envelope/package.json
  packages/dmn-editor/package.json
  packages/dmn-runner/package.json
  packages/editor/package.json
  packages/envelope-bus/package.json
  packages/envelope/package.json
  packages/feel-input-component/package.json
  packages/form-dmn/package.json
  packages/form/package.json
  packages/i18n/package.json
  packages/import-java-classes-component/package.json
  packages/keyboard-shortcuts/package.json
  packages/kie-bc-editors/package.json
  packages/pmml-editor/package.json
  packages/react-hooks/package.json
  packages/runtime-tools-components/package.json
  packages/runtime-tools-process-enveloped-components/package.json
  packages/runtime-tools-process-webapp-components/package.json
  packages/runtime-tools-shared-enveloped-components/package.json
  packages/runtime-tools-shared-webapp-components/package.json
  packages/runtime-tools-swf-enveloped-components/package.json
  packages/runtime-tools-swf-webapp-components/package.json
  packages/serverless-workflow-combined-editor/package.json
  packages/serverless-workflow-text-editor/package.json
  packages/text-editor/package.json
  packages/uniforms-bootstrap4-codegen/package.json
  packages/uniforms-patternfly-codegen/package.json
  packages/uniforms-patternfly/package.json
  packages/unitables-dmn/package.json
  packages/unitables/package.json
  packages/workspaces-git-fs/package.json
  packages/yard-editor/package.json
  pnpm-lock.yaml
Labels: area:dependencies, area:monorepo

#2570 [10.0.x] NO-ISSUE: Upgrade lima and colima for GH Actions (#2565)
  .github/actions/setup-env/action.yml
Labels: pr: cherry-pick 🍒, area:monorepo, area:cicd

#2576 kie-issues#1475: Classic Standalone Editors TypeScript errors for `resources` property
  packages/chrome-extension/src/app/components/common/ChromeResourceContentService.ts
  packages/chrome-extension/src/app/github/api.ts
  packages/dmn-editor-envelope/src/DmnEditorRoot.tsx
  packages/dmn-editor-standalone/src/DmnEditorStandaloneChannelApiImpl.ts
  packages/dmn-editor-standalone/stories/DevWebApp.stories.tsx
  packages/dmn-editor-standalone/tests-e2e/__fixtures__/editor.ts
  packages/dmn-editor-standalone/tests-e2e/includedModels/includedModels.spec.ts
  packages/kie-editors-standalone/e2e-tests/src/App.tsx
  packages/kie-editors-standalone/e2e-tests/src/components/EditorComponent.tsx
  packages/kie-editors-standalone/e2e-tests/src/components/FileLoader.tsx
  packages/kie-editors-standalone/src/bpmn/index.ts
  packages/kie-editors-standalone/src/common/Editor.ts
  packages/kie-editors-standalone/src/dmn/index.ts
  packages/kie-editors-standalone/src/envelope/StandaloneEditorsEditorChannelApiImpl.ts
  packages/vscode-extension/src/workspace/VsCodeResourceContentServiceForDanglingFiles.ts
  packages/vscode-extension/src/workspace/VsCodeResourceContentServiceForWorkspaces.ts
  packages/vscode-extension/tests/VsCodeResourceContentServiceForDanglingFiles.test.ts
  packages/workspace/src/api/ContentType.ts
  packages/workspace/src/api/ResourceContent.ts
  packages/workspaces-git-fs/src/worker/WorkspacesWorkerApiImpl.ts
Labels: area:bpmn, area:dmn

#2577 NO-ISSUE: Increase daily-dev Jenkins job timeout
  .ci/jenkins/Jenkinsfile.daily-dev-publish
Labels: area:monorepo, area:cicd

#2572 [10.0.x] NO-ISSUE: Fix Dashbuilder javadocs
  packages/dashbuilder/appformer/uberfire-api/src/main/java/org/uberfire/debug/Debug.java
  packages/dashbuilder/appformer/uberfire-api/src/main/java/org/uberfire/mvp/PlaceRequest.java
  packages/dashbuilder/appformer/uberfire-api/src/main/java/org/uberfire/workbench/model/CustomPanelDefinition.java
  packages/dashbuilder/appformer/uberfire-api/src/main/java/org/uberfire/workbench/model/PanelDefinition.java
  packages/dashbuilder/appformer/uberfire-api/src/main/java/org/uberfire/workbench/model/PartDefinition.java
  packages/dashbuilder/appformer/uberfire-client-api/src/main/java/org/uberfire/client/annotations/WorkbenchPanel.java
  packages/dashbuilder/appformer/uberfire-client-api/src/main/java/org/uberfire/client/annotations/WorkbenchPerspective.java
  packages/dashbuilder/appformer/uberfire-client-api/src/main/java/org/uberfire/client/annotations/WorkbenchPopup.java
  packages/dashbuilder/appformer/uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/common/popups/BaseModal.java
  packages/dashbuilder/appformer/uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/tables/TitledTextCell.java
  packages/dashbuilder/appformer/uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/tab/TabPanelWithDropdowns.java
  packages/dashbuilder/appformer/uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/AbstractActivity.java
  packages/dashbuilder/appformer/uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/Activity.java
  packages/dashbuilder/appformer/uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/ActivityManager.java
  packages/dashbuilder/appformer/uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/PerspectiveManager.java
  packages/dashbuilder/appformer/uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/PlaceManager.java
  packages/dashbuilder/appformer/uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/PlaceManagerImpl.java
  packages/dashbuilder/appformer/uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/AlternativeLayout.java
  packages/dashbuilder/appformer/uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/BeanFactory.java
  packages/dashbuilder/appformer/uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/PanelManager.java
  packages/dashbuilder/appformer/uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/WorkbenchLayout.java
  packages/dashbuilder/appformer/uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/widgets/listbar/ResizeFlowPanel.java
  packages/dashbuilder/appformer/uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/widgets/listbar/ResizeFocusPanel.java
  packages/dashbuilder/appformer/uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/widgets/split/WorkbenchSplitLayoutPanel.java
  packages/dashbuilder/appformer/uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/workbench/PanelManagerTest.java
  packages/dashbuilder/appformer/uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/workbench/panels/impl/PlaceManagerTest.java
  packages/dashbuilder/appformer/uberfire-workbench/uberfire-workbench-processors/src/main/java/org/uberfire/annotations/processors/GeneratorUtils.java
  packages/dashbuilder/dashbuilder-client/dashbuilder-dataset-client/src/main/java/org/dashbuilder/dataset/client/DataSetClientServices.java
  packages/dashbuilder/dashbuilder-client/dashbuilder-dataset-client/src/main/java/org/dashbuilder/dataset/client/DataSetClientServicesImpl.java
  packages/dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/AbstractDisplayer.java
  packages/dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/Displayer.java
  packages/dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/RendererLibrary.java
  packages/dashbuilder/dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-default/src/main/java/org/dashbuilder/renderer/client/table/TableDisplayerView.java
  packages/dashbuilder/dashbuilder-shared/dashbuilder-displayer-api/src/main/java/org/dashbuilder/displayer/DisplayerSettingsBuilder.java
  packages/dashbuilder/kie-soup-dataset/kie-soup-dataset-api/src/main/java/org/dashbuilder/dataprovider/DataSetProvider.java
  packages/dashbuilder/kie-soup-dataset/kie-soup-dataset-api/src/main/java/org/dashbuilder/dataset/DataColumn.java
  packages/dashbuilder/kie-soup-dataset/kie-soup-dataset-api/src/main/java/org/dashbuilder/dataset/DataSetGenerator.java
  packages/dashbuilder/kie-soup-dataset/kie-soup-dataset-api/src/main/java/org/dashbuilder/dataset/date/TimeAmount.java
  packages/dashbuilder/kie-soup-dataset/kie-soup-dataset-api/src/main/java/org/dashbuilder/dataset/date/TimeFrame.java
  packages/dashbuilder/kie-soup-dataset/kie-soup-dataset-api/src/main/java/org/dashbuilder/dataset/date/TimeInstant.java
  packages/dashbuilder/kie-soup-dataset/kie-soup-dataset-core/src/main/java/org/dashbuilder/dataprovider/StaticDataSetProvider.java
  packages/dashbuilder/kie-soup-dataset/kie-soup-dataset-shared/src/main/java/org/dashbuilder/dataset/engine/Chronometer.java
  packages/dashbuilder/kie-soup-dataset/kie-soup-dataset-shared/src/main/java/org/dashbuilder/dataset/engine/group/IntervalBuilderFixedDate.java
  packages/dashbuilder/kie-soup-dataset/kie-soup-dataset-shared/src/main/java/org/dashbuilder/dataset/engine/index/spi/DataSetIndexRegistry.java
  packages/dashbuilder/kie-soup-dataset/kie-soup-dataset-shared/src/main/java/org/dashbuilder/dataset/engine/sort/CollectionsDataSetSort.java
  packages/stunner-editors/uberfire-api/src/main/java/org/uberfire/mvp/PlaceRequest.java
Labels: area:dashbuilder, area:cicd

#2581 NO-ISSUE: Fix Dashbuilder javadocs
  packages/dashbuilder/appformer/uberfire-api/src/main/java/org/uberfire/debug/Debug.java
  packages/dashbuilder/appformer/uberfire-api/src/main/java/org/uberfire/mvp/PlaceRequest.java
  packages/dashbuilder/appformer/uberfire-api/src/main/java/org/uberfire/workbench/model/CustomPanelDefinition.java
  packages/dashbuilder/appformer/uberfire-api/src/main/java/org/uberfire/workbench/model/PanelDefinition.java
  packages/dashbuilder/appformer/uberfire-api/src/main/java/org/uberfire/workbench/model/PartDefinition.java
  packages/dashbuilder/appformer/uberfire-client-api/src/main/java/org/uberfire/client/annotations/WorkbenchPanel.java
  packages/dashbuilder/appformer/uberfire-client-api/src/main/java/org/uberfire/client/annotations/WorkbenchPerspective.java
  packages/dashbuilder/appformer/uberfire-client-api/src/main/java/org/uberfire/client/annotations/WorkbenchPopup.java
  packages/dashbuilder/appformer/uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/common/popups/BaseModal.java
  packages/dashbuilder/appformer/uberfire-extensions/uberfire-widgets/uberfire-widgets-commons/src/main/java/org/uberfire/ext/widgets/common/client/tables/TitledTextCell.java
  packages/dashbuilder/appformer/uberfire-workbench/uberfire-workbench-client-views-patternfly/src/main/java/org/uberfire/client/views/pfly/tab/TabPanelWithDropdowns.java
  packages/dashbuilder/appformer/uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/AbstractActivity.java
  packages/dashbuilder/appformer/uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/Activity.java
  packages/dashbuilder/appformer/uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/ActivityManager.java
  packages/dashbuilder/appformer/uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/PerspectiveManager.java
  packages/dashbuilder/appformer/uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/PlaceManager.java
  packages/dashbuilder/appformer/uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/mvp/PlaceManagerImpl.java
  packages/dashbuilder/appformer/uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/AlternativeLayout.java
  packages/dashbuilder/appformer/uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/BeanFactory.java
  packages/dashbuilder/appformer/uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/PanelManager.java
  packages/dashbuilder/appformer/uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/WorkbenchLayout.java
  packages/dashbuilder/appformer/uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/widgets/listbar/ResizeFlowPanel.java
  packages/dashbuilder/appformer/uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/widgets/listbar/ResizeFocusPanel.java
  packages/dashbuilder/appformer/uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/widgets/split/WorkbenchSplitLayoutPanel.java
  packages/dashbuilder/appformer/uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/workbench/PanelManagerTest.java
  packages/dashbuilder/appformer/uberfire-workbench/uberfire-workbench-client/src/test/java/org/uberfire/client/workbench/panels/impl/PlaceManagerTest.java
  packages/dashbuilder/appformer/uberfire-workbench/uberfire-workbench-processors/src/main/java/org/uberfire/annotations/processors/GeneratorUtils.java
  packages/dashbuilder/dashbuilder-client/dashbuilder-dataset-client/src/main/java/org/dashbuilder/dataset/client/DataSetClientServices.java
  packages/dashbuilder/dashbuilder-client/dashbuilder-dataset-client/src/main/java/org/dashbuilder/dataset/client/DataSetClientServicesImpl.java
  packages/dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/AbstractDisplayer.java
  packages/dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/Displayer.java
  packages/dashbuilder/dashbuilder-client/dashbuilder-displayer-client/src/main/java/org/dashbuilder/displayer/client/RendererLibrary.java
  packages/dashbuilder/dashbuilder-client/dashbuilder-renderers/dashbuilder-renderer-default/src/main/java/org/dashbuilder/renderer/client/table/TableDisplayerView.java
  packages/dashbuilder/dashbuilder-shared/dashbuilder-displayer-api/src/main/java/org/dashbuilder/displayer/DisplayerSettingsBuilder.java
  packages/dashbuilder/kie-soup-dataset/kie-soup-dataset-api/src/main/java/org/dashbuilder/dataprovider/DataSetProvider.java
  packages/dashbuilder/kie-soup-dataset/kie-soup-dataset-api/src/main/java/org/dashbuilder/dataset/DataColumn.java
  packages/dashbuilder/kie-soup-dataset/kie-soup-dataset-api/src/main/java/org/dashbuilder/dataset/DataSetGenerator.java
  packages/dashbuilder/kie-soup-dataset/kie-soup-dataset-api/src/main/java/org/dashbuilder/dataset/date/TimeAmount.java
  packages/dashbuilder/kie-soup-dataset/kie-soup-dataset-api/src/main/java/org/dashbuilder/dataset/date/TimeFrame.java
  packages/dashbuilder/kie-soup-dataset/kie-soup-dataset-api/src/main/java/org/dashbuilder/dataset/date/TimeInstant.java
  packages/dashbuilder/kie-soup-dataset/kie-soup-dataset-core/src/main/java/org/dashbuilder/dataprovider/StaticDataSetProvider.java
  packages/dashbuilder/kie-soup-dataset/kie-soup-dataset-shared/src/main/java/org/dashbuilder/dataset/engine/Chronometer.java
  packages/dashbuilder/kie-soup-dataset/kie-soup-dataset-shared/src/main/java/org/dashbuilder/dataset/engine/group/IntervalBuilderFixedDate.java
  packages/dashbuilder/kie-soup-dataset/kie-soup-dataset-shared/src/main/java/org/dashbuilder/dataset/engine/index/spi/DataSetIndexRegistry.java
  packages/dashbuilder/kie-soup-dataset/kie-soup-dataset-shared/src/main/java/org/dashbuilder/dataset/engine/sort/CollectionsDataSetSort.java
  packages/stunner-editors/uberfire-api/src/main/java/org/uberfire/mvp/PlaceRequest.java
Labels: area:dashbuilder

#2579 NO-ISSUE: upgrade body-parser to version 1.20.3 (fixes CVE-2024-45590)
  packages/runtime-tools-management-console-webapp/package.json
  packages/runtime-tools-process-dev-ui-webapp/package.json
  packages/sonataflow-dev-app/package.json
  pnpm-lock.yaml
Labels: area:dependencies

#2580 NO-ISSUE: upgrade express to version 4.21.0 (fixes CVE-2024-43796)
  packages/cors-proxy/package.json
  packages/runtime-tools-management-console-webapp/package.json
  packages/runtime-tools-process-dev-ui-webapp/package.json
  packages/runtime-tools-task-console-webapp/package.json
  packages/sonataflow-dev-app/package.json
  pnpm-lock.yaml
Labels: area:dependencies

#2574 NO-ISSUE: Use `image-builder` and `maven-m2-repo-via-http-image` to build `serverless-logic-web-tools-swf-dev-mode-image`
  packages/serverless-logic-web-tools-swf-dev-mode-image/Containerfile
  packages/serverless-logic-web-tools-swf-dev-mode-image/entrypoint.sh
  packages/serverless-logic-web-tools-swf-dev-mode-image/env/index.js
  packages/serverless-logic-web-tools-swf-dev-mode-image/package.json
  packages/serverless-logic-web-tools-swf-dev-mode-image/pom.xml
  packages/serverless-logic-web-tools/src/openshift/pipelines/SpinUpDevModePipeline.ts
  pnpm-lock.yaml
  repo/graph.dot
  repo/graph.json
Labels: area:sonataflow, area:monorepo

#2575 [10.0.x] NO-ISSUE: Use `image-builder` and `maven-m2-repo-via-http-image` to build `serverless-logic-web-tools-swf-dev-mode-image`
  packages/serverless-logic-web-tools-swf-dev-mode-image/Containerfile
  packages/serverless-logic-web-tools-swf-dev-mode-image/entrypoint.sh
  packages/serverless-logic-web-tools-swf-dev-mode-image/env/index.js
  packages/serverless-logic-web-tools-swf-dev-mode-image/package.json
  packages/serverless-logic-web-tools-swf-dev-mode-image/pom.xml
  packages/serverless-logic-web-tools/src/openshift/pipelines/SpinUpDevModePipeline.ts
  pnpm-lock.yaml
  repo/graph.dot
  repo/graph.json
Labels: area:sonataflow, area:monorepo

#2592 kie-issues#2545: Create a landing page for the Jobs Service
  packages/jobs-service-webapp/env/index.js
  packages/jobs-service-webapp/package.json
  packages/jobs-service-webapp/src/index.html
  packages/jobs-service-webapp/src/styles.css
  packages/jobs-service-webapp/static/favicon.svg
  packages/jobs-service-webapp/webpack.config.js
  pnpm-lock.yaml
  repo/graph.dot
  repo/graph.json
Labels: area:sonataflow

#2597 NO-ISSUE: Release job updates and fixes for Apache 10 release
  .ci/jenkins/Jenkinsfile.daily-dev-publish
  .ci/jenkins/Jenkinsfile.release-build
  .ci/jenkins/Jenkinsfile.release-candidate
  .ci/jenkins/Jenkinsfile.release-candidate.quarkus-accelerator
  .ci/jenkins/Jenkinsfile.release-dry-run
  .ci/jenkins/Jenkinsfile.release-publish
  .ci/jenkins/Jenkinsfile.weekly-publish
  .ci/jenkins/release-jobs/Jenkinsfile.chrome-extensions
  .ci/jenkins/release-jobs/Jenkinsfile.cors-proxy
  .ci/jenkins/release-jobs/Jenkinsfile.dashbuilder-viewer-image
  .ci/jenkins/release-jobs/Jenkinsfile.dev-deployment-base-image
  .ci/jenkins/release-jobs/Jenkinsfile.dev-deployment-dmn-form-webapp-image
  .ci/jenkins/release-jobs/Jenkinsfile.dev-deployment-kogito-quarkus-blank-app-image
  .ci/jenkins/release-jobs/Jenkinsfile.dev-deployment-upload-service
  .ci/jenkins/release-jobs/Jenkinsfile.extended-services
  .ci/jenkins/release-jobs/Jenkinsfile.jbpm-quarkus-devui
  .ci/jenkins/release-jobs/Jenkinsfile.kie-sandbox
  .ci/jenkins/release-jobs/Jenkinsfile.kie-sandbox-extended-services
  .ci/jenkins/release-jobs/Jenkinsfile.kie-sandbox-helm-chart
  .ci/jenkins/release-jobs/Jenkinsfile.kn-plugin-workflow
  .ci/jenkins/release-jobs/Jenkinsfile.kogito-management-console
  .ci/jenkins/release-jobs/Jenkinsfile.kogito-serverless-operator
  .ci/jenkins/release-jobs/Jenkinsfile.kogito-swf-builder
  .ci/jenkins/release-jobs/Jenkinsfile.kogito-swf-devmode
  .ci/jenkins/release-jobs/Jenkinsfile.kogito-task-console
  .ci/jenkins/release-jobs/Jenkinsfile.npm-packages
  .ci/jenkins/release-jobs/Jenkinsfile.online-editor
  .ci/jenkins/release-jobs/Jenkinsfile.runtime-tools-consoles-helm-chart
  .ci/jenkins/release-jobs/Jenkinsfile.serverless-logic-web-tools
  .ci/jenkins/release-jobs/Jenkinsfile.serverless-logic-web-tools-base-builder-image
  .ci/jenkins/release-jobs/Jenkinsfile.serverless-logic-web-tools-swf-builder-image
  .ci/jenkins/release-jobs/Jenkinsfile.serverless-logic-web-tools-swf-dev-mode-image
  .ci/jenkins/release-jobs/Jenkinsfile.sonataflow-quarkus-devui
  .ci/jenkins/release-jobs/Jenkinsfile.standalone-editors-cdn
  .ci/jenkins/release-jobs/Jenkinsfile.vscode-extensions-dev
  .ci/jenkins/release-jobs/Jenkinsfile.vscode-extensions-prod
  .ci/jenkins/shared-scripts/buildUtils.groovy
  .ci/jenkins/shared-scripts/dockerUtils.groovy
  .ci/jenkins/shared-scripts/pipelineVars.groovy
  .ci/jenkins/shared-scripts/releaseUtils.groovy
  .github/workflows/release_dry_run_extended_services.yml
  .github/workflows/release_publish_extended_services.yml
Labels: area:monorepo, area:cicd

#2606 kie-tools-issues#2584: Make `private` members to be `protected` for `DefaultVsCodeKieEditorChannelApiImpl`
  packages/vscode-extension/src/DefaultVsCodeKieEditorChannelApiImpl.ts
Labels: area:core

#2598 kie-issues#980: On the DMN Editor it's not possible to use the Palette if the focus is on another element
  packages/dmn-editor/src/diagram/Palette.tsx
  packages/dmn-editor/tests-e2e/__screenshots__/Google-Chrome/drdArtifacts/add-2-group-nodes-from-palette.png
  packages/dmn-editor/tests-e2e/__screenshots__/Google-Chrome/drdArtifacts/add-2-text-annotation-nodes-from-palette.png
  packages/dmn-editor/tests-e2e/__screenshots__/Google-Chrome/drgElements/add-2-bkm-nodes-from-palette.png
  packages/dmn-editor/tests-e2e/__screenshots__/Google-Chrome/drgElements/add-2-decision-nodes-from-palette.png
  packages/dmn-editor/tests-e2e/__screenshots__/Google-Chrome/drgElements/add-2-decision-service-nodes-from-palette.png
  packages/dmn-editor/tests-e2e/__screenshots__/Google-Chrome/drgElements/add-2-input-data-nodes-from-palette.png
  packages/dmn-editor/tests-e2e/__screenshots__/Google-Chrome/drgElements/add-2-knowledge-source-nodes-from-palette.png
  packages/dmn-editor/tests-e2e/__screenshots__/chromium/drdArtifacts/add-2-group-nodes-from-palette.png
  packages/dmn-editor/tests-e2e/__screenshots__/chromium/drdArtifacts/add-2-text-annotation-nodes-from-palette.png
  packages/dmn-editor/tests-e2e/__screenshots__/chromium/drgElements/add-2-bkm-nodes-from-palette.png
  packages/dmn-editor/tests-e2e/__screenshots__/chromium/drgElements/add-2-decision-nodes-from-palette.png
  packages/dmn-editor/tests-e2e/__screenshots__/chromium/drgElements/add-2-decision-service-nodes-from-palette.png
  packages/dmn-editor/tests-e2e/__screenshots__/chromium/drgElements/add-2-input-data-nodes-from-palette.png
  packages/dmn-editor/tests-e2e/__screenshots__/chromium/drgElements/add-2-knowledge-source-nodes-from-palette.png
  packages/dmn-editor/tests-e2e/__screenshots__/webkit/drdArtifacts/add-2-group-nodes-from-palette.png
  packages/dmn-editor/tests-e2e/__screenshots__/webkit/drdArtifacts/add-2-text-annotation-nodes-from-palette.png
  packages/dmn-editor/tests-e2e/__screenshots__/webkit/drgElements/add-2-bkm-nodes-from-palette.png
  packages/dmn-editor/tests-e2e/__screenshots__/webkit/drgElements/add-2-decision-nodes-from-palette.png
  packages/dmn-editor/tests-e2e/__screenshots__/webkit/drgElements/add-2-decision-service-nodes-from-palette.png
  packages/dmn-editor/tests-e2e/__screenshots__/webkit/drgElements/add-2-input-data-nodes-from-palette.png
  packages/dmn-editor/tests-e2e/__screenshots__/webkit/drgElements/add-2-knowledge-source-nodes-from-palette.png
  packages/dmn-editor/tests-e2e/drdArtifacts/addAssociation.spec.ts
  packages/dmn-editor/tests-e2e/drdArtifacts/addGroup.spec.ts
  packages/dmn-editor/tests-e2e/drdArtifacts/addTextAnnotation.spec.ts
  packages/dmn-editor/tests-e2e/drdArtifacts/deleteAssociation.spec.ts
  packages/dmn-editor/tests-e2e/drgElements/addBkm.spec.ts
  packages/dmn-editor/tests-e2e/drgElements/addDecision.spec.ts
  packages/dmn-editor/tests-e2e/drgElements/addDecisionService.spec.ts
  packages/dmn-editor/tests-e2e/drgElements/addInputData.spec.ts
  packages/dmn-editor/tests-e2e/drgElements/addKnowledgeSource.spec.ts
  packages/dmn-editor/tests-e2e/drgRequirements/addAuthorityRequirement.spec.ts
  packages/dmn-editor/tests-e2e/drgRequirements/addInformationRequirement.spec.ts
  packages/dmn-editor/tests-e2e/drgRequirements/addKnowledgeRequirement.spec.ts
  packages/dmn-editor/tests-e2e/drgRequirements/deleteAuthorityRequirement.spec.ts
  packages/dmn-editor/tests-e2e/drgRequirements/deleteInformationRequirement.spec.ts
  packages/dmn-editor/tests-e2e/drgRequirements/deleteKnowledgeRequirement.spec.ts
  packages/dmn-editor/tests-e2e/drgRequirements/invalidAuthorityRequirement.spec.ts
  packages/dmn-editor/tests-e2e/drgRequirements/invalidInformationRequirement.spec.ts
  packages/dmn-editor/tests-e2e/drgRequirements/invalidKnowledgeRequirement.spec.ts
  packages/dmn-editor/tests-e2e/readOnly/readOnlyDiagram.spec.ts
Labels: area:dmn

#2595 kie-issues#2568: [sonataflow-management-console-webapp] Restyle 503 Keycloak page
  packages/runtime-tools-components/src/common/components/KeycloakUnavailablePage/KeycloakUnavailablePage.tsx
  packages/runtime-tools-components/src/common/static/kogito.png
  packages/runtime-tools-components/src/static/kogito.png
Labels: area:sonataflow

#2607 kie-issues#1488: Importing `drools-build-parent` in Jbang script to enforce usage of correct depencendies version
  packages/dmn-marshaller-backend-compatibility-tester/package.json
  packages/dmn-marshaller-backend-compatibility-tester/src/DmnMarshallerBackendCompatibilityTesterScript.java
  pnpm-lock.yaml
Labels: area:dmn, area:dependencies, area:cicd

#2609 NO-ISSUE: Bump `maven-surefire-plugin` from `3.2.5` to `3.5.0`
  packages/dev-deployment-dmn-form-webapp/dev-webapp/quarkus-app/pom.xml
  packages/dev-deployment-kogito-quarkus-blank-app/pom.xml
  packages/jbpm-quarkus-devui/dev/pom.xml
  packages/kn-plugin-workflow/pkg/command/quarkus/testdata/pom1-expected.xml_no_auto_formatting
  packages/kn-plugin-workflow/pkg/command/quarkus/testdata/pom1-input.xml_no_auto_formatting
  packages/maven-base/pom.xml
Labels: area:dependencies

#2610 NO-ISSUE: Moving `sonataflow-management-console-image` to partition1.txt
  .github/supporting-files/ci/partitions/partition1.txt
Labels: area:monorepo, area:cicd

#2615 NO-ISSUE: Enable "Create a merge commit" option
  .asf.yaml
Labels: area:monorepo

#2613 NO-ISSUE: Upgrade Kogito to `999-20240912-SNAPSHOT`
  packages/maven-base/pom.xml
  packages/root-env/env/index.js
  packages/sonataflow-operator/test/testdata/platform/noservices/preview/ephemeral/02-sonataflow_platform.yaml
  packages/sonataflow-operator/test/testdata/platform/services/dev/ephemeral/02-sonataflow_platform.yaml
  packages/sonataflow-operator/test/testdata/platform/services/dev/postgreSQL/02-sonataflow_platform.yaml
  packages/sonataflow-operator/test/testdata/platform/services/preview/cluster-wide-ephemeral/02-sonataflow_platform.yaml
  packages/sonataflow-operator/test/testdata/platform/services/preview/ephemeral-data-index/02-sonataflow_platform.yaml
  packages/sonataflow-operator/test/testdata/platform/services/preview/ephemeral-job-service/02-sonataflow_platform.yaml
  packages/sonataflow-operator/test/testdata/workflow/persistence/by_service/02-sonataflow_platform.yaml
  packages/sonataflow-operator/test/testdata/workflow/persistence/from_platform_overwritten_by_service/02-sonataflow_platform.yaml
  packages/sonataflow-operator/test/testdata/workflow/persistence/from_platform_with_di_and_js_services/02-sonataflow_platform.yaml
  packages/sonataflow-operator/test/testdata/workflow/persistence/from_platform_with_no_persistence_required/02-sonataflow_platform.yaml
  packages/sonataflow-operator/test/testdata/workflow/persistence/from_platform_without_di_and_js_services/02-sonataflow_platform.yaml
Labels: area:dependencies

#2616 [10.0.x] NO-ISSUE: Use maven-m2-repo-via-http to build sonataflow-builder/devmode-images
  devbox.lock
  packages/sonataflow-builder-image/env/index.js
  packages/sonataflow-builder-image/package.json
  packages/sonataflow-builder-image/resources/modules/sonataflow/builder/runtime/community/configure.sh
  packages/sonataflow-devmode-image/env/index.js
  packages/sonataflow-devmode-image/package.json
  packages/sonataflow-devmode-image/resources/modules/sonataflow/devmode/runtime/community/configure.sh
  packages/sonataflow-image-common/resources/Makefile
  packages/sonataflow-image-common/resources/modules/kogito-maven/common/maven/maven-m2-repo-via-http-settings.xml.envsubst
  packages/sonataflow-image-common/resources/modules/kogito-maven/common/module.yaml
  packages/sonataflow-image-common/resources/modules/sonataflow/common/build/configure.sh
  pnpm-lock.yaml
  repo/graph.dot
  repo/graph.json
Labels: area:monorepo

#2629 NO-ISSUE: Fix tests and test command of `sonataflow-image-common`
  .github/actions/setup-env/action.yml
  .github/supporting-files/ci/partitions/partition1.txt
  README.md
  devbox.json
  devbox.lock
  packages/sonataflow-image-common/package.json
  packages/sonataflow-image-common/resources/modules/kogito-maven/tests/bats/maven-settings.bats
  scripts/check-junit-report-results/tests/index.test.js
  scripts/check-junit-report-results/tests/reports/empty.xml
Labels: area:monorepo, area:cicd

#2617 NO-ISSUE: Use maven-m2-repo-via-http to build sonataflow-builder/devmode-images
  devbox.lock
  packages/sonataflow-builder-image/env/index.js
  packages/sonataflow-builder-image/package.json
  packages/sonataflow-builder-image/resources/modules/sonataflow/builder/runtime/community/configure.sh
  packages/sonataflow-devmode-image/env/index.js
  packages/sonataflow-devmode-image/package.json
  packages/sonataflow-devmode-image/resources/modules/sonataflow/devmode/runtime/community/configure.sh
  packages/sonataflow-image-common/resources/Makefile
  packages/sonataflow-image-common/resources/modules/kogito-maven/common/maven/maven-m2-repo-via-http-settings.xml.envsubst
  packages/sonataflow-image-common/resources/modules/kogito-maven/common/module.yaml
  packages/sonataflow-image-common/resources/modules/sonataflow/common/build/configure.sh
  pnpm-lock.yaml
  repo/graph.dot
  repo/graph.json
Labels: area:monorepo
