Repository apache/incubator-kie-tools, pull requests merged in 2024-12, with the labels that each got.

#2657 kie-issues#1527: DMN Editor: Create new overlay option 'Highlight evaluation results'
  packages/dmn-editor/src/DmnEditor.css
  packages/dmn-editor/src/boxedExpressions/BoxedExpressionScreen.tsx
  packages/dmn-editor/src/diagram/Diagram.tsx
  packages/dmn-editor/src/evaluationHighlights/EvaluationHighlightsBadge.tsx
  packages/dmn-editor/src/overlaysPanel/OverlaysPanel.tsx
  packages/dmn-editor/src/store/Store.ts
Labels: area:dmn, lang:typescript

#2808 NO-ISSUE: Disable AppArmor allowing unpriviledge user namespace to fix VS Code E2E tests
  .github/actions/setup-env/action.yml
Labels: area:cicd

#2810 kie-issues#1690: Apache KIE trademark character missing on Extended Services VS Code Extension's name
  packages/extended-services-java/pom.xml
  packages/extended-services-vscode-extension/package.json
  packages/extended-services-vscode-extension/src/Validator.ts
  packages/extended-services-vscode-extension/src/configurations/Configuration.ts
  packages/extended-services-vscode-extension/src/extension/extension-browser.ts
  packages/extended-services-vscode-extension/src/extension/extension-main.ts
Labels: area:bpmn, area:dmn

#2807 NO-ISSUE: Bump up `selenium-webdriver` to 4.27.0
  packages/chrome-extension-pack-kogito-kie-editors/package.json
  packages/chrome-extension-test-helper/package.json
  packages/serverless-workflow-vscode-extension/package.json
  packages/vscode-extension-common-test-helpers/package.json
  packages/vscode-extension-dashbuilder-editor/package.json
  packages/yard-vscode-extension/package.json
  pnpm-lock.yaml
Labels: area:dependencies, area:tests

#2809 kie-issues#1715: Chrome Extension `Serverless Workflow Editor for GitHub` rendering a 404 page instead of the SWF Editor
  .ci/jenkins/release-jobs/Jenkinsfile.chrome-extensions
Labels: area:sonataflow

#2811 kie-issues#1716: Serverless Workflow VS Code Extension should have `Apache KIE™` prefix instead of just `KIE` on its displayName
  packages/serverless-workflow-vscode-extension/package.json
Labels: area:sonataflow

#2798 kie-issues#1704: Change custom forms directory from `src/main/resources/forms` to `src/main/resources/custom-forms-dev`
  packages/form-code-generator-vscode-command/src/generateFormCodeCommand.ts
  packages/jbpm-quarkus-devui/jbpm-quarkus-devui-runtime/src/main/java/org/jbpm/quarkus/devui/runtime/forms/impl/FormsStorageImpl.java
  packages/jbpm-quarkus-devui/jbpm-quarkus-devui-runtime/src/test/java/org/jbpm/quarkus/devui/runtime/forms/impl/FormsStorageImplTest.java
  packages/jbpm-quarkus-devui/jbpm-quarkus-devui-runtime/src/test/resources/custom-forms-dev/hiring_HRInterview.config
  packages/jbpm-quarkus-devui/jbpm-quarkus-devui-runtime/src/test/resources/custom-forms-dev/hiring_HRInterview.html
  packages/jbpm-quarkus-devui/jbpm-quarkus-devui-runtime/src/test/resources/custom-forms-dev/hiring_HRInterviewWithoutConfig.html
  packages/jbpm-quarkus-devui/jbpm-quarkus-devui-runtime/src/test/resources/custom-forms-dev/hiring_ITInterview.config
  packages/jbpm-quarkus-devui/jbpm-quarkus-devui-runtime/src/test/resources/custom-forms-dev/hiring_ITInterview.html
  packages/runtime-tools-process-dev-ui-webapp/server/MockData/controllers.js
Labels: area:bpmn

#2681 kie-issues#1547: DMN Editor: Render evaluation highlights in the Boxed Expression Editor
  packages/boxed-expression-component/src/BoxedExpressionEditor.tsx
  packages/boxed-expression-component/src/BoxedExpressionEditorContext.tsx
  packages/boxed-expression-component/src/api/BeeTable.ts
  packages/boxed-expression-component/src/expressions/ConditionalExpression/ConditionalExpression.tsx
  packages/boxed-expression-component/src/expressions/DecisionTableExpression/DecisionTableExpression.tsx
  packages/boxed-expression-component/src/table/BeeTable/BeeTable.css
  packages/boxed-expression-component/src/table/BeeTable/BeeTable.tsx
  packages/boxed-expression-component/src/table/BeeTable/BeeTableBody.tsx
  packages/boxed-expression-component/src/table/BeeTable/BeeTableTd.tsx
  packages/boxed-expression-component/stories/boxedExpressionStoriesWrapper.tsx
  packages/boxed-expression-component/stories/boxedExpressions/Conditional/Conditional.stories.tsx
  packages/boxed-expression-component/stories/boxedExpressions/DecisionTable/DecisionTable.stories.tsx
Labels: area:dmn

#2794 kie-tools#2751: Remove references to Quarkus and Kogito versions; Automatic change of platform images based on env context
  packages/kogito-data-index-ephemeral-image/resources/incubator-kie-kogito-data-index-ephemeral-image.yaml
  packages/kogito-data-index-postgresql-image/resources/incubator-kie-kogito-data-index-postgresql-image.yaml
  packages/kogito-jobs-service-allinone-image/resources/incubator-kie-kogito-jobs-service-allinone-image.yaml
  packages/kogito-jobs-service-ephemeral-image/resources/incubator-kie-kogito-jobs-service-ephemeral-image.yaml
  packages/kogito-jobs-service-postgresql-image/resources/incubator-kie-kogito-jobs-service-postgresql-image.yaml
  packages/sonataflow-image-common/resources/modules/sonataflow/common/scripts/added/add-extension.sh
  packages/sonataflow-image-common/resources/modules/sonataflow/common/scripts/added/quarkus-mvn-plugin.sh
  packages/sonataflow-image-common/resources/modules/sonataflow/common/scripts/tests/bats/quarkus-mvn-plugin.bats
  packages/sonataflow-operator/Makefile
  packages/sonataflow-operator/config/manager/controllers_cfg.yaml
  packages/sonataflow-operator/config/manager/kustomization.yaml
  packages/sonataflow-operator/config/samples/sonataflow.org_v1alpha08_sonataflowplatform.yaml
  packages/sonataflow-operator/container-builder/api/build_types.go
  packages/sonataflow-operator/container-builder/builder/kubernetes/builder_kaniko_test.go
  packages/sonataflow-operator/container-builder/builder/kubernetes/builder_test.go
  packages/sonataflow-operator/container-builder/builder/kubernetes/testdata/sample.Dockerfile
  packages/sonataflow-operator/container-builder/examples/api/PlatformBuild_usingKanikowithCache.yaml
  packages/sonataflow-operator/hack/bump-version.sh
  packages/sonataflow-operator/hack/update_controllers_cfg.py
  packages/sonataflow-operator/install.js
  packages/sonataflow-operator/internal/controller/builder/kogitoserverlessbuild_manager.go
  packages/sonataflow-operator/internal/controller/cfg/controllers_cfg.go
  packages/sonataflow-operator/internal/controller/cfg/controllers_cfg_test.go
  packages/sonataflow-operator/internal/controller/cfg/testdata/controllers-cfg-test.yaml
  packages/sonataflow-operator/internal/controller/platform/platformutils_test.go
  packages/sonataflow-operator/internal/controller/platform/testdata/platformTest.Dockerfile
  packages/sonataflow-operator/internal/controller/profiles/common/object_creators_test.go
  packages/sonataflow-operator/internal/controller/profiles/common/persistence/postgresql.go
  packages/sonataflow-operator/internal/controller/profiles/dev/profile_dev_test.go
  packages/sonataflow-operator/internal/controller/profiles/preview/deployment_handler_test.go
  packages/sonataflow-operator/internal/controller/sonataflowplatform_controller_test.go
  packages/sonataflow-operator/operator.yaml
  packages/sonataflow-operator/package.json
  packages/sonataflow-operator/test/e2e/testdata/platform/noservices/gitops/ephemeral/02-sonataflow_platform.yaml
  packages/sonataflow-operator/test/e2e/testdata/platform/services/dev/ephemeral/02-sonataflow_platform.yaml
  packages/sonataflow-operator/test/e2e/testdata/platform/services/dev/postgreSQL/02-sonataflow_platform.yaml
  packages/sonataflow-operator/test/e2e/testdata/platform/services/gitops/cluster-wide-ephemeral/02-sonataflow_platform.yaml
  packages/sonataflow-operator/test/e2e/testdata/platform/services/gitops/ephemeral-data-index/02-sonataflow_platform.yaml
  packages/sonataflow-operator/test/e2e/testdata/platform/services/gitops/ephemeral-job-service/02-sonataflow_platform.yaml
  packages/sonataflow-operator/test/testdata/sonataflow.org_v1alpha08_sonataflowbuild.yaml
  packages/sonataflow-operator/test/testdata/sonataflow.org_v1alpha08_sonataflowplatform.yaml
  packages/sonataflow-operator/test/testdata/sonataflow.org_v1alpha08_sonataflowplatform_withBroker.yaml
  packages/sonataflow-operator/test/yaml.go
Labels: area:sonataflow
