Repository apache/incubator-kie-tools, pull requests merged in 2024-11, with the labels that each got.

#2692 kie-issues#2679: [SonataFlow] [reopen] SonataFlow Management Console on KIE Tools daily dev job
  .ci/jenkins/Jenkinsfile.daily-dev-publish
Labels: area:sonataflow, area:cicd

#2732 [10.0.x] NO-ISSUE: Release jobs fixes
  .ci/jenkins/release-jobs/Jenkinsfile.chrome-extensions
  .ci/jenkins/release-jobs/Jenkinsfile.cors-proxy
  .ci/jenkins/release-jobs/Jenkinsfile.extended-services
  .ci/jenkins/release-jobs/Jenkinsfile.kn-plugin-workflow
  .ci/jenkins/release-jobs/Jenkinsfile.kogito-serverless-operator
  .ci/jenkins/release-jobs/Jenkinsfile.npm-packages
  .ci/jenkins/release-jobs/Jenkinsfile.online-editor
  .ci/jenkins/release-jobs/Jenkinsfile.standalone-editors-cdn
  .ci/jenkins/shared-scripts/releaseUtils.groovy
Labels: pr: DO NOT MERGE

#2731 NO-ISSUE: Remove default admin user from jBPM Quarkus Dev UI
  packages/jbpm-quarkus-devui/jbpm-quarkus-devui-runtime/src/main/resources/application.properties
Labels: area:bpmn

#2741 NO-ISSUE: Adding missing legal files to Chrome Extension release Jenkins job
  .ci/jenkins/release-jobs/Jenkinsfile.chrome-extensions
Labels: area:cicd

#2740 NO-ISSUE: Align `devbox.lock` with `devbox` `0.13.6` and move files to `repo/`
  .github/supporting-files/ci/patterns/non-source-files-patterns.txt
  README.md
  devbox.lock
  repo/KOGITO_UPGRADE_PROCESS.md
  repo/MANUAL.md
  repo/NIX_DEV_ENV.md
Labels: area:monorepo

#2745 NO-ISSUE: Bump 'actions/upload-artifact' to v4
  .github/actions/upload-ci-reports-and-artifacts/action.yml
Labels: area:dependencies, area:monorepo, area:cicd

#2752 NO-ISSUE: Bump `xstream` to version `1.4.21`
  packages/dev-deployment-kogito-quarkus-blank-app/pom.xml
  packages/stunner-editors/pom.xml
Labels: area:dependencies

#2754 kie-tools#2753: Parameterize the groupId of `quarkus-maven-plugin` in "Kogito images" packages
  packages/kogito-base-builder-image/env/index.js
  packages/kogito-base-builder-image/package.json
  packages/kogito-data-index-ephemeral-image/env/index.js
  packages/kogito-data-index-ephemeral-image/package.json
  packages/kogito-data-index-postgresql-image/env/index.js
  packages/kogito-data-index-postgresql-image/package.json
  packages/kogito-jit-runner-image/env/index.js
  packages/kogito-jit-runner-image/package.json
  packages/kogito-jobs-service-allinone-image/env/index.js
  packages/kogito-jobs-service-allinone-image/package.json
  packages/kogito-jobs-service-ephemeral-image/env/index.js
  packages/kogito-jobs-service-ephemeral-image/package.json
  packages/kogito-jobs-service-postgresql-image/env/index.js
  packages/kogito-jobs-service-postgresql-image/package.json
  packages/sonataflow-builder-image/env/index.js
  packages/sonataflow-builder-image/package.json
  packages/sonataflow-devmode-image/env/index.js
  packages/sonataflow-devmode-image/package.json
  packages/sonataflow-image-common/README.md
  packages/sonataflow-image-common/env/index.js
  packages/sonataflow-image-common/resources/Makefile
  packages/sonataflow-image-common/resources/modules/kogito-project-versions/module.yaml
  packages/sonataflow-image-common/resources/modules/sonataflow/common/scripts/added/add-extension.sh
  packages/sonataflow-image-common/resources/modules/sonataflow/common/scripts/added/create-app.sh
  packages/sonataflow-image-common/resources/scripts/common.py
  packages/sonataflow-image-common/resources/scripts/versions_manager.py
  packages/sonataflow-management-console-image/env/index.js
  packages/sonataflow-management-console-image/package.json
Labels: area:sonataflow

#2764 NO-ISSUE: Disable 'merge' option for PRs after SonataFlow Operator migration is done
  .asf.yaml
Labels: area:monorepo, area:cicd
