Repository apache/incubator-kie-tools, pull requests merged in 2025-04, with the labels that each got.

#3039 kie-issues-3038: SonataFlow Dev UI is not accessible after migration to Quarkus 3.15.3
  packages/sonataflow-operator/internal/controller/profiles/common/constants/workflows.go
  packages/sonataflow-operator/internal/controller/profiles/common/properties/managed.go
  packages/sonataflow-operator/internal/controller/profiles/dev/states_dev.go
Labels: area:sonataflow

#3041 kie-tools#3037: include High Contrast Light possibility for Themes
  packages/editor/src/api/EditorTheme.ts
  packages/vscode-extension/src/VsCodeKieEditorController.ts
Labels: area:core

#3040 kie-issues#1512: DMN Editor: Context result row change causes expression data type to be reverted
  packages/boxed-expression-component/src/expressions/ContextExpression/ContextResultExpressionCell.tsx
  packages/boxed-expression-component/tests-e2e/boxedExpressions/context/populate.spec.ts
Labels: area:dmn

#2918 [kie-issues#1826] Sandbox: Render selected indicator in the DMN Runner form output card
  packages/dev-deployment-dmn-form-webapp/src/DmnFormPage.tsx
  packages/dmn-editor-envelope/src/DmnEditorFactory.tsx
  packages/dmn-editor-envelope/src/DmnEditorRoot.tsx
  packages/dmn-editor-envelope/src/NewDmnEditorEnvelopeApi.ts
  packages/dmn-editor-envelope/src/NewDmnEditorEnvelopeApiFactory.ts
  packages/dmn-editor-envelope/src/NewDmnEditorFactory.tsx
  packages/dmn-editor/src/DmnEditor.tsx
  packages/dmn-editor/stories/dmnEditorStoriesWrapper.tsx
  packages/form-dmn/src/FormDmnOutputs.tsx
  packages/form-dmn/src/styles.scss
  packages/form-dmn/tests/FormDmnOutputs.test.tsx
  packages/online-editor/src/dmnRunner/DmnRunnerDrawerPanelContent.tsx
  packages/online-editor/src/dmnRunner/DmnRunnerTable.tsx
Labels: area:dmn

#3025 [kie-issues#1884] Quarkus Upgrade to 3.15.3.1
  packages/maven-base/pom.xml
  packages/root-env/env/index.js
  packages/sonataflow-image-common/resources/modules/kogito-maven/common/configure
Labels: area:dependencies

#3052 kie-tools-issues#3051: [sonataflow-management-console-image] SIGWINCH on terminal resize
  packages/sonataflow-management-console-image/README.md
Labels: area:sonataflow

#3043 kie-issues#1799: [kn-workflow-plugin] Specify image on 'workflow deploy
  packages/kn-plugin-workflow/e2e-tests/deploy_test.go
  packages/kn-plugin-workflow/e2e-tests/helper_test.go
  packages/kn-plugin-workflow/pkg/command/deploy.go
Labels: area:sonataflow

#3062 kie-issues#1880: Update Kogito version to `999-20250316-SNAPSHOT`
  packages/maven-base/pom.xml
  packages/root-env/env/index.js
  repo/MANUAL.md
Labels: area:dependencies

#3063 kie-issues#1925: Kubernetes requests not complying with the insecurelyDisableTlsCertificateValidation flag on KIE Sandbox
  packages/k8s-yaml-to-apiserver-requests/dev/main.ts
  packages/k8s-yaml-to-apiserver-requests/package.json
  packages/k8s-yaml-to-apiserver-requests/src/k8sApiServerCalls.ts
  packages/k8s-yaml-to-apiserver-requests/src/k8sApiServerEndpointsByResourceKind.ts
  packages/online-editor/src/devDeployments/services/KubernetesService.ts
  pnpm-lock.yaml
  repo/graph.dot
  repo/graph.json
Labels: area:core

#3014 kie-issues#1872: Sandbox: Render selected indicator in the DMN Runner table output column when Highlight evaluation results is on
  packages/boxed-expression-component/src/expressions/DecisionTableExpression/DecisionTableExpression.css
  packages/boxed-expression-component/src/expressions/DecisionTableExpression/DecisionTableExpression.tsx
  packages/boxed-expression-component/src/table/BeeTable/BeeTableTd.tsx
  packages/boxed-expression-component/src/table/BeeTable/BeeTableThResizable.tsx
  packages/online-editor/src/dmnRunner/DmnRunnerTable.tsx
  packages/unitables-dmn/src/DmnRunnerOutputsTable.css
  packages/unitables-dmn/src/DmnRunnerOutputsTable.tsx
Labels: area:dmn

#3066 kie-issues#1912: DMN VS Code Extension: Evaluation highlights feature should not be available
  packages/dmn-editor-envelope/src/DmnEditorFactory.tsx
  packages/dmn-editor-envelope/src/DmnEditorRoot.tsx
  packages/dmn-editor-envelope/src/NewDmnEditorFactory.tsx
  packages/dmn-editor/src/DmnEditor.tsx
  packages/dmn-editor/src/overlaysPanel/OverlaysPanel.tsx
  packages/dmn-editor/src/settings/DmnEditorSettingsContext.tsx
  packages/dmn-editor/stories/dmnEditorStoriesWrapper.tsx
  packages/dmn-editor/stories/misc/evaluationHighlights/EvaluationHighlights.stories.tsx
Labels: area:dmn

#3077 NO-ISSUE: Update `JDT-LS` to 1.43.0
  packages/maven-base/pom.xml
  packages/vscode-java-code-completion-extension-plugin/pom.xml
  packages/vscode-java-code-completion-extension-plugin/vscode-java-code-completion-extension-plugin-core/META-INF/MANIFEST.MF
Labels: area:dependencies

#3061 Fix #3059 - Remove quarkus-kubernetes extension from SonataFlow builder image
  packages/sonataflow-builder-image/resources/incubator-kie-sonataflow-builder-image.yaml
  packages/sonataflow-builder-image/resources/modules/sonataflow/builder/build-config/module.yaml
  packages/sonataflow-builder-image/resources/modules/sonataflow/builder/runtime/community/module.yaml
Labels: area:sonataflow

#3091 NO-ISSUE: Increase Node.js memory limit to 6GB in the CI
  .ci/incubator-kie-tools-ci-build.Dockerfile
  .github/workflows/ci_build.yml
Labels: area:cicd

#3088 CVE-2024-21538 set resolutions for cross-spawn
  package.json
  pnpm-lock.yaml
Labels: area:dependencies

#3094 NO-ISSUE: Fix dev-deployment-dmn-form-webapp dev-webapp and how it parses OpenAPI specs
  packages/dev-deployment-dmn-form-webapp/dev-webapp/quarkus-app/pom.xml
  packages/dev-deployment-dmn-form-webapp/dev-webapp/start.js
  packages/dev-deployment-dmn-form-webapp/src/DmnDevDeploymentFormWebAppDataApi.tsx
  packages/dev-deployment-dmn-form-webapp/src/DmnFormErrorPage.tsx
  packages/jbpm-quarkus-devui/dev/src/main/resources/Sample.dmn
Labels: area:dmn

#3092 [kn-workflow] Failed to render eventRef that has only triggerEventRef
  .rat-excludes
  packages/kn-plugin-workflow/e2e-tests/deploy_test.go
  packages/kn-plugin-workflow/e2e-tests/quarkus_build_test.go
  packages/kn-plugin-workflow/e2e-tests/quarkus_convert_test.go
  packages/kn-plugin-workflow/e2e-tests/quarkus_create_test.go
  packages/kn-plugin-workflow/e2e-tests/quarkus_run_test.go
  packages/kn-plugin-workflow/e2e-tests/testdata/lock.sw.yaml
  packages/kn-plugin-workflow/go.mod
  packages/kn-plugin-workflow/go.sum
  packages/sonataflow-operator/api/go.mod
  packages/sonataflow-operator/api/go.sum
  packages/sonataflow-operator/container-builder/go.mod
  packages/sonataflow-operator/container-builder/go.sum
  packages/sonataflow-operator/go.mod
  packages/sonataflow-operator/go.sum
  packages/sonataflow-operator/go.work
  packages/sonataflow-operator/go.work.sum
  packages/sonataflow-operator/operator.yaml
  packages/sonataflow-operator/workflowproj/go.mod
  packages/sonataflow-operator/workflowproj/go.sum
Labels: area:sonataflow
