Repository apache/incubator-kie-tools, pull requests merged in 2025-07, with the labels that each got.

#3192 kie-issues#1906: New version of date and time conversion function on FEEL
  packages/feel-input-component/src/FeelConfigs.ts
Labels: area:dmn

#3189 kie-tools-issues#3184- [sonataflow-management-console-webapp] Management console is unable to sort workflow instances by ID
  packages/runtime-tools-swf-enveloped-components/src/workflowList/envelope/components/WorkflowListTable/WorkflowListTable.tsx
Labels: area:sonataflow

#3167 kie-tools-issues#3166: [serverless-logic-web-tools-swf-dev-mode-image] Wrong maven version (skip mvnw use)
  packages/sonataflow-image-common/resources/modules/kogito-maven/common/configure
  packages/sonataflow-image-common/resources/modules/kogito-maven/common/module.yaml
Labels: area:sonataflow

#3207 kie-tools#3205: [Serverless Logic Web Tools] Settings menu is not shown
  packages/serverless-logic-web-tools/e2e-tests/e2e/Settings.cy.ts
  packages/serverless-logic-web-tools/src/homepage/pageTemplate/OnlineEditorPage.tsx
Labels: area:sonataflow

#3188 kie-issues#890: DMN Editor: Adding a Decision to a Decision Service
  packages/dmn-editor/src/diagram/Diagram.tsx
  packages/dmn-editor/src/mutations/addDecisionToDecisionService.ts
  packages/dmn-editor/tests-e2e/__screenshots__/Google-Chrome/drds/decision-added-to-decision-service-collapsedDS.png
  packages/dmn-editor/tests-e2e/__screenshots__/Google-Chrome/drds/decision-added-to-decision-service.png
  packages/dmn-editor/tests-e2e/__screenshots__/chromium/drds/decision-added-to-decision-service-collapsedDS.png
  packages/dmn-editor/tests-e2e/__screenshots__/chromium/drds/decision-added-to-decision-service.png
  packages/dmn-editor/tests-e2e/__screenshots__/webkit/drds/decision-added-to-decision-service-collapsedDS.png
  packages/dmn-editor/tests-e2e/__screenshots__/webkit/drds/decision-added-to-decision-service.png
  packages/dmn-editor/tests-e2e/drds/modelDecisionServicesInDrds.spec.ts
Labels: pr: order: 1, area:dmn
