Repository apache/incubator-kie-tools, pull requests merged in 2025-01, with the labels that each got.

#2824 kie-issues#1725: KIE Tools: folder indicator is lost
  packages/online-editor/src/home/HomePage.tsx
Labels: area:dmn

#2831 kie-issues#2821: KIE Tools: TypeError when invoking Java method inside BKM
  packages/boxed-expression-component/src/expressions/FunctionExpression/JavaFunctionExpression.tsx
Labels: area:dmn

#2832 [kn-plugin-workflow] NO_ISSUE: Fix typo in gen_manifest help text
  packages/kn-plugin-workflow/pkg/command/gen_manifest.go
Labels: area:sonataflow

#2795 kie-issues#1677: [serverless-workflow-diagram-editor] marshallers (json/yaml) must support stateExecTimeout.(total/single) properties
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/definition/StateExecTimeout.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/definition/WorkflowTimeouts.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/marshall/json/StateExecTimeoutJsonSerializer.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-api/src/main/java/org/kie/workbench/common/stunner/sw/marshall/yaml/StateExecTimeoutYamlSerializer.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-client/src/main/java/org/kie/workbench/common/stunner/sw/client/shapes/CallbackStateShape.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-client/src/main/java/org/kie/workbench/common/stunner/sw/client/shapes/EventStateShape.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-client/src/main/java/org/kie/workbench/common/stunner/sw/client/shapes/ForEachStateShape.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-client/src/main/java/org/kie/workbench/common/stunner/sw/client/shapes/OperationStateShape.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-client/src/main/java/org/kie/workbench/common/stunner/sw/client/shapes/ParallelStateShape.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-client/src/main/java/org/kie/workbench/common/stunner/sw/client/shapes/SwitchStateShape.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-kogito-app/src/test/java/org/kie/workbench/common/stunner/sw/client/selenium/SWEditorSeleniumIT.java
  packages/serverless-workflow-diagram-editor/sw-editor/sw-editor-kogito-app/src/test/resources/org/kie/workbench/common/stunner/sw/client/selenium/StateExecTimeoutExample.sw.json
Labels: area:sonataflow

#2749 kie-issues#2718: [kn-plugin-workflow] Minify the openAPI spec files to trim components/schemas
  packages/kn-plugin-workflow/pkg/specs/openapi_minifier.go
  packages/kn-plugin-workflow/pkg/specs/openapi_minifier_test.go
  packages/kn-plugin-workflow/pkg/specs/ref_collector.go
  packages/kn-plugin-workflow/pkg/specs/testdata/refs/emptyworkflow.sw.yaml
  packages/kn-plugin-workflow/pkg/specs/testdata/refs/openapi-subflow34.expected.yaml
  packages/kn-plugin-workflow/pkg/specs/testdata/refs/openapi.expected.yaml
  packages/kn-plugin-workflow/pkg/specs/testdata/refs/openapi.yaml
  packages/kn-plugin-workflow/pkg/specs/testdata/refs/openapi1.expected.yaml
  packages/kn-plugin-workflow/pkg/specs/testdata/refs/openapi1.yaml
  packages/kn-plugin-workflow/pkg/specs/testdata/refs/openapi2.expected.yaml
  packages/kn-plugin-workflow/pkg/specs/testdata/refs/openapi2.yaml
  packages/kn-plugin-workflow/pkg/specs/testdata/refs/subflow1.sw.yaml
  packages/kn-plugin-workflow/pkg/specs/testdata/refs/subflow2.sw.yaml
  packages/kn-plugin-workflow/pkg/specs/testdata/refs/subflow3.sw.yaml
  packages/kn-plugin-workflow/pkg/specs/testdata/refs/subflow4.sw.yaml
  packages/kn-plugin-workflow/pkg/specs/testdata/refs/workflow.sw.yaml
  packages/kn-plugin-workflow/pkg/specs/testdata/refs/workflow1.sw.yaml
Labels: area:sonataflow

#2778 kie-issues#1647 [kn-plugin-workflow] Executing kn workflow run creates the container in the background
  packages/kn-plugin-workflow/e2e-tests/helper_test.go
  packages/kn-plugin-workflow/e2e-tests/run_test.go
  packages/kn-plugin-workflow/pkg/command/run.go
  packages/kn-plugin-workflow/pkg/common/containers.go
Labels: area:sonataflow

#2814 kie-issues#1669: jBPM Quarkus DevUI seems to not update the # of items
  packages/jbpm-quarkus-devui/jbpm-quarkus-devui-deployment/src/main/java/org/jbpm/quarkus/devui/deployment/DevConsoleProcessor.java
  packages/jbpm-quarkus-devui/jbpm-quarkus-devui-runtime/pom.xml
  packages/jbpm-quarkus-devui/jbpm-quarkus-devui-runtime/src/main/java/org/jbpm/quarkus/devui/runtime/rpc/DataIndexCounter.java
  packages/jbpm-quarkus-devui/jbpm-quarkus-devui-runtime/src/main/java/org/jbpm/quarkus/devui/runtime/rpc/JBPMDevUIEventPublisher.java
  packages/jbpm-quarkus-devui/jbpm-quarkus-devui-runtime/src/main/java/org/jbpm/quarkus/devui/runtime/rpc/JBPMDevuiJsonRPCService.java
Labels: area:bpmn

#2830 [incubator-kie-issues#1733] Remove JavaScript language option from Script Editor in BPMN Editor
  packages/kie-editors-dev-vscode-extension/e2e-tests/extension-editors-bpmn.test.ts
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/components/monaco_editor/MonacoEditorLanguage.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/scriptEditor/ScriptTypeFieldEditorPresenter.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/components/monaco_editor/MonacoEditorLanguageTest.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/conditionEditor/ConditionEditorFieldEditorPresenterTest.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/test/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/scriptEditor/ScriptTypeFieldEditorPresenterTest.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-marshalling/src/main/java/org/kie/workbench/common/stunner/bpmn/client/marshall/converters/tostunner/properties/Scripts.java
Labels: area:bpmn

#2841 kie-issues#2842 [sonataflow-operator] SonataFlow Operator goes into CrashLoopBackOff when workflow is deployed with cluster platform referenced platform
  packages/sonataflow-operator/internal/controller/profiles/common/object_creators.go
Labels: area:sonataflow

#2848 NO-ISSUE: Make sure `kie-tools` is using the latest timestamped SNAPSHOT from Kogito (999-20250105-SNAPSHOT)
  packages/maven-base/pom.xml
  packages/root-env/env/index.js
  repo/MANUAL.md
Labels: area:dependencies

#2847 NO-ISSUE: Removing not existing profile in Maven command in SWF Editor
  packages/serverless-workflow-diagram-editor/package.json
Labels: area:sonataflow

#2828 [kie-issues#1723] Allow dot character in metadata attributes
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/metaDataEditor/MetaDataListItemWidgetViewImpl.java
  packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/util/StringUtils.java
Labels: area:bpmn

#2850 NO-ISSUE [serverless-workflow-diagram-editor] bump j2cl-tools bom to 0.4
  packages/serverless-workflow-diagram-editor/appformer-bom/pom.xml
  packages/serverless-workflow-diagram-editor/kie-wb-common-bom/pom.xml
  packages/serverless-workflow-diagram-editor/kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/main/java/org/kie/workbench/common/stunner/client/lienzo/shape/view/ViewEventHandlerManager.java
  packages/serverless-workflow-diagram-editor/kie-wb-common-stunner/kie-wb-common-stunner-client/kie-wb-common-stunner-lienzo/src/test/java/org/kie/workbench/common/stunner/client/lienzo/shape/view/wires/WiresContainerShapeViewTest.java
  packages/serverless-workflow-diagram-editor/kie-wb-common-stunner/kie-wb-common-stunner-core/kie-wb-common-stunner-api/kie-wb-common-stunner-core-api/src/main/java/org/kie/workbench/common/stunner/core/definition/jsadapter/JsDefinitionAdapter.java
  packages/serverless-workflow-diagram-editor/lienzo-core/src/main/java/com/ait/lienzo/tools/client/NObjectJSO.java
  packages/serverless-workflow-diagram-editor/lienzo-core/src/main/java/com/ait/lienzo/tools/client/collection/NFastStringMap.java
  packages/serverless-workflow-diagram-editor/lienzo-tests/src/main/java/com/ait/lienzo/test/stub/overlays/DomGlobal.java
  packages/serverless-workflow-diagram-editor/lienzo-tests/src/main/java/com/ait/lienzo/test/stub/overlays/JsMap.java
  packages/serverless-workflow-diagram-editor/pom.xml
Labels: area:sonataflow

#2835 kie-tools#2623: [kn-plugin-workflow] Parameterize Quarkus version with $(build-env versions.quarkus)
  packages/kn-plugin-workflow/e2e-tests/helper_test.go
  packages/kn-plugin-workflow/e2e-tests/quarkus_convert_test.go
  packages/kn-plugin-workflow/e2e-tests/quarkus_create_test.go
  packages/kn-plugin-workflow/pkg/command/quarkus/deploy_test.go
  packages/kn-plugin-workflow/pkg/command/quarkus/testdata/knative.yml
Labels: area:sonataflow

#2855 NO-ISSUE: Add LICENSE and DISCLAIMER-WIP in non-source file list
  .github/supporting-files/ci/patterns/non-source-files-patterns.txt
Labels: area:monorepo

#2846 kie-issues#1636: DMN Editor throw an error opening Included Models tab
  packages/dmn-editor/src/includedModels/IncludedModels.css
  packages/dmn-editor/src/includedModels/IncludedModels.tsx
Labels: area:dmn

#2856 kie-tools-issues#2582: [serverless-logic-web-tools] CORS on Dev Mode deployment on OpenShift
  packages/serverless-logic-web-tools-swf-deployment-quarkus-app/src/main/resources/application.properties
  packages/sonataflow-quarkus-devui/sonataflow-quarkus-devui/src/main/resources/application.properties
Labels: area:sonataflow

#2858 [serverless-logic-web-tools] NO-ISSUE: Use env vars instead hardcoded repository url
  packages/serverless-logic-web-tools/env/index.js
  packages/serverless-logic-web-tools/src/samples/SampleConstants.ts
  packages/serverless-logic-web-tools/webpack.config.ts
Labels: area:sonataflow

#2857 NO-ISSUE: Remove leftover directories from examples due to merge conflicts
  examples/commit-message-validation-service/Makefile
  examples/jbpm-compact-architecture-example/src/main/resources/application.properties
Labels: area:monorepo

#2859 NO-ISSUE: Bump vsce to `3.2.1` version
  examples/micro-frontends-multiplying-architecture-base64png-editor-vscode-extension/package.json
  examples/micro-frontends-multiplying-architecture-todo-list-view-vscode-extension/package.json
  packages/bpmn-vscode-extension/package.json
  packages/dmn-vscode-extension/package.json
  packages/extended-services-vscode-extension/package.json
  packages/kie-editors-dev-vscode-extension/package.json
  packages/pmml-vscode-extension/package.json
  packages/serverless-workflow-vscode-extension/package.json
  packages/vscode-extension-dashbuilder-editor/package.json
  packages/vscode-extension-kie-ba-bundle/package.json
  packages/vscode-extension-kogito-bundle/package.json
  packages/yard-vscode-extension/package.json
  pnpm-lock.yaml
Labels: area:dependencies, area:monorepo

#2802 kie-issues#1694: Apache KIE Extended Services extension issues
  packages/cors-proxy/package.json
  packages/extended-services-vscode-extension/env/index.js
  packages/extended-services-vscode-extension/package.json
  packages/extended-services-vscode-extension/src/Connection.ts
  packages/extended-services-vscode-extension/src/LocalExtendedServices.ts
  packages/extended-services-vscode-extension/src/Validator.ts
  packages/extended-services-vscode-extension/src/configurations/Configuration.ts
  packages/extended-services-vscode-extension/src/configurations/ConfigurationWatcher.ts
  packages/extended-services-vscode-extension/src/extension/extension-browser.ts
  packages/extended-services-vscode-extension/src/extension/extension-main.ts
  packages/extended-services-vscode-extension/src/requests/PingRequest.ts
  packages/extended-services-vscode-extension/src/requests/ValidationRequests.ts
  packages/extended-services-vscode-extension/webpack.config.js
  packages/kie-sandbox-distribution/package.json
  pnpm-lock.yaml
Labels: area:bpmn, area:dmn

#2819 NO-ISSUE: Upgrade Maven plugins to newer versions and Apache parent from `32` to `33`
  packages/dashbuilder/pom.xml
  packages/dev-deployment-dmn-form-webapp/dev-webapp/quarkus-app/pom.xml
  packages/dev-deployment-kogito-quarkus-blank-app/pom.xml
  packages/extended-services/pom.xml
  packages/maven-base/pom.xml
  packages/serverless-logic-web-tools-swf-deployment-quarkus-app/pom.xml
  packages/serverless-workflow-diagram-editor/pom.xml
  packages/stunner-editors/pom.xml
Labels: pr: DO NOT MERGE, area:dependencies, area:monorepo

#2861 NO-ISSUE: Fix for daily dev Jenkins CI failing to build due to missing git config and hardlinked files
  .ci/jenkins/Jenkinsfile.daily-dev-publish
  .ci/jenkins/Jenkinsfile.release-build
  .ci/jenkins/Jenkinsfile.release-candidate
  .ci/jenkins/Jenkinsfile.release-dry-run
  .ci/jenkins/Jenkinsfile.release-publish
  .ci/jenkins/release-jobs/Jenkinsfile.kogito-task-console
  .ci/jenkins/shared-scripts/buildUtils.groovy
  packages/kie-sandbox-accelerator-quarkus/package.json
  packages/kogito-management-console/entrypoint.sh
  packages/sonataflow-management-console-image/resources/modules/sonataflow/management-console/added/entrypoint.sh
Labels: area:monorepo, area:cicd

#2864 kie-tools-issues#2761: [Serverless Logic Web Tools] Devmode deployment URL redirection
  packages/serverless-logic-web-tools/src/editor/hooks/useDeployDropdownItems.tsx
  packages/serverless-logic-web-tools/src/openshift/dropdown/OpenShiftDeploymentDropdownItem.tsx
Labels: area:sonataflow

#2860 kie-issues#1552: Test Scenario Editor: Update `@kie-tools/dmn-vscode-extension` to add the new Test Scenario Editor
  packages/dmn-vscode-extension/README.md
  packages/dmn-vscode-extension/package.json
  packages/dmn-vscode-extension/src/extension/extension.ts
  packages/dmn-vscode-extension/src/webview/NewTestScenarioEditorEnvelopeApp.ts
  packages/dmn-vscode-extension/webpack.config.js
  packages/scesim-editor-envelope/src/TestScenarioEditorRoot.tsx
  packages/scesim-editor/.storybook/preview.tsx
  packages/scesim-editor/package.json
  packages/scesim-editor/src/TestScenarioEditor.css
  packages/scesim-editor/src/TestScenarioEditor.tsx
  packages/scesim-editor/src/creation/TestScenarioCreationPanel.tsx
  packages/scesim-editor/src/drawer/TestScenarioDrawerDataSelectorPanel.css
  packages/scesim-editor/src/drawer/TestScenarioDrawerDataSelectorPanel.tsx
  packages/scesim-editor/stories/dev/DevWebApp.stories.tsx
  packages/scesim-editor/stories/scesimEditorStoriesWrapper.tsx
  packages/scesim-editor/tests-e2e/__fixtures__/editor.ts
  packages/scesim-editor/tests-e2e/__screenshots__/Google-Chrome/misc/emptyExpression/create-a-new-test-scenario.png
  packages/scesim-editor/tests-e2e/__screenshots__/Google-Chrome/scesimEditor/backgroundTable/background-table-decision.png
  packages/scesim-editor/tests-e2e/__screenshots__/Google-Chrome/scesimEditor/backgroundTable/background-table-rule.png
  packages/scesim-editor/tests-e2e/__screenshots__/chromium/misc/emptyExpression/create-a-new-test-scenario.png
  packages/scesim-editor/tests-e2e/__screenshots__/chromium/scesimEditor/backgroundTable/background-table-decision.png
  packages/scesim-editor/tests-e2e/__screenshots__/chromium/scesimEditor/backgroundTable/background-table-rule.png
  packages/scesim-editor/tests-e2e/__screenshots__/webkit/misc/emptyExpression/create-a-new-test-scenario.png
  packages/scesim-editor/tests-e2e/__screenshots__/webkit/scesimEditor/backgroundTable/background-table-decision.png
  packages/scesim-editor/tests-e2e/__screenshots__/webkit/scesimEditor/backgroundTable/background-table-rule.png
  pnpm-lock.yaml
  repo/graph.dot
  repo/graph.json
Labels: area:scesim

#2720 kie-issues#1595: Sandbox: Add "Open in Boxed Expression Editor" button in the DMN Runner form output cards
  packages/boxed-expression-component/README.md
  packages/dmn-editor-envelope/src/DmnEditorFactory.tsx
  packages/dmn-editor-envelope/src/DmnEditorRoot.tsx
  packages/dmn-editor-envelope/src/NewDmnEditorChannelApi.ts
  packages/dmn-editor-envelope/src/NewDmnEditorEnvelopeApi.ts
  packages/dmn-editor-envelope/src/NewDmnEditorEnvelopeApiFactory.ts
  packages/dmn-editor-envelope/src/NewDmnEditorFactory.tsx
  packages/dmn-editor/src/DmnEditor.tsx
  packages/form-dmn/src/FormDmnOutputs.tsx
  packages/online-editor/src/dmnRunner/DmnRunnerContext.tsx
  packages/online-editor/src/dmnRunner/DmnRunnerContextProvider.tsx
  packages/online-editor/src/dmnRunner/DmnRunnerDrawerPanelContent.tsx
  packages/online-editor/src/editor/EditorPage.tsx
  packages/online-editor/src/editor/Toolbar/NewFileDropdownMenu.tsx
  packages/online-editor/src/envelope/NewDmnEditorEnvelopeApp.ts
  packages/online-editor/src/envelopeLocator/EditorEnvelopeLocatorFactory.ts
  packages/online-editor/src/envelopeLocator/hooks/EditorEnvelopeLocatorContext.tsx
  packages/online-editor/src/home/HomePage.tsx
Labels: area:dmn

#2870 kie-issues#1779: Update deprecated react-json-view dependency
  packages/boxed-expression-component/package.json
  packages/runtime-tools-process-enveloped-components/package.json
  packages/runtime-tools-process-enveloped-components/src/processDetails/envelope/components/ProcessVariables/ProcessVariables.tsx
  packages/runtime-tools-shared-enveloped-components/package.json
  packages/runtime-tools-swf-enveloped-components/package.json
  packages/runtime-tools-swf-enveloped-components/src/workflowDetails/envelope/components/WorkflowVariables/WorkflowVariables.tsx
  packages/runtime-tools-swf-enveloped-components/src/workflowForm/envelope/components/WorkflowResult/WorkflowResult.tsx
  pnpm-lock.yaml
Labels: area:dependencies

#2845 kie-issues#1679 : If the bottom of the overlay panel is close to editor bottom, it adds a vertical overflow after toggling an option
  packages/dmn-editor/src/overlaysPanel/OverlaysPanel.tsx
Labels: area:dmn

#2697 kie-issues#2659: [SonataFlow] Migrate DBMigration Image from SonataFlow operator repository to kie-tools
  .ci/jenkins/Jenkinsfile.daily-dev-publish
  .ci/jenkins/release-jobs/Jenkinsfile.kogito-db-migrator-tool
  .gitignore
  packages/kogito-db-migrator-tool-image/README.md
  packages/kogito-db-migrator-tool-image/env/index.js
  packages/kogito-db-migrator-tool-image/install.js
  packages/kogito-db-migrator-tool-image/package.json
  packages/kogito-db-migrator-tool-image/resources/incubator-kie-kogito-db-migrator-tool-image.yaml
  packages/kogito-db-migrator-tool-image/resources/modules/kogito-db-migrator-tool/postgresql/added/kogito-app-launch.sh
  packages/kogito-db-migrator-tool-image/resources/modules/kogito-db-migrator-tool/postgresql/configure
  packages/kogito-db-migrator-tool-image/resources/modules/kogito-db-migrator-tool/postgresql/module.yaml
  packages/kogito-db-migrator-tool/.gitignore
  packages/kogito-db-migrator-tool/README.md
  packages/kogito-db-migrator-tool/env/index.js
  packages/kogito-db-migrator-tool/install.js
  packages/kogito-db-migrator-tool/package.json
  packages/kogito-db-migrator-tool/pom.xml
  packages/kogito-db-migrator-tool/src/main/java/org/kie/kogito/migrator/postgresql/DBConnectionChecker.java
  packages/kogito-db-migrator-tool/src/main/java/org/kie/kogito/migrator/postgresql/DBMigrator.java
  packages/kogito-db-migrator-tool/src/main/java/org/kie/kogito/migrator/postgresql/MigrationService.java
  packages/kogito-db-migrator-tool/src/main/resources/application.properties
  packages/kogito-db-migrator-tool/src/test/java/org/kie/kogito/migrator/postgresql/DBConnectionCheckerTest.java
  packages/kogito-db-migrator-tool/src/test/java/org/kie/kogito/migrator/postgresql/DBMigratorTest.java
  packages/kogito-db-migrator-tool/src/test/java/org/kie/kogito/migrator/postgresql/MigrationServiceTest.java
  packages/maven-base/pom.xml
  packages/sonataflow-image-common/resources/scripts/build-kogito-apps-components.sh
  pnpm-lock.yaml
  repo/graph.dot
  repo/graph.json
Labels: area:sonataflow

#2883 kie-issues#1164: Cut/Copy/Paste Functionality Issues in DRD View: DMN Editor Extension for VSCode (macOS)
  packages/boxed-expression-component/src/expressionVariable/ExpressionVariableMenu.tsx
  packages/boxed-expression-component/src/table/BeeTable/BeeTable.tsx
  packages/boxed-expression-component/src/table/BeeTable/BeeTableEditableCellContent.tsx
  packages/boxed-expression-component/src/table/BeeTable/BeeTableThResizable.tsx
  packages/dmn-editor/src/diagram/nodes/EditableNodeLabel.tsx
  packages/dmn-editor/src/feel/InlineFeelNameInput.tsx
  packages/dmn-editor/src/propertiesPanel/BeePropertiesPanel.tsx
  packages/dmn-editor/src/propertiesPanel/BoxedExpressionPropertiesPanel.tsx
  packages/dmn-editor/src/propertiesPanel/DiagramPropertiesPanel.tsx
Labels: area:dmn
